using CropQc.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CropQc.Data.Migrations
{
    /// <inheritdoc />
    [DbContext(typeof(CropQcDbContext))]
    [Migration("20260711213000_AddCanonicalGrowers")]
    public partial class AddCanonicalGrowers : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            if (migrationBuilder.ActiveProvider.Contains("Npgsql", StringComparison.OrdinalIgnoreCase))
            {
                migrationBuilder.Sql("""
                    CREATE TABLE IF NOT EXISTS "CanonicalGrowers" (
                        "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                        "DisplayName" character varying(200) NOT NULL,
                        "NormalizedKey" character varying(200) NOT NULL,
                        "IsActive" boolean NOT NULL,
                        "MergedIntoCanonicalGrowerId" integer NULL,
                        "CreatedAt" timestamp with time zone NOT NULL,
                        "UpdatedAt" timestamp with time zone NOT NULL,
                        CONSTRAINT "PK_CanonicalGrowers" PRIMARY KEY ("Id"),
                        CONSTRAINT "FK_CanonicalGrowers_CanonicalGrowers_MergedIntoCanonicalGrowerId" FOREIGN KEY ("MergedIntoCanonicalGrowerId") REFERENCES "CanonicalGrowers" ("Id") ON DELETE NO ACTION
                    );

                    CREATE INDEX IF NOT EXISTS "IX_CanonicalGrowers_NormalizedKey" ON "CanonicalGrowers" ("NormalizedKey");
                    CREATE INDEX IF NOT EXISTS "IX_CanonicalGrowers_MergedIntoCanonicalGrowerId" ON "CanonicalGrowers" ("MergedIntoCanonicalGrowerId");

                    CREATE TABLE IF NOT EXISTS "CanonicalGrowerAliases" (
                        "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                        "CanonicalGrowerId" integer NOT NULL,
                        "AliasName" character varying(200) NOT NULL,
                        "NormalizedAliasKey" character varying(200) NOT NULL,
                        "SourceSystem" character varying(100) NULL,
                        "IsActive" boolean NOT NULL,
                        "CreatedAt" timestamp with time zone NOT NULL,
                        "UpdatedAt" timestamp with time zone NOT NULL,
                        CONSTRAINT "PK_CanonicalGrowerAliases" PRIMARY KEY ("Id"),
                        CONSTRAINT "FK_CanonicalGrowerAliases_CanonicalGrowers_CanonicalGrowerId" FOREIGN KEY ("CanonicalGrowerId") REFERENCES "CanonicalGrowers" ("Id") ON DELETE CASCADE
                    );

                    CREATE INDEX IF NOT EXISTS "IX_CanonicalGrowerAliases_NormalizedAliasKey" ON "CanonicalGrowerAliases" ("NormalizedAliasKey");
                    CREATE INDEX IF NOT EXISTS "IX_CanonicalGrowerAliases_CanonicalGrowerId_NormalizedAliasKey" ON "CanonicalGrowerAliases" ("CanonicalGrowerId", "NormalizedAliasKey");

                    CREATE TABLE IF NOT EXISTS "CanonicalGrowerNumbers" (
                        "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                        "CanonicalGrowerId" integer NOT NULL,
                        "GrowerNumber" character varying(50) NOT NULL,
                        "NormalizedGrowerNumber" character varying(50) NOT NULL,
                        "SourceSystem" character varying(100) NULL,
                        "Facility" character varying(100) NULL,
                        "CropYear" integer NULL,
                        "IsActive" boolean NOT NULL,
                        "CreatedAt" timestamp with time zone NOT NULL,
                        "UpdatedAt" timestamp with time zone NOT NULL,
                        CONSTRAINT "PK_CanonicalGrowerNumbers" PRIMARY KEY ("Id"),
                        CONSTRAINT "FK_CanonicalGrowerNumbers_CanonicalGrowers_CanonicalGrowerId" FOREIGN KEY ("CanonicalGrowerId") REFERENCES "CanonicalGrowers" ("Id") ON DELETE CASCADE
                    );

                    CREATE INDEX IF NOT EXISTS "IX_CanonicalGrowerNumbers_NormalizedGrowerNumber" ON "CanonicalGrowerNumbers" ("NormalizedGrowerNumber");
                    CREATE INDEX IF NOT EXISTS "IX_CanonicalGrowerNumbers_CanonicalGrowerId_NormalizedGrowerNumber" ON "CanonicalGrowerNumbers" ("CanonicalGrowerId", "NormalizedGrowerNumber");

                    INSERT INTO "CanonicalGrowers" ("DisplayName", "NormalizedKey", "IsActive", "MergedIntoCanonicalGrowerId", "CreatedAt", "UpdatedAt")
                    SELECT 'Vantage Orchard', 'VANTAGE_ORCHARD', TRUE, NULL, now(), now()
                    WHERE NOT EXISTS (SELECT 1 FROM "CanonicalGrowers" WHERE "NormalizedKey" = 'VANTAGE_ORCHARD');

                    INSERT INTO "CanonicalGrowers" ("DisplayName", "NormalizedKey", "IsActive", "MergedIntoCanonicalGrowerId", "CreatedAt", "UpdatedAt")
                    SELECT 'Stayman Flats', 'STAYMAN_FLATS', TRUE, NULL, now(), now()
                    WHERE NOT EXISTS (SELECT 1 FROM "CanonicalGrowers" WHERE "NormalizedKey" = 'STAYMAN_FLATS');

                    DO $$
                    DECLARE
                        vantage_id integer;
                        stayman_id integer;
                    BEGIN
                        SELECT "Id" INTO vantage_id FROM "CanonicalGrowers" WHERE "NormalizedKey" = 'VANTAGE_ORCHARD' ORDER BY "Id" LIMIT 1;
                        SELECT "Id" INTO stayman_id FROM "CanonicalGrowers" WHERE "NormalizedKey" = 'STAYMAN_FLATS' ORDER BY "Id" LIMIT 1;

                        IF vantage_id IS NOT NULL THEN
                            IF NOT EXISTS (SELECT 1 FROM "CanonicalGrowerAliases" WHERE "CanonicalGrowerId" = vantage_id AND "NormalizedAliasKey" = 'VANTAGE_ORCHARD') THEN
                                INSERT INTO "CanonicalGrowerAliases" ("CanonicalGrowerId", "AliasName", "NormalizedAliasKey", "SourceSystem", "IsActive", "CreatedAt", "UpdatedAt")
                                VALUES (vantage_id, 'Vantage Orchard', 'VANTAGE_ORCHARD', NULL, TRUE, now(), now());
                            END IF;

                            IF NOT EXISTS (SELECT 1 FROM "CanonicalGrowerAliases" WHERE "CanonicalGrowerId" = vantage_id AND "NormalizedAliasKey" = 'VANTAGE_ORCHARD_NON_CHILEAN') THEN
                                INSERT INTO "CanonicalGrowerAliases" ("CanonicalGrowerId", "AliasName", "NormalizedAliasKey", "SourceSystem", "IsActive", "CreatedAt", "UpdatedAt")
                                VALUES (vantage_id, 'Vantage Orchard Non Chilean', 'VANTAGE_ORCHARD_NON_CHILEAN', NULL, TRUE, now(), now());
                            END IF;
                        END IF;

                        IF stayman_id IS NOT NULL THEN
                            IF NOT EXISTS (SELECT 1 FROM "CanonicalGrowerAliases" WHERE "CanonicalGrowerId" = stayman_id AND "NormalizedAliasKey" = 'STAYMAN_FLATS') THEN
                                INSERT INTO "CanonicalGrowerAliases" ("CanonicalGrowerId", "AliasName", "NormalizedAliasKey", "SourceSystem", "IsActive", "CreatedAt", "UpdatedAt")
                                VALUES (stayman_id, 'Stayman Flats', 'STAYMAN_FLATS', NULL, TRUE, now(), now());
                            END IF;

                            IF NOT EXISTS (SELECT 1 FROM "CanonicalGrowerAliases" WHERE "CanonicalGrowerId" = stayman_id AND "NormalizedAliasKey" = 'STAYMAN') THEN
                                INSERT INTO "CanonicalGrowerAliases" ("CanonicalGrowerId", "AliasName", "NormalizedAliasKey", "SourceSystem", "IsActive", "CreatedAt", "UpdatedAt")
                                VALUES (stayman_id, 'Stayman', 'STAYMAN', NULL, TRUE, now(), now());
                            END IF;

                            IF NOT EXISTS (SELECT 1 FROM "CanonicalGrowerAliases" WHERE "CanonicalGrowerId" = stayman_id AND "NormalizedAliasKey" = 'STAYMAN_FLATS_NON_CHILEAN') THEN
                                INSERT INTO "CanonicalGrowerAliases" ("CanonicalGrowerId", "AliasName", "NormalizedAliasKey", "SourceSystem", "IsActive", "CreatedAt", "UpdatedAt")
                                VALUES (stayman_id, 'Stayman Flats Non Chilean', 'STAYMAN_FLATS_NON_CHILEAN', NULL, TRUE, now(), now());
                            END IF;
                        END IF;
                    END $$;
                    """);
                return;
            }

            migrationBuilder.Sql("""
                IF OBJECT_ID(N'[CanonicalGrowers]', N'U') IS NULL
                BEGIN
                    CREATE TABLE [CanonicalGrowers] (
                        [Id] int IDENTITY(1,1) NOT NULL,
                        [DisplayName] nvarchar(200) NOT NULL,
                        [NormalizedKey] nvarchar(200) NOT NULL,
                        [IsActive] bit NOT NULL,
                        [MergedIntoCanonicalGrowerId] int NULL,
                        [CreatedAt] datetimeoffset NOT NULL,
                        [UpdatedAt] datetimeoffset NOT NULL,
                        CONSTRAINT [PK_CanonicalGrowers] PRIMARY KEY ([Id]),
                        CONSTRAINT [FK_CanonicalGrowers_CanonicalGrowers_MergedIntoCanonicalGrowerId] FOREIGN KEY ([MergedIntoCanonicalGrowerId]) REFERENCES [CanonicalGrowers] ([Id]) ON DELETE NO ACTION
                    );
                    CREATE INDEX [IX_CanonicalGrowers_NormalizedKey] ON [CanonicalGrowers] ([NormalizedKey]);
                    CREATE INDEX [IX_CanonicalGrowers_MergedIntoCanonicalGrowerId] ON [CanonicalGrowers] ([MergedIntoCanonicalGrowerId]);
                END

                IF OBJECT_ID(N'[CanonicalGrowerAliases]', N'U') IS NULL
                BEGIN
                    CREATE TABLE [CanonicalGrowerAliases] (
                        [Id] int IDENTITY(1,1) NOT NULL,
                        [CanonicalGrowerId] int NOT NULL,
                        [AliasName] nvarchar(200) NOT NULL,
                        [NormalizedAliasKey] nvarchar(200) NOT NULL,
                        [SourceSystem] nvarchar(100) NULL,
                        [IsActive] bit NOT NULL,
                        [CreatedAt] datetimeoffset NOT NULL,
                        [UpdatedAt] datetimeoffset NOT NULL,
                        CONSTRAINT [PK_CanonicalGrowerAliases] PRIMARY KEY ([Id]),
                        CONSTRAINT [FK_CanonicalGrowerAliases_CanonicalGrowers_CanonicalGrowerId] FOREIGN KEY ([CanonicalGrowerId]) REFERENCES [CanonicalGrowers] ([Id]) ON DELETE CASCADE
                    );
                    CREATE INDEX [IX_CanonicalGrowerAliases_NormalizedAliasKey] ON [CanonicalGrowerAliases] ([NormalizedAliasKey]);
                    CREATE INDEX [IX_CanonicalGrowerAliases_CanonicalGrowerId_NormalizedAliasKey] ON [CanonicalGrowerAliases] ([CanonicalGrowerId], [NormalizedAliasKey]);
                END

                IF OBJECT_ID(N'[CanonicalGrowerNumbers]', N'U') IS NULL
                BEGIN
                    CREATE TABLE [CanonicalGrowerNumbers] (
                        [Id] int IDENTITY(1,1) NOT NULL,
                        [CanonicalGrowerId] int NOT NULL,
                        [GrowerNumber] nvarchar(50) NOT NULL,
                        [NormalizedGrowerNumber] nvarchar(50) NOT NULL,
                        [SourceSystem] nvarchar(100) NULL,
                        [Facility] nvarchar(100) NULL,
                        [CropYear] int NULL,
                        [IsActive] bit NOT NULL,
                        [CreatedAt] datetimeoffset NOT NULL,
                        [UpdatedAt] datetimeoffset NOT NULL,
                        CONSTRAINT [PK_CanonicalGrowerNumbers] PRIMARY KEY ([Id]),
                        CONSTRAINT [FK_CanonicalGrowerNumbers_CanonicalGrowers_CanonicalGrowerId] FOREIGN KEY ([CanonicalGrowerId]) REFERENCES [CanonicalGrowers] ([Id]) ON DELETE CASCADE
                    );
                    CREATE INDEX [IX_CanonicalGrowerNumbers_NormalizedGrowerNumber] ON [CanonicalGrowerNumbers] ([NormalizedGrowerNumber]);
                    CREATE INDEX [IX_CanonicalGrowerNumbers_CanonicalGrowerId_NormalizedGrowerNumber] ON [CanonicalGrowerNumbers] ([CanonicalGrowerId], [NormalizedGrowerNumber]);
                END

                DECLARE @now datetimeoffset = SYSDATETIMEOFFSET();

                IF NOT EXISTS (SELECT 1 FROM [CanonicalGrowers] WHERE [NormalizedKey] = N'VANTAGE_ORCHARD')
                BEGIN
                    INSERT INTO [CanonicalGrowers] ([DisplayName], [NormalizedKey], [IsActive], [MergedIntoCanonicalGrowerId], [CreatedAt], [UpdatedAt])
                    VALUES (N'Vantage Orchard', N'VANTAGE_ORCHARD', 1, NULL, @now, @now);
                END

                IF NOT EXISTS (SELECT 1 FROM [CanonicalGrowers] WHERE [NormalizedKey] = N'STAYMAN_FLATS')
                BEGIN
                    INSERT INTO [CanonicalGrowers] ([DisplayName], [NormalizedKey], [IsActive], [MergedIntoCanonicalGrowerId], [CreatedAt], [UpdatedAt])
                    VALUES (N'Stayman Flats', N'STAYMAN_FLATS', 1, NULL, @now, @now);
                END

                DECLARE @vantageId int = (SELECT TOP (1) [Id] FROM [CanonicalGrowers] WHERE [NormalizedKey] = N'VANTAGE_ORCHARD' ORDER BY [Id]);
                DECLARE @staymanId int = (SELECT TOP (1) [Id] FROM [CanonicalGrowers] WHERE [NormalizedKey] = N'STAYMAN_FLATS' ORDER BY [Id]);

                IF @vantageId IS NOT NULL
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM [CanonicalGrowerAliases] WHERE [CanonicalGrowerId] = @vantageId AND [NormalizedAliasKey] = N'VANTAGE_ORCHARD')
                        INSERT INTO [CanonicalGrowerAliases] ([CanonicalGrowerId], [AliasName], [NormalizedAliasKey], [SourceSystem], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (@vantageId, N'Vantage Orchard', N'VANTAGE_ORCHARD', NULL, 1, @now, @now);
                    IF NOT EXISTS (SELECT 1 FROM [CanonicalGrowerAliases] WHERE [CanonicalGrowerId] = @vantageId AND [NormalizedAliasKey] = N'VANTAGE_ORCHARD_NON_CHILEAN')
                        INSERT INTO [CanonicalGrowerAliases] ([CanonicalGrowerId], [AliasName], [NormalizedAliasKey], [SourceSystem], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (@vantageId, N'Vantage Orchard Non Chilean', N'VANTAGE_ORCHARD_NON_CHILEAN', NULL, 1, @now, @now);
                END

                IF @staymanId IS NOT NULL
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM [CanonicalGrowerAliases] WHERE [CanonicalGrowerId] = @staymanId AND [NormalizedAliasKey] = N'STAYMAN_FLATS')
                        INSERT INTO [CanonicalGrowerAliases] ([CanonicalGrowerId], [AliasName], [NormalizedAliasKey], [SourceSystem], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (@staymanId, N'Stayman Flats', N'STAYMAN_FLATS', NULL, 1, @now, @now);
                    IF NOT EXISTS (SELECT 1 FROM [CanonicalGrowerAliases] WHERE [CanonicalGrowerId] = @staymanId AND [NormalizedAliasKey] = N'STAYMAN')
                        INSERT INTO [CanonicalGrowerAliases] ([CanonicalGrowerId], [AliasName], [NormalizedAliasKey], [SourceSystem], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (@staymanId, N'Stayman', N'STAYMAN', NULL, 1, @now, @now);
                    IF NOT EXISTS (SELECT 1 FROM [CanonicalGrowerAliases] WHERE [CanonicalGrowerId] = @staymanId AND [NormalizedAliasKey] = N'STAYMAN_FLATS_NON_CHILEAN')
                        INSERT INTO [CanonicalGrowerAliases] ([CanonicalGrowerId], [AliasName], [NormalizedAliasKey], [SourceSystem], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (@staymanId, N'Stayman Flats Non Chilean', N'STAYMAN_FLATS_NON_CHILEAN', NULL, 1, @now, @now);
                END
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            if (migrationBuilder.ActiveProvider.Contains("Npgsql", StringComparison.OrdinalIgnoreCase))
            {
                migrationBuilder.Sql("""
                    DROP TABLE IF EXISTS "CanonicalGrowerNumbers";
                    DROP TABLE IF EXISTS "CanonicalGrowerAliases";
                    DROP TABLE IF EXISTS "CanonicalGrowers";
                    """);
                return;
            }

            migrationBuilder.Sql("""
                IF OBJECT_ID(N'[CanonicalGrowerNumbers]', N'U') IS NOT NULL DROP TABLE [CanonicalGrowerNumbers];
                IF OBJECT_ID(N'[CanonicalGrowerAliases]', N'U') IS NOT NULL DROP TABLE [CanonicalGrowerAliases];
                IF OBJECT_ID(N'[CanonicalGrowers]', N'U') IS NOT NULL DROP TABLE [CanonicalGrowers];
                """);
        }
    }
}
