using CropQc.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CropQc.Data.Migrations
{
    /// <inheritdoc />
    [DbContext(typeof(CropQcDbContext))]
    [Migration("20260711195500_LinkVarietyColorsToFruitProfiles")]
    public partial class LinkVarietyColorsToFruitProfiles : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            if (migrationBuilder.ActiveProvider.Contains("Npgsql", StringComparison.OrdinalIgnoreCase))
            {
                migrationBuilder.Sql("""
                    CREATE TABLE IF NOT EXISTS "VarietyColorConfigurations" (
                        "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                        "FruitProfileId" integer NULL,
                        "VarietyKey" character varying(100) NOT NULL,
                        "VarietyName" character varying(150) NOT NULL,
                        "HexColor" character varying(7) NOT NULL,
                        "CreatedAt" timestamp with time zone NOT NULL,
                        "UpdatedAt" timestamp with time zone NOT NULL,
                        "UpdatedByUserId" integer NULL,
                        CONSTRAINT "PK_VarietyColorConfigurations" PRIMARY KEY ("Id"),
                        CONSTRAINT "FK_VarietyColorConfigurations_FruitProfiles_FruitProfileId" FOREIGN KEY ("FruitProfileId") REFERENCES "FruitProfiles" ("Id") ON DELETE SET NULL,
                        CONSTRAINT "FK_VarietyColorConfigurations_Users_UpdatedByUserId" FOREIGN KEY ("UpdatedByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
                    );

                    CREATE UNIQUE INDEX IF NOT EXISTS "IX_VarietyColorConfigurations_VarietyKey" ON "VarietyColorConfigurations" ("VarietyKey");
                    CREATE INDEX IF NOT EXISTS "IX_VarietyColorConfigurations_FruitProfileId" ON "VarietyColorConfigurations" ("FruitProfileId");

                    ALTER TABLE "VarietyColorConfigurations" ADD COLUMN IF NOT EXISTS "FruitProfileId" integer NULL;

                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM pg_constraint
                            WHERE conname = 'FK_VarietyColorConfigurations_FruitProfiles_FruitProfileId'
                        ) THEN
                            ALTER TABLE "VarietyColorConfigurations"
                            ADD CONSTRAINT "FK_VarietyColorConfigurations_FruitProfiles_FruitProfileId"
                            FOREIGN KEY ("FruitProfileId") REFERENCES "FruitProfiles" ("Id") ON DELETE SET NULL;
                        END IF;
                    END $$;

                    UPDATE "VarietyColorConfigurations" vc
                    SET "FruitProfileId" = (
                        SELECT fp2."Id"
                        FROM "FruitProfiles" fp2
                        WHERE
                            UPPER(REPLACE(REPLACE(CASE WHEN fp2."IsOrganic" = TRUE AND fp2."Name" LIKE 'Organic %' THEN SUBSTRING(fp2."Name" FROM 9) ELSE fp2."Name" END, ' ', ''), '_', '')) =
                            UPPER(REPLACE(REPLACE(vc."VarietyName", ' ', ''), '_', ''))
                            OR UPPER(REPLACE(REPLACE(fp2."VarietyCode", ' ', ''), '_', '')) = UPPER(REPLACE(REPLACE(vc."VarietyKey", ' ', ''), '_', ''))
                        ORDER BY fp2."IsOrganic", CASE WHEN fp2."Name" = vc."VarietyName" THEN 0 ELSE 1 END, fp2."Id"
                        LIMIT 1
                    )
                    WHERE vc."FruitProfileId" IS NULL
                      AND EXISTS (
                          SELECT 1
                          FROM "FruitProfiles" fp2
                          WHERE
                              UPPER(REPLACE(REPLACE(CASE WHEN fp2."IsOrganic" = TRUE AND fp2."Name" LIKE 'Organic %' THEN SUBSTRING(fp2."Name" FROM 9) ELSE fp2."Name" END, ' ', ''), '_', '')) =
                              UPPER(REPLACE(REPLACE(vc."VarietyName", ' ', ''), '_', ''))
                              OR UPPER(REPLACE(REPLACE(fp2."VarietyCode", ' ', ''), '_', '')) = UPPER(REPLACE(REPLACE(vc."VarietyKey", ' ', ''), '_', ''))
                      );
                    """);
                return;
            }

            migrationBuilder.Sql("""
                IF OBJECT_ID(N'[VarietyColorConfigurations]', N'U') IS NULL
                BEGIN
                    CREATE TABLE [VarietyColorConfigurations] (
                        [Id] int IDENTITY(1,1) NOT NULL,
                        [FruitProfileId] int NULL,
                        [VarietyKey] nvarchar(100) NOT NULL,
                        [VarietyName] nvarchar(150) NOT NULL,
                        [HexColor] nvarchar(7) NOT NULL,
                        [CreatedAt] datetimeoffset NOT NULL,
                        [UpdatedAt] datetimeoffset NOT NULL,
                        [UpdatedByUserId] int NULL,
                        CONSTRAINT [PK_VarietyColorConfigurations] PRIMARY KEY ([Id]),
                        CONSTRAINT [FK_VarietyColorConfigurations_FruitProfiles_FruitProfileId] FOREIGN KEY ([FruitProfileId]) REFERENCES [FruitProfiles] ([Id]) ON DELETE SET NULL,
                        CONSTRAINT [FK_VarietyColorConfigurations_Users_UpdatedByUserId] FOREIGN KEY ([UpdatedByUserId]) REFERENCES [Users] ([Id]) ON DELETE SET NULL
                    );
                    CREATE UNIQUE INDEX [IX_VarietyColorConfigurations_VarietyKey] ON [VarietyColorConfigurations] ([VarietyKey]);
                    CREATE INDEX [IX_VarietyColorConfigurations_FruitProfileId] ON [VarietyColorConfigurations] ([FruitProfileId]);
                END

                IF COL_LENGTH(N'[VarietyColorConfigurations]', N'FruitProfileId') IS NULL
                BEGIN
                    ALTER TABLE [VarietyColorConfigurations] ADD [FruitProfileId] int NULL;
                    CREATE INDEX [IX_VarietyColorConfigurations_FruitProfileId] ON [VarietyColorConfigurations] ([FruitProfileId]);
                    ALTER TABLE [VarietyColorConfigurations] WITH CHECK ADD CONSTRAINT [FK_VarietyColorConfigurations_FruitProfiles_FruitProfileId] FOREIGN KEY([FruitProfileId]) REFERENCES [FruitProfiles] ([Id]) ON DELETE SET NULL;
                END

                UPDATE vc
                SET [FruitProfileId] = fp.[Id]
                FROM [VarietyColorConfigurations] vc
                CROSS APPLY (
                    SELECT TOP (1) fp2.[Id]
                    FROM [FruitProfiles] fp2
                    WHERE
                        UPPER(REPLACE(REPLACE(CASE WHEN fp2.[IsOrganic] = 1 AND fp2.[Name] LIKE N'Organic %' THEN SUBSTRING(fp2.[Name], 9, LEN(fp2.[Name])) ELSE fp2.[Name] END, N' ', N''), N'_', N'')) =
                        UPPER(REPLACE(REPLACE(vc.[VarietyName], N' ', N''), N'_', N''))
                        OR UPPER(REPLACE(REPLACE(fp2.[VarietyCode], N' ', N''), N'_', N'')) = UPPER(REPLACE(REPLACE(vc.[VarietyKey], N' ', N''), N'_', N''))
                    ORDER BY fp2.[IsOrganic], CASE WHEN fp2.[Name] = vc.[VarietyName] THEN 0 ELSE 1 END, fp2.[Id]
                ) fp
                WHERE vc.[FruitProfileId] IS NULL;
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            if (migrationBuilder.ActiveProvider.Contains("Npgsql", StringComparison.OrdinalIgnoreCase))
            {
                migrationBuilder.Sql("""
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_name = 'VarietyColorConfigurations'
                              AND column_name = 'FruitProfileId'
                        ) THEN
                            IF EXISTS (
                                SELECT 1
                                FROM pg_constraint
                                WHERE conname = 'FK_VarietyColorConfigurations_FruitProfiles_FruitProfileId'
                            ) THEN
                                ALTER TABLE "VarietyColorConfigurations" DROP CONSTRAINT "FK_VarietyColorConfigurations_FruitProfiles_FruitProfileId";
                            END IF;

                            DROP INDEX IF EXISTS "IX_VarietyColorConfigurations_FruitProfileId";
                            ALTER TABLE "VarietyColorConfigurations" DROP COLUMN "FruitProfileId";
                        END IF;
                    END $$;
                    """);
                return;
            }

            migrationBuilder.Sql("""
                IF COL_LENGTH(N'[VarietyColorConfigurations]', N'FruitProfileId') IS NOT NULL
                BEGIN
                    IF OBJECT_ID(N'[FK_VarietyColorConfigurations_FruitProfiles_FruitProfileId]', N'F') IS NOT NULL
                    BEGIN
                        ALTER TABLE [VarietyColorConfigurations] DROP CONSTRAINT [FK_VarietyColorConfigurations_FruitProfiles_FruitProfileId];
                    END
                    IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_VarietyColorConfigurations_FruitProfileId' AND object_id = OBJECT_ID(N'[VarietyColorConfigurations]'))
                    BEGIN
                        DROP INDEX [IX_VarietyColorConfigurations_FruitProfileId] ON [VarietyColorConfigurations];
                    END
                    ALTER TABLE [VarietyColorConfigurations] DROP COLUMN [FruitProfileId];
                END
                """);
        }
    }
}
