// <auto-generated />
using System;
using CropQc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CropQc.Data.Migrations
{
    [DbContext(typeof(CropQcDbContext))]
    partial class CropQcDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CropQc.Data.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AfterValuesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeforeValuesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EntityKey")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SourceApplication")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityName", "EntityKey");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("CropQc.Data.Entities.DashboardConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("DashboardConfigurations");
                });

            modelBuilder.Entity("CropQc.Data.Entities.DefectType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DefectTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Bruise"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Sunburn"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Bitter Pit"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Scald"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Decay"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Puncture"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "Watercore"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Name = "Limb Rub"
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            Name = "Stem Bowl Crack"
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            Name = "Internal Browning"
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("CropQc.Data.Entities.FruitProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FruitType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOrganic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ProductionType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("VarietyCode")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("VarietyCode")
                        .IsUnique();

                    b.ToTable("FruitProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Fuji",
                            FruitType = "Apple",
                            IsActive = true,
                            IsOrganic = false,
                            Name = "Fuji",
                            ProductionType = "Conventional",
                            VarietyCode = "FUJI"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Gala",
                            FruitType = "Apple",
                            IsActive = true,
                            IsOrganic = false,
                            Name = "Gala",
                            ProductionType = "Conventional",
                            VarietyCode = "GALA"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Golden Delicious",
                            FruitType = "Apple",
                            IsActive = true,
                            IsOrganic = false,
                            Name = "Golden Delicious",
                            ProductionType = "Conventional",
                            VarietyCode = "GOLD"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Granny Smith",
                            FruitType = "Apple",
                            IsActive = true,
                            IsOrganic = false,
                            Name = "Granny Smith",
                            ProductionType = "Conventional",
                            VarietyCode = "GSMT"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Honey Crisp",
                            FruitType = "Apple",
                            IsActive = true,
                            IsOrganic = false,
                            Name = "Honey Crisp",
                            ProductionType = "Conventional",
                            VarietyCode = "HONY"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Organic Fuji",
                            FruitType = "Apple",
                            IsActive = true,
                            IsOrganic = true,
                            Name = "Organic Fuji",
                            ProductionType = "Organic",
                            VarietyCode = "ORFU"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Organic Gala",
                            FruitType = "Apple",
                            IsActive = true,
                            IsOrganic = true,
                            Name = "Organic Gala",
                            ProductionType = "Organic",
                            VarietyCode = "ORGA"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Organic Golden Delicious",
                            FruitType = "Apple",
                            IsActive = true,
                            IsOrganic = true,
                            Name = "Organic Golden Delicious",
                            ProductionType = "Organic",
                            VarietyCode = "ORGD"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Organic Granny Smith",
                            FruitType = "Apple",
                            IsActive = true,
                            IsOrganic = true,
                            Name = "Organic Granny Smith",
                            ProductionType = "Organic",
                            VarietyCode = "ORGS"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Organic Honey Crisp",
                            FruitType = "Apple",
                            IsActive = true,
                            IsOrganic = true,
                            Name = "Organic Honey Crisp",
                            ProductionType = "Organic",
                            VarietyCode = "ORHC"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Organic Pink Lady",
                            FruitType = "Apple",
                            IsActive = true,
                            IsOrganic = true,
                            Name = "Organic Pink Lady",
                            ProductionType = "Organic",
                            VarietyCode = "ORPL"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Organic Red Delicious",
                            FruitType = "Apple",
                            IsActive = true,
                            IsOrganic = true,
                            Name = "Organic Red Delicious",
                            ProductionType = "Organic",
                            VarietyCode = "ORRD"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Pink Lady",
                            FruitType = "Apple",
                            IsActive = true,
                            IsOrganic = false,
                            Name = "Pink Lady",
                            ProductionType = "Conventional",
                            VarietyCode = "PINK"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Red Delicious",
                            FruitType = "Apple",
                            IsActive = true,
                            IsOrganic = false,
                            Name = "Red Delicious",
                            ProductionType = "Conventional",
                            VarietyCode = "RED"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Mardi Gras",
                            FruitType = "Pear",
                            IsActive = true,
                            IsOrganic = false,
                            Name = "Mardi Gras",
                            ProductionType = "Conventional",
                            VarietyCode = "MDGS"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Bosc",
                            FruitType = "Pear",
                            IsActive = true,
                            IsOrganic = false,
                            Name = "Bosc",
                            ProductionType = "Conventional",
                            VarietyCode = "BOSC"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Bartlett",
                            FruitType = "Pear",
                            IsActive = true,
                            IsOrganic = false,
                            Name = "Bartlett",
                            ProductionType = "Conventional",
                            VarietyCode = "BART"
                        },
                        new
                        {
                            Id = 18,
                            Description = "D'Anjou",
                            FruitType = "Pear",
                            IsActive = true,
                            IsOrganic = false,
                            Name = "D'Anjou",
                            ProductionType = "Conventional",
                            VarietyCode = "DANJ"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Organic Bartlett",
                            FruitType = "Pear",
                            IsActive = true,
                            IsOrganic = true,
                            Name = "Organic Bartlett",
                            ProductionType = "Organic",
                            VarietyCode = "ORBA"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Organic Bosc",
                            FruitType = "Pear",
                            IsActive = true,
                            IsOrganic = true,
                            Name = "Organic Bosc",
                            ProductionType = "Organic",
                            VarietyCode = "ORBO"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Organic D'anjou",
                            FruitType = "Pear",
                            IsActive = true,
                            IsOrganic = true,
                            Name = "Organic D'anjou",
                            ProductionType = "Organic",
                            VarietyCode = "ORDA"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Autumn Glory",
                            FruitType = "Apple",
                            IsActive = true,
                            IsOrganic = false,
                            Name = "Autumn Glory",
                            ProductionType = "Conventional",
                            VarietyCode = "ATGL"
                        });
                });

            modelBuilder.Entity("CropQc.Data.Entities.FruitSizeConversionThreshold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FruitType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MinimumWeightGrams")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<int>("SizeCategory")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FruitType", "MinimumWeightGrams");

                    b.HasIndex("FruitType", "SizeCategory")
                        .IsUnique();

                    b.ToTable("FruitSizeConversionThresholds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FruitType = "Apple",
                            IsActive = true,
                            MinimumWeightGrams = 405.0000m,
                            SizeCategory = 48
                        },
                        new
                        {
                            Id = 2,
                            FruitType = "Apple",
                            IsActive = true,
                            MinimumWeightGrams = 354.0000m,
                            SizeCategory = 56
                        },
                        new
                        {
                            Id = 3,
                            FruitType = "Apple",
                            IsActive = true,
                            MinimumWeightGrams = 298.0000m,
                            SizeCategory = 64
                        },
                        new
                        {
                            Id = 4,
                            FruitType = "Apple",
                            IsActive = true,
                            MinimumWeightGrams = 264.0000m,
                            SizeCategory = 72
                        },
                        new
                        {
                            Id = 5,
                            FruitType = "Apple",
                            IsActive = true,
                            MinimumWeightGrams = 238.0000m,
                            SizeCategory = 80
                        },
                        new
                        {
                            Id = 6,
                            FruitType = "Apple",
                            IsActive = true,
                            MinimumWeightGrams = 215.0000m,
                            SizeCategory = 88
                        },
                        new
                        {
                            Id = 7,
                            FruitType = "Apple",
                            IsActive = true,
                            MinimumWeightGrams = 190.0000m,
                            SizeCategory = 100
                        },
                        new
                        {
                            Id = 8,
                            FruitType = "Apple",
                            IsActive = true,
                            MinimumWeightGrams = 167.0000m,
                            SizeCategory = 113
                        },
                        new
                        {
                            Id = 9,
                            FruitType = "Apple",
                            IsActive = true,
                            MinimumWeightGrams = 153.0000m,
                            SizeCategory = 125
                        },
                        new
                        {
                            Id = 10,
                            FruitType = "Apple",
                            IsActive = true,
                            MinimumWeightGrams = 136.0000m,
                            SizeCategory = 138
                        },
                        new
                        {
                            Id = 11,
                            FruitType = "Apple",
                            IsActive = true,
                            MinimumWeightGrams = 128.0000m,
                            SizeCategory = 150
                        },
                        new
                        {
                            Id = 12,
                            FruitType = "Apple",
                            IsActive = true,
                            MinimumWeightGrams = 116.0000m,
                            SizeCategory = 163
                        },
                        new
                        {
                            Id = 13,
                            FruitType = "Apple",
                            IsActive = true,
                            MinimumWeightGrams = 108.0000m,
                            SizeCategory = 175
                        },
                        new
                        {
                            Id = 14,
                            FruitType = "Apple",
                            IsActive = true,
                            MinimumWeightGrams = 96.0000m,
                            SizeCategory = 198
                        },
                        new
                        {
                            Id = 15,
                            FruitType = "Apple",
                            IsActive = true,
                            MinimumWeightGrams = 88.0000m,
                            SizeCategory = 216
                        },
                        new
                        {
                            Id = 16,
                            FruitType = "Pear",
                            IsActive = true,
                            MinimumWeightGrams = 360.0000m,
                            SizeCategory = 50
                        },
                        new
                        {
                            Id = 17,
                            FruitType = "Pear",
                            IsActive = true,
                            MinimumWeightGrams = 303.0000m,
                            SizeCategory = 60
                        },
                        new
                        {
                            Id = 18,
                            FruitType = "Pear",
                            IsActive = true,
                            MinimumWeightGrams = 260.0000m,
                            SizeCategory = 70
                        },
                        new
                        {
                            Id = 19,
                            FruitType = "Pear",
                            IsActive = true,
                            MinimumWeightGrams = 227.0000m,
                            SizeCategory = 80
                        },
                        new
                        {
                            Id = 20,
                            FruitType = "Pear",
                            IsActive = true,
                            MinimumWeightGrams = 203.0000m,
                            SizeCategory = 90
                        },
                        new
                        {
                            Id = 21,
                            FruitType = "Pear",
                            IsActive = true,
                            MinimumWeightGrams = 182.0000m,
                            SizeCategory = 100
                        },
                        new
                        {
                            Id = 22,
                            FruitType = "Pear",
                            IsActive = true,
                            MinimumWeightGrams = 165.0000m,
                            SizeCategory = 110
                        },
                        new
                        {
                            Id = 23,
                            FruitType = "Pear",
                            IsActive = true,
                            MinimumWeightGrams = 151.0000m,
                            SizeCategory = 120
                        },
                        new
                        {
                            Id = 24,
                            FruitType = "Pear",
                            IsActive = true,
                            MinimumWeightGrams = 135.0000m,
                            SizeCategory = 135
                        },
                        new
                        {
                            Id = 25,
                            FruitType = "Pear",
                            IsActive = true,
                            MinimumWeightGrams = 121.0000m,
                            SizeCategory = 150
                        },
                        new
                        {
                            Id = 26,
                            FruitType = "Pear",
                            IsActive = true,
                            MinimumWeightGrams = 110.0000m,
                            SizeCategory = 165
                        },
                        new
                        {
                            Id = 27,
                            FruitType = "Pear",
                            IsActive = true,
                            MinimumWeightGrams = 101.0000m,
                            SizeCategory = 180
                        },
                        new
                        {
                            Id = 28,
                            FruitType = "Pear",
                            IsActive = true,
                            MinimumWeightGrams = 94.0000m,
                            SizeCategory = 193
                        },
                        new
                        {
                            Id = 29,
                            FruitType = "Pear",
                            IsActive = true,
                            MinimumWeightGrams = 87.0000m,
                            SizeCategory = 210
                        },
                        new
                        {
                            Id = 30,
                            FruitType = "Pear",
                            IsActive = true,
                            MinimumWeightGrams = 81.0000m,
                            SizeCategory = 225
                        });
                });

            modelBuilder.Entity("CropQc.Data.Entities.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "W1",
                            IsActive = true,
                            Name = "W1"
                        },
                        new
                        {
                            Id = 2,
                            Code = "W2",
                            IsActive = true,
                            Name = "W2"
                        },
                        new
                        {
                            Id = 3,
                            Code = "W3",
                            IsActive = true,
                            Name = "W3"
                        },
                        new
                        {
                            Id = 4,
                            Code = "W4",
                            IsActive = true,
                            Name = "W4"
                        },
                        new
                        {
                            Id = 5,
                            Code = "WF",
                            IsActive = true,
                            Name = "WF"
                        },
                        new
                        {
                            Id = 6,
                            Code = "US1",
                            IsActive = true,
                            Name = "US1"
                        },
                        new
                        {
                            Id = 7,
                            Code = "US2",
                            IsActive = true,
                            Name = "US2"
                        },
                        new
                        {
                            Id = 8,
                            Code = "USF",
                            IsActive = true,
                            Name = "USF"
                        });
                });

            modelBuilder.Entity("CropQc.Data.Entities.OfflineSyncItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTimeOffset?>("LastAttemptedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("LocalEntityId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("QcStationId")
                        .HasColumnType("int");

                    b.Property<long?>("ServerEntityId")
                        .HasColumnType("bigint");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("SyncedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("QcStationId", "EntityName", "LocalEntityId")
                        .IsUnique()
                        .HasFilter("[QcStationId] IS NOT NULL");

                    b.ToTable("OfflineSyncItems");
                });

            modelBuilder.Entity("CropQc.Data.Entities.PasswordPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MinimumLength")
                        .HasColumnType("int");

                    b.Property<int>("PasswordExpirationDays")
                        .HasColumnType("int");

                    b.Property<bool>("RequireLowercase")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireNumber")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireSymbol")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireUppercase")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("PasswordPolicies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            MinimumLength = 8,
                            PasswordExpirationDays = 365,
                            RequireLowercase = true,
                            RequireNumber = true,
                            RequireSymbol = true,
                            RequireUppercase = true
                        });
                });

            modelBuilder.Entity("CropQc.Data.Entities.QcFruitDefect", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DefectTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("QcFruitReadingId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DefectTypeId");

                    b.HasIndex("QcFruitReadingId", "DefectTypeId")
                        .IsUnique();

                    b.ToTable("QcFruitDefects");
                });

            modelBuilder.Entity("CropQc.Data.Entities.QcFruitReading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("GradeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Pressure1Lbs")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Pressure1Source")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Pressure2Lbs")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Pressure2Source")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("QcSampleId")
                        .HasColumnType("bigint");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int");

                    b.Property<int?>("SizeCategory")
                        .HasColumnType("int");

                    b.Property<string>("SizeStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasDefaultValue("NotCalculated");

                    b.Property<int?>("StarchScaleValueId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("WeightGrams")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.HasIndex("StarchScaleValueId");

                    b.HasIndex("QcSampleId", "RowNumber")
                        .IsUnique();

                    b.ToTable("QcFruitReadings", t =>
                        {
                            t.HasCheckConstraint("CK_QcFruitReadings_CompletedRequiresCoreFields", "([IsCompleted] = 0) OR ([Pressure1Lbs] IS NOT NULL AND [Pressure2Lbs] IS NOT NULL AND [WeightGrams] IS NOT NULL AND [GradeId] IS NOT NULL)");

                            t.HasCheckConstraint("CK_QcFruitReadings_RowNumber_1_50", "[RowNumber] >= 1 AND [RowNumber] <= 50");
                        });
                });

            modelBuilder.Entity("CropQc.Data.Entities.QcPhoto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CapturedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DriveId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FileId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FolderId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhotoSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhotoType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("QcSampleId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ReceiptId")
                        .HasColumnType("bigint");

                    b.Property<string>("SharePointDriveId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SharePointItemId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Legacy");

                    b.Property<DateTimeOffset?>("UploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("WebUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CapturedByUserId");

                    b.HasIndex("QcSampleId");

                    b.HasIndex("ReceiptId");

                    b.HasIndex("SharePointDriveId", "SharePointItemId")
                        .IsUnique();

                    b.HasIndex("StorageProvider", "FileId");

                    b.ToTable("QcPhotos", t =>
                        {
                            t.HasCheckConstraint("CK_QcPhotos_ReceiptOrSample", "([ReceiptId] IS NOT NULL AND [QcSampleId] IS NULL) OR ([ReceiptId] IS NULL AND [QcSampleId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("CropQc.Data.Entities.QcSample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("ActualSampleSize")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EmailStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PhotoStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("QcStationId")
                        .HasColumnType("int");

                    b.Property<long>("ReceiptId")
                        .HasColumnType("bigint");

                    b.Property<int>("SampleSequenceNumber")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SampleTakenAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("SampleTypeId")
                        .HasColumnType("int");

                    b.Property<string>("StarchStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TakenByUserId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("QcStationId");

                    b.HasIndex("SampleTypeId");

                    b.HasIndex("TakenByUserId");

                    b.HasIndex("ReceiptId", "SampleSequenceNumber")
                        .IsUnique();

                    b.ToTable("QcSamples");
                });

            modelBuilder.Entity("CropQc.Data.Entities.QcStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ApiKeyCreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ApiKeyHash")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ApiKeyLastFour")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTimeOffset?>("ApiKeyRotatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DeviceIdentifier")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastSeenIp")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("LastSyncAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("StationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("WarehouseCode")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int?>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("StationCode")
                        .IsUnique();

                    b.HasIndex("WarehouseId");

                    b.ToTable("QcStations");
                });

            modelBuilder.Entity("CropQc.Data.Entities.QcSummaryEmailLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EmailBodySnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<bool>("IsOverride")
                        .HasColumnType("bit");

                    b.Property<bool>("IsResend")
                        .HasColumnType("bit");

                    b.Property<string>("MessageId")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MissingItemsSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverrideReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long?>("QcSampleId")
                        .HasColumnType("bigint");

                    b.Property<long>("ReceiptId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReplyToAddress")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("ReportSnapshotReference")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ResendReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("SentByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ToAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("QcSampleId");

                    b.HasIndex("ReceiptId");

                    b.HasIndex("SentByUserId");

                    b.ToTable("QcSummaryEmailLogs");
                });

            modelBuilder.Entity("CropQc.Data.Entities.Receipt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("BinCount")
                        .HasColumnType("int");

                    b.Property<string>("CompuTechReceiptId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CropYear")
                        .HasColumnType("int");

                    b.Property<int>("FruitProfileId")
                        .HasColumnType("int");

                    b.Property<string>("GrowerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LotCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompuTechReceiptId");

                    b.HasIndex("FruitProfileId");

                    b.HasIndex("RoomId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("CropQc.Data.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Full dashboard and configuration access.",
                            IsSystemRole = true,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Manage QC receiving workflows and resend summaries.",
                            IsSystemRole = true,
                            Name = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Capture receiving samples and QC readings.",
                            IsSystemRole = true,
                            Name = "QC User"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Read-only dashboard access.",
                            IsSystemRole = true,
                            Name = "Viewer"
                        });
                });

            modelBuilder.Entity("CropQc.Data.Entities.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PermissionKey")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId", "PermissionKey")
                        .IsUnique();

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("CropQc.Data.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapacityBins")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId", "Code")
                        .IsUnique();

                    b.HasIndex("WarehouseId", "Name")
                        .IsUnique();

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("CropQc.Data.Entities.SampleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SampleTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Receiving Sample"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Door Sample"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Line QC Sample"
                        });
                });

            modelBuilder.Entity("CropQc.Data.Entities.StarchScale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FruitProfileId")
                        .HasColumnType("int");

                    b.Property<string>("FruitType")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FruitProfileId");

                    b.HasIndex("Name", "FruitType", "FruitProfileId")
                        .IsUnique()
                        .HasFilter("[FruitType] IS NOT NULL AND [FruitProfileId] IS NOT NULL");

                    b.ToTable("StarchScales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "6-point starch scale"
                        });
                });

            modelBuilder.Entity("CropQc.Data.Entities.StarchScaleValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("StarchScaleId")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)");

                    b.HasKey("Id");

                    b.HasIndex("StarchScaleId", "Value")
                        .IsUnique();

                    b.ToTable("StarchScaleValues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            SortOrder = 10,
                            StarchScaleId = 1,
                            Value = 1.0m
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            SortOrder = 20,
                            StarchScaleId = 1,
                            Value = 1.2m
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            SortOrder = 30,
                            StarchScaleId = 1,
                            Value = 1.5m
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            SortOrder = 40,
                            StarchScaleId = 1,
                            Value = 1.8m
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            SortOrder = 50,
                            StarchScaleId = 1,
                            Value = 2.0m
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            SortOrder = 60,
                            StarchScaleId = 1,
                            Value = 2.5m
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            SortOrder = 70,
                            StarchScaleId = 1,
                            Value = 3.0m
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            SortOrder = 80,
                            StarchScaleId = 1,
                            Value = 3.5m
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            SortOrder = 90,
                            StarchScaleId = 1,
                            Value = 4.0m
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            SortOrder = 100,
                            StarchScaleId = 1,
                            Value = 4.5m
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            SortOrder = 110,
                            StarchScaleId = 1,
                            Value = 5.0m
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            SortOrder = 120,
                            StarchScaleId = 1,
                            Value = 6.0m
                        });
                });

            modelBuilder.Entity("CropQc.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("GoogleSubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("PasswordLastChangedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleSubjectId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CropQc.Data.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("CropQc.Data.Entities.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "EBS",
                            IsActive = true,
                            Name = "EBS"
                        },
                        new
                        {
                            Id = 2,
                            Code = "DH",
                            IsActive = true,
                            Name = "DH"
                        },
                        new
                        {
                            Id = 3,
                            Code = "McDougall",
                            IsActive = true,
                            Name = "McDougall"
                        },
                        new
                        {
                            Id = 4,
                            Code = "WP",
                            IsActive = true,
                            Name = "WP"
                        });
                });

            modelBuilder.Entity("CropQc.Data.Entities.AuditLog", b =>
                {
                    b.HasOne("CropQc.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CropQc.Data.Entities.OfflineSyncItem", b =>
                {
                    b.HasOne("CropQc.Data.Entities.QcStation", "QcStation")
                        .WithMany()
                        .HasForeignKey("QcStationId");

                    b.Navigation("QcStation");
                });

            modelBuilder.Entity("CropQc.Data.Entities.QcFruitDefect", b =>
                {
                    b.HasOne("CropQc.Data.Entities.DefectType", "DefectType")
                        .WithMany()
                        .HasForeignKey("DefectTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CropQc.Data.Entities.QcFruitReading", "QcFruitReading")
                        .WithMany("Defects")
                        .HasForeignKey("QcFruitReadingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefectType");

                    b.Navigation("QcFruitReading");
                });

            modelBuilder.Entity("CropQc.Data.Entities.QcFruitReading", b =>
                {
                    b.HasOne("CropQc.Data.Entities.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CropQc.Data.Entities.QcSample", "QcSample")
                        .WithMany("FruitReadings")
                        .HasForeignKey("QcSampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CropQc.Data.Entities.StarchScaleValue", "StarchScaleValue")
                        .WithMany()
                        .HasForeignKey("StarchScaleValueId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Grade");

                    b.Navigation("QcSample");

                    b.Navigation("StarchScaleValue");
                });

            modelBuilder.Entity("CropQc.Data.Entities.QcPhoto", b =>
                {
                    b.HasOne("CropQc.Data.Entities.User", "CapturedByUser")
                        .WithMany()
                        .HasForeignKey("CapturedByUserId");

                    b.HasOne("CropQc.Data.Entities.QcSample", "QcSample")
                        .WithMany("Photos")
                        .HasForeignKey("QcSampleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CropQc.Data.Entities.Receipt", "Receipt")
                        .WithMany("Photos")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CapturedByUser");

                    b.Navigation("QcSample");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("CropQc.Data.Entities.QcSample", b =>
                {
                    b.HasOne("CropQc.Data.Entities.QcStation", "QcStation")
                        .WithMany("Samples")
                        .HasForeignKey("QcStationId");

                    b.HasOne("CropQc.Data.Entities.Receipt", "Receipt")
                        .WithMany("Samples")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CropQc.Data.Entities.SampleType", "SampleType")
                        .WithMany("Samples")
                        .HasForeignKey("SampleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CropQc.Data.Entities.User", "TakenByUser")
                        .WithMany("TakenSamples")
                        .HasForeignKey("TakenByUserId");

                    b.Navigation("QcStation");

                    b.Navigation("Receipt");

                    b.Navigation("SampleType");

                    b.Navigation("TakenByUser");
                });

            modelBuilder.Entity("CropQc.Data.Entities.QcStation", b =>
                {
                    b.HasOne("CropQc.Data.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("CropQc.Data.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("CropQc.Data.Entities.QcSummaryEmailLog", b =>
                {
                    b.HasOne("CropQc.Data.Entities.QcSample", "QcSample")
                        .WithMany()
                        .HasForeignKey("QcSampleId");

                    b.HasOne("CropQc.Data.Entities.Receipt", "Receipt")
                        .WithMany("SummaryEmailLogs")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CropQc.Data.Entities.User", "SentByUser")
                        .WithMany()
                        .HasForeignKey("SentByUserId");

                    b.Navigation("QcSample");

                    b.Navigation("Receipt");

                    b.Navigation("SentByUser");
                });

            modelBuilder.Entity("CropQc.Data.Entities.Receipt", b =>
                {
                    b.HasOne("CropQc.Data.Entities.FruitProfile", "FruitProfile")
                        .WithMany("Receipts")
                        .HasForeignKey("FruitProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CropQc.Data.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CropQc.Data.Entities.Warehouse", "Warehouse")
                        .WithMany("Receipts")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FruitProfile");

                    b.Navigation("Room");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("CropQc.Data.Entities.RolePermission", b =>
                {
                    b.HasOne("CropQc.Data.Entities.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CropQc.Data.Entities.Room", b =>
                {
                    b.HasOne("CropQc.Data.Entities.Warehouse", "Warehouse")
                        .WithMany("Rooms")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("CropQc.Data.Entities.StarchScale", b =>
                {
                    b.HasOne("CropQc.Data.Entities.FruitProfile", "FruitProfile")
                        .WithMany()
                        .HasForeignKey("FruitProfileId");

                    b.Navigation("FruitProfile");
                });

            modelBuilder.Entity("CropQc.Data.Entities.StarchScaleValue", b =>
                {
                    b.HasOne("CropQc.Data.Entities.StarchScale", "StarchScale")
                        .WithMany("Values")
                        .HasForeignKey("StarchScaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StarchScale");
                });

            modelBuilder.Entity("CropQc.Data.Entities.UserRole", b =>
                {
                    b.HasOne("CropQc.Data.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CropQc.Data.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CropQc.Data.Entities.FruitProfile", b =>
                {
                    b.Navigation("Receipts");
                });

            modelBuilder.Entity("CropQc.Data.Entities.QcFruitReading", b =>
                {
                    b.Navigation("Defects");
                });

            modelBuilder.Entity("CropQc.Data.Entities.QcSample", b =>
                {
                    b.Navigation("FruitReadings");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("CropQc.Data.Entities.QcStation", b =>
                {
                    b.Navigation("Samples");
                });

            modelBuilder.Entity("CropQc.Data.Entities.Receipt", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("Samples");

                    b.Navigation("SummaryEmailLogs");
                });

            modelBuilder.Entity("CropQc.Data.Entities.Role", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CropQc.Data.Entities.SampleType", b =>
                {
                    b.Navigation("Samples");
                });

            modelBuilder.Entity("CropQc.Data.Entities.StarchScale", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("CropQc.Data.Entities.User", b =>
                {
                    b.Navigation("TakenSamples");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CropQc.Data.Entities.Warehouse", b =>
                {
                    b.Navigation("Receipts");

                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
