-- Read-only integrity fingerprint query used before and after the investigation.
SELECT jsonb_build_object('observed_at',current_timestamp,
'Receipts',(SELECT jsonb_build_object('rows',count(*),'hash',md5(coalesce(string_agg(to_jsonb(t)::text,'' ORDER BY to_jsonb(t)::text),''))) FROM "Receipts" t),
'ReceiptVarietyLines',(SELECT jsonb_build_object('rows',count(*),'hash',md5(coalesce(string_agg(to_jsonb(t)::text,'' ORDER BY to_jsonb(t)::text),''))) FROM "ReceiptVarietyLines" t),
'RoomInventoryAdjustments',(SELECT jsonb_build_object('rows',count(*),'hash',md5(coalesce(string_agg(to_jsonb(t)::text,'' ORDER BY to_jsonb(t)::text),''))) FROM "RoomInventoryAdjustments" t),
'TreatmentLineageSegments',(SELECT jsonb_build_object('rows',count(*),'hash',md5(coalesce(string_agg(to_jsonb(t)::text,'' ORDER BY to_jsonb(t)::text),''))) FROM "TreatmentLineageSegments" t),
'TreatmentLineageMovements',(SELECT jsonb_build_object('rows',count(*),'hash',md5(coalesce(string_agg(to_jsonb(t)::text,'' ORDER BY to_jsonb(t)::text),''))) FROM "TreatmentLineageMovements" t),
'TreatmentLineageSegmentApplications',(SELECT jsonb_build_object('rows',count(*),'hash',md5(coalesce(string_agg(to_jsonb(t)::text,'' ORDER BY to_jsonb(t)::text),''))) FROM "TreatmentLineageSegmentApplications" t),
'RoomTreatmentApplications',(SELECT jsonb_build_object('rows',count(*),'hash',md5(coalesce(string_agg(to_jsonb(t)::text,'' ORDER BY to_jsonb(t)::text),''))) FROM "RoomTreatmentApplications" t),
'RoomTreatmentApplicationSources',(SELECT jsonb_build_object('rows',count(*),'hash',md5(coalesce(string_agg(to_jsonb(t)::text,'' ORDER BY to_jsonb(t)::text),''))) FROM "RoomTreatmentApplicationSources" t),
'InterCrewTransfers',(SELECT jsonb_build_object('rows',count(*),'hash',md5(coalesce(string_agg(to_jsonb(t)::text,'' ORDER BY to_jsonb(t)::text),''))) FROM "InterCrewTransfers" t),
'OutsideWarehouseTransfers',(SELECT jsonb_build_object('rows',count(*),'hash',md5(coalesce(string_agg(to_jsonb(t)::text,'' ORDER BY to_jsonb(t)::text),''))) FROM "OutsideWarehouseTransfers" t),
'RoomTransfers',(SELECT jsonb_build_object('rows',count(*),'hash',md5(coalesce(string_agg(to_jsonb(t)::text,'' ORDER BY to_jsonb(t)::text),''))) FROM "RoomTransfers" t),
'RoomInventoryLosses',(SELECT jsonb_build_object('rows',count(*),'hash',md5(coalesce(string_agg(to_jsonb(t)::text,'' ORDER BY to_jsonb(t)::text),''))) FROM "RoomInventoryLosses" t),
'ReceiptInventoryOverrides',(SELECT jsonb_build_object('rows',count(*),'hash',md5(coalesce(string_agg(to_jsonb(t)::text,'' ORDER BY to_jsonb(t)::text),''))) FROM "ReceiptInventoryOverrides" t),
'InventoryIdentityCorrections',(SELECT jsonb_build_object('rows',count(*),'hash',md5(coalesce(string_agg(to_jsonb(t)::text,'' ORDER BY to_jsonb(t)::text),''))) FROM "InventoryIdentityCorrections" t),
'InventoryCommands',(SELECT jsonb_build_object('rows',count(*),'hash',md5(coalesce(string_agg(to_jsonb(t)::text,'' ORDER BY to_jsonb(t)::text),''))) FROM "InventoryCommands" t),
'audits',(SELECT jsonb_build_object('max_id',max("Id"),'rows',count(*),'hash',md5(string_agg(to_jsonb(t)::text,'' ORDER BY "Id"))) FROM "AuditLogs" t),
'ledger_total',(SELECT sum("ChangeAmount") FROM "RoomInventoryAdjustments")) AS baseline;;

