SELECT jsonb_build_object('observed_at',now(),'read_only',current_setting('transaction_read_only'),
'Rooms',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM "Rooms" t),
'Warehouses',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM "Warehouses" t),
'Receipts',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM "Receipts" t),
'ReceiptInventoryOverrides',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM "ReceiptInventoryOverrides" t),
'InventoryIdentityCorrections',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM "InventoryIdentityCorrections" t),
'RoomInventoryAdjustments',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM "RoomInventoryAdjustments" t),
'RoomTransfers',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM "RoomTransfers" t),
'RoomInventoryLosses',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM "RoomInventoryLosses" t),
'InterCrewTransfers',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM "InterCrewTransfers" t),
'OutsideWarehouseTransfers',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM "OutsideWarehouseTransfers" t),
'TreatmentLineageSegments',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM "TreatmentLineageSegments" t),
'TreatmentLineageMovements',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM "TreatmentLineageMovements" t),
'TreatmentLineageSegmentApplications',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM "TreatmentLineageSegmentApplications" t),
'RoomTreatmentApplications',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM "RoomTreatmentApplications" t),
'RoomTreatmentApplicationSources',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM "RoomTreatmentApplicationSources" t),
'BinsRunEntries',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM "BinsRunEntries" t)) AS evidence;

