\set ON_ERROR_STOP on
\ir preflight-inventory-diagnostic-acknowledgments.sql

BEGIN;
SELECT pg_advisory_xact_lock(hashtextextended('CropQc:20260809151943_AddInventoryDiagnosticAcknowledgments', 0));

SELECT to_regclass(format('%I.%I',current_schema(),'InventoryDiagnosticAcknowledgments')) IS NULL AS create_target \gset
\if :create_target
CREATE TABLE "InventoryDiagnosticAcknowledgments" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "DiagnosticKey" character varying(64) NOT NULL,
    "DiagnosticType" character varying(100) NOT NULL,
    "DiagnosticCode" character varying(100) NOT NULL,
    "DiagnosticMessage" character varying(1000) NOT NULL,
    "RoomInventoryAdjustmentId" bigint NOT NULL,
    "InvariantVersion" integer NOT NULL,
    "Reason" character varying(500) NOT NULL,
    "DiagnosticSnapshotJson" character varying(4000) NOT NULL,
    "DismissedByUserId" integer NULL,
    "DismissedByEmail" character varying(320) NOT NULL,
    "DismissedAt" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "RestoredByUserId" integer NULL,
    "RestoredByEmail" character varying(320) NULL,
    "RestoredAt" timestamp with time zone NULL,
    CONSTRAINT "PK_InventoryDiagnosticAcknowledgments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InventoryDiagnosticAck_Adjustment" FOREIGN KEY ("RoomInventoryAdjustmentId") REFERENCES "RoomInventoryAdjustments" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_InventoryDiagnosticAck_DismissedBy" FOREIGN KEY ("DismissedByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_InventoryDiagnosticAck_RestoredBy" FOREIGN KEY ("RestoredByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
);

CREATE UNIQUE INDEX "IX_InventoryDiagnosticAck_Key"
    ON "InventoryDiagnosticAcknowledgments" ("DiagnosticKey");
CREATE INDEX "IX_InventoryDiagnosticAck_DismissedBy"
    ON "InventoryDiagnosticAcknowledgments" ("DismissedByUserId");
CREATE INDEX "IX_InventoryDiagnosticAck_ActiveAdjustment"
    ON "InventoryDiagnosticAcknowledgments" ("IsActive", "RoomInventoryAdjustmentId");
CREATE INDEX "IX_InventoryDiagnosticAck_RestoredBy"
    ON "InventoryDiagnosticAcknowledgments" ("RestoredByUserId");
CREATE INDEX "IX_InventoryDiagnosticAck_Adjustment"
    ON "InventoryDiagnosticAcknowledgments" ("RoomInventoryAdjustmentId");
\else
\echo 'InventoryDiagnosticAcknowledgments is already complete and exact; no DDL will be applied.'
\endif

DO $postcheck$
DECLARE
    target_oid oid := to_regclass(format('%I.%I',current_schema(),'InventoryDiagnosticAcknowledgments'));
BEGIN
    RAISE NOTICE 'Post-apply object counts: table_oid=% columns=% constraints=% indexes=%',
        target_oid,
        (SELECT count(*) FROM information_schema.columns WHERE table_schema=current_schema() AND table_name='InventoryDiagnosticAcknowledgments'),
        (SELECT count(*) FROM pg_constraint WHERE conrelid=target_oid AND contype IN ('p','f','u','c','x')),
        (SELECT count(*) FROM pg_index WHERE indrelid=target_oid);
    IF target_oid IS NULL
       OR (SELECT count(*) FROM information_schema.columns WHERE table_schema=current_schema() AND table_name='InventoryDiagnosticAcknowledgments') <> 16
       OR (SELECT count(*) FROM pg_constraint WHERE conrelid=target_oid AND contype IN ('p','f','u','c','x')) <> 4
       OR (SELECT count(*) FROM pg_index WHERE indrelid=target_oid) <> 6 THEN
        RAISE EXCEPTION 'Post-apply object counts are incomplete; transaction will roll back.';
    END IF;
    IF current_setting('cropqc.test_force_inventory_diagnostic_ack_failure', true) = 'on' THEN
        RAISE EXCEPTION 'Forced compatibility-apply failure for rollback regression testing.';
    END IF;
END $postcheck$;

COMMIT;

-- The independent verifier repeats the complete shape check after commit.
\ir verify-inventory-diagnostic-acknowledgments.sql
