\set ON_ERROR_STOP on

-- Transactional, idempotent, additive PostgreSQL compatibility update for
-- 20260730150926_EnforceRoomInventoryDeductionParents.
-- It preserves all historical inventory rows and does not update migration history.
begin;
set local lock_timeout = '15s';
set local statement_timeout = '10min';
select pg_advisory_xact_lock(hashtextextended(
    'CropQc:20260730150926_EnforceRoomInventoryDeductionParents', 0));

do $precheck$
declare
    duplicate_count bigint;
begin
    if to_regclass(format('%I.%I', current_schema(), 'RoomInventoryAdjustments')) is null
       or to_regclass(format('%I.%I', current_schema(), 'BinsRunEntries')) is null then
        raise exception 'Required room inventory tables are missing; transaction rolled back.';
    end if;
    select count(*) into duplicate_count
    from (
        select "InventoryAdjustmentId"
        from "BinsRunEntries"
        group by "InventoryAdjustmentId"
        having count(*) > 1
    ) duplicates;
    if duplicate_count > 0 then
        raise exception '% duplicate Bins Run parent relationship(s) require review; transaction rolled back.', duplicate_count;
    end if;
end
$precheck$;

create table if not exists "RoomTransfers" (
    "Id" bigint generated by default as identity primary key,
    "OperationKey" character varying(150) not null,
    "SourceWarehouseId" integer not null references "Warehouses" ("Id") on delete restrict,
    "SourceRoomId" integer not null references "Rooms" ("Id") on delete restrict,
    "DestinationWarehouseId" integer not null references "Warehouses" ("Id") on delete restrict,
    "DestinationRoomId" integer not null references "Rooms" ("Id") on delete restrict,
    "CropYear" integer null,
    "GrowerLotId" integer null,
    "FruitProfileId" integer null references "FruitProfiles" ("Id") on delete set null,
    "GrowerName" character varying(200) not null,
    "LotNumber" character varying(100) not null,
    "PoolStart" character varying(20) null,
    "VarietyCode" character varying(50) null,
    "InventoryStatus" character varying(100) null,
    "BinCount" integer not null,
    "Reason" character varying(500) not null,
    "Notes" character varying(1000) null,
    "TransferredAt" timestamp with time zone not null,
    "CreatedByUserId" integer null references "Users" ("Id") on delete set null,
    "CreatedAt" timestamp with time zone not null,
    "IsReversed" boolean not null default false,
    "ReversedAt" timestamp with time zone null,
    "ReversedByUserId" integer null,
    "ReverseReason" character varying(1000) null,
    "ReversesRoomTransferId" bigint null
);

alter table "RoomTransfers"
    add column if not exists "IsReversed" boolean not null default false,
    add column if not exists "ReversedAt" timestamp with time zone null,
    add column if not exists "ReversedByUserId" integer null,
    add column if not exists "ReverseReason" character varying(1000) null,
    add column if not exists "ReversesRoomTransferId" bigint null;

alter table "RoomInventoryAdjustments"
    add column if not exists "InventoryInvariantVersion" integer not null default 0,
    add column if not exists "InventoryOperationKey" character varying(200) null,
    add column if not exists "RoomTransferId" bigint null;

do $constraint$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'FK_RoomInventoryAdjustments_RoomTransfers_RoomTransferId'
          and conrelid = '"RoomInventoryAdjustments"'::regclass
    ) then
        alter table "RoomInventoryAdjustments"
            add constraint "FK_RoomInventoryAdjustments_RoomTransfers_RoomTransferId"
            foreign key ("RoomTransferId") references "RoomTransfers" ("Id") on delete restrict;
    end if;
    if not exists (
        select 1 from pg_constraint
        where conname = 'FK_RoomTransfers_Users_ReversedByUserId'
          and conrelid = '"RoomTransfers"'::regclass
    ) then
        alter table "RoomTransfers"
            add constraint "FK_RoomTransfers_Users_ReversedByUserId"
            foreign key ("ReversedByUserId") references "Users" ("Id") on delete set null;
    end if;
    if not exists (
        select 1 from pg_constraint
        where conname = 'FK_RoomTransfers_RoomTransfers_ReversesRoomTransferId'
          and conrelid = '"RoomTransfers"'::regclass
    ) then
        alter table "RoomTransfers"
            add constraint "FK_RoomTransfers_RoomTransfers_ReversesRoomTransferId"
            foreign key ("ReversesRoomTransferId") references "RoomTransfers" ("Id") on delete restrict;
    end if;
end
$constraint$;

create unique index if not exists "UX_BinsRunEntries_InventoryAdjustmentId_Invariant"
    on "BinsRunEntries" ("InventoryAdjustmentId");
create unique index if not exists "IX_RoomInventoryAdjustments_InventoryOperationKey"
    on "RoomInventoryAdjustments" ("InventoryOperationKey")
    where "InventoryOperationKey" is not null;
create unique index if not exists "IX_RoomInventoryAdjustments_RoomTransferId_AdjustmentType"
    on "RoomInventoryAdjustments" ("RoomTransferId", "AdjustmentType")
    where "RoomTransferId" is not null;
create unique index if not exists "IX_RoomTransfers_OperationKey" on "RoomTransfers" ("OperationKey");
create index if not exists "IX_RoomTransfers_ReversedByUserId" on "RoomTransfers" ("ReversedByUserId");
create unique index if not exists "IX_RoomTransfers_ReversesRoomTransferId"
    on "RoomTransfers" ("ReversesRoomTransferId")
    where "ReversesRoomTransferId" is not null;
create index if not exists "IX_RoomTransfers_SourceRoomId_TransferredAt" on "RoomTransfers" ("SourceRoomId", "TransferredAt");
create index if not exists "IX_RoomTransfers_DestinationRoomId_TransferredAt" on "RoomTransfers" ("DestinationRoomId", "TransferredAt");
create index if not exists "IX_RoomTransfers_SourceWarehouseId" on "RoomTransfers" ("SourceWarehouseId");
create index if not exists "IX_RoomTransfers_DestinationWarehouseId" on "RoomTransfers" ("DestinationWarehouseId");
create index if not exists "IX_RoomTransfers_FruitProfileId" on "RoomTransfers" ("FruitProfileId");
create index if not exists "IX_RoomTransfers_GrowerLotId" on "RoomTransfers" ("GrowerLotId");
create index if not exists "IX_RoomTransfers_CreatedByUserId" on "RoomTransfers" ("CreatedByUserId");

commit;
