-- Bounded additive compatibility package for 20260906025535_AddHarvestWatchDeployments.
BEGIN;
SELECT pg_advisory_xact_lock(hashtextextended('CropQc:20260906025535_AddHarvestWatchDeployments', 0));
CREATE TABLE "HarvestWatchDeployments" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY, "RoomId" integer NOT NULL, "WarehouseId" integer NOT NULL,
    "HarvestWatchCode" character varying(5) NOT NULL, "Status" character varying(40) NOT NULL, "IsActive" boolean NOT NULL,
    "DeployedAt" timestamp with time zone NOT NULL, "DeployedByUserId" integer NOT NULL, "DeployerEmailSnapshot" character varying(320) NOT NULL,
    "WarehouseCodeSnapshot" character varying(25) NOT NULL, "RoomCodeSnapshot" character varying(150) NOT NULL, "VarietySnapshot" character varying(1000) NOT NULL,
    "CorrelationToken" character varying(64) NOT NULL, "VerificationEmailSentAt" timestamp with time zone NULL, "VerificationEmailMessageId" character varying(255) NULL,
    "VerificationEmailError" character varying(1000) NULL, "VerifiedAt" timestamp with time zone NULL, "VerifiedByEmail" character varying(320) NULL,
    "LastReplyMessageId" character varying(255) NULL, "ErrorNotificationSentAt" timestamp with time zone NULL, "ErrorNotificationMessageId" character varying(255) NULL,
    "RemovedAt" timestamp with time zone NULL, "RemovedByUserId" integer NULL, "CreatedAt" timestamp with time zone NOT NULL, "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_HarvestWatchDeployments" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_HarvestWatchDeployments_Code" CHECK ("HarvestWatchCode" ~ '^[0-9]{5}$'),
    CONSTRAINT "FK_HarvestWatchDeployments_Rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES "Rooms"("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_HarvestWatchDeployments_Warehouses_WarehouseId" FOREIGN KEY ("WarehouseId") REFERENCES "Warehouses"("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_HarvestWatchDeployments_Users_DeployedByUserId" FOREIGN KEY ("DeployedByUserId") REFERENCES "Users"("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_HarvestWatchDeployments_Users_RemovedByUserId" FOREIGN KEY ("RemovedByUserId") REFERENCES "Users"("Id") ON DELETE RESTRICT
);
CREATE TABLE "HarvestWatchStatusHistories" ("Id" bigint GENERATED BY DEFAULT AS IDENTITY, "HarvestWatchDeploymentId" bigint NOT NULL, "PreviousStatus" character varying(40) NULL, "NewStatus" character varying(40) NOT NULL, "Source" character varying(40) NOT NULL, "ChangedAt" timestamp with time zone NOT NULL, "InboundMessageId" character varying(255) NULL, "ChangedByEmail" character varying(320) NULL, "Note" character varying(1000) NULL, CONSTRAINT "PK_HarvestWatchStatusHistories" PRIMARY KEY ("Id"), CONSTRAINT "FK_HarvestWatchStatusHistories_HarvestWatchDeployments_HarvestWatchDeploymentId" FOREIGN KEY ("HarvestWatchDeploymentId") REFERENCES "HarvestWatchDeployments"("Id") ON DELETE CASCADE);
CREATE TABLE "HarvestWatchInboundMessages" ("Id" bigint GENERATED BY DEFAULT AS IDENTITY, "GmailMessageId" character varying(255) NOT NULL, "HarvestWatchDeploymentId" bigint NULL, "SenderEmail" character varying(320) NOT NULL, "Subject" character varying(1000) NOT NULL, "BodyExcerpt" character varying(4000) NOT NULL, "ReceivedAt" timestamp with time zone NOT NULL, "Outcome" character varying(100) NOT NULL, "ProcessedAt" timestamp with time zone NOT NULL, CONSTRAINT "PK_HarvestWatchInboundMessages" PRIMARY KEY ("Id"), CONSTRAINT "FK_HarvestWatchInboundMessages_HarvestWatchDeployments_HarvestWatchDeploymentId" FOREIGN KEY ("HarvestWatchDeploymentId") REFERENCES "HarvestWatchDeployments"("Id") ON DELETE SET NULL);
CREATE TABLE "HarvestWatchMailboxCursors" ("Id" integer GENERATED BY DEFAULT AS IDENTITY, "LastPolledAt" timestamp with time zone NULL, "UpdatedAt" timestamp with time zone NOT NULL, CONSTRAINT "PK_HarvestWatchMailboxCursors" PRIMARY KEY ("Id"));
CREATE UNIQUE INDEX "IX_HarvestWatchDeployments_CorrelationToken" ON "HarvestWatchDeployments"("CorrelationToken");
CREATE INDEX "IX_HarvestWatchDeployments_DeployedByUserId" ON "HarvestWatchDeployments"("DeployedByUserId");
CREATE UNIQUE INDEX "IX_HarvestWatchDeployments_HarvestWatchCode_IsActive" ON "HarvestWatchDeployments"("HarvestWatchCode","IsActive") WHERE "IsActive" = TRUE;
CREATE INDEX "IX_HarvestWatchDeployments_RemovedByUserId" ON "HarvestWatchDeployments"("RemovedByUserId");
CREATE INDEX "IX_HarvestWatchDeployments_RoomId_IsActive" ON "HarvestWatchDeployments"("RoomId","IsActive");
CREATE INDEX "IX_HarvestWatchDeployments_WarehouseId" ON "HarvestWatchDeployments"("WarehouseId");
CREATE UNIQUE INDEX "IX_HarvestWatchInboundMessages_GmailMessageId" ON "HarvestWatchInboundMessages"("GmailMessageId");
CREATE INDEX "IX_HarvestWatchInboundMessages_HarvestWatchDeploymentId" ON "HarvestWatchInboundMessages"("HarvestWatchDeploymentId");
CREATE INDEX "IX_HarvestWatchStatusHistories_HarvestWatchDeploymentId_ChangedAt" ON "HarvestWatchStatusHistories"("HarvestWatchDeploymentId","ChangedAt");
COMMIT;
