START TRANSACTION;

\set ON_ERROR_STOP on
set local lock_timeout = '15s';
set local statement_timeout = '10min';
select pg_advisory_xact_lock(hashtextextended(
    'CropQc:20260731014107_SeparatePlanningProjectionsFromActualRuns', 0));

DO $PRECHECK$
DECLARE
    missing_base text;
    migration_recorded boolean;
    target_objects_complete boolean;
BEGIN
    SELECT string_agg(expected.name, ', ' ORDER BY expected.name)
    INTO missing_base
    FROM (VALUES
        ('ActualRuns'),
        ('ActualRunRevisions'),
        ('BinsRunEntries'),
        ('PackoutRuns'),
        ('QcSamples'),
        ('Users')
    ) expected(name)
    WHERE to_regclass(format('%I.%I', current_schema(), expected.name)) IS NULL;

    IF missing_base IS NOT NULL THEN
        RAISE EXCEPTION 'Required pre-existing table(s) are missing: %. Transaction rolled back.', missing_base;
    END IF;

    SELECT EXISTS (
        SELECT 1 FROM "__EFMigrationsHistory"
        WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns'
    ) INTO migration_recorded;

    SELECT to_regclass(format('%I.%I', current_schema(), 'RunExpectations')) IS NOT NULL
       AND to_regclass(format('%I.%I', current_schema(), 'RunExpectationSources')) IS NOT NULL
       AND to_regclass(format('%I.%I', current_schema(), 'PackoutSourceAllocations')) IS NOT NULL
       AND EXISTS (
           SELECT 1 FROM information_schema.columns
           WHERE table_schema = current_schema()
             AND table_name = 'PackoutRuns'
             AND column_name = 'ActualRunId')
       AND EXISTS (
           SELECT 1 FROM information_schema.columns
           WHERE table_schema = current_schema()
             AND table_name = 'PackoutRuns'
             AND column_name = 'RunExpectationId')
    INTO target_objects_complete;

    IF migration_recorded AND NOT target_objects_complete THEN
        RAISE EXCEPTION 'EF migration history records the target migration but required objects are missing. Manual review is required; transaction rolled back.';
    END IF;
END $PRECHECK$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    ALTER TABLE "PackoutRuns" ALTER COLUMN "RunProjectionId" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    ALTER TABLE "PackoutRuns" ADD COLUMN IF NOT EXISTS "ActualRunId" bigint;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    ALTER TABLE "PackoutRuns" ADD COLUMN IF NOT EXISTS "RunExpectationId" bigint;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE TABLE IF NOT EXISTS "RunExpectations" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ActualRunId" bigint NOT NULL,
        "ActualRunRevisionId" bigint NOT NULL,
        "RevisionNumber" integer NOT NULL,
        "FacilityWarehouseId" integer NOT NULL,
        "FacilitySnapshot" character varying(50) NOT NULL,
        "RunAtSnapshot" timestamp with time zone NOT NULL,
        "TotalBins" integer NOT NULL,
        "GrossPounds" numeric(18,4) NOT NULL,
        "ExpectedPackoutPercent" numeric(8,4) NOT NULL,
        "ExpectedPackedPounds" numeric(18,4) NOT NULL,
        "ExpectedPackedBoxes" numeric(18,4) NOT NULL,
        "ExpectedWholeBoxes" integer NOT NULL,
        "ExpectedCullPounds" numeric(18,4) NOT NULL,
        "ExpectedJuicePounds" numeric(18,4) NOT NULL,
        "ExpectedPeelerPounds" numeric(18,4) NOT NULL,
        "ExpectedWastePounds" numeric(18,4) NOT NULL,
        "ConfidencePercent" numeric(8,4) NOT NULL,
        "SizeDistributionSnapshotJson" text NOT NULL,
        "GradeDistributionSnapshotJson" text NOT NULL,
        "ConfigurationSnapshotJson" text NOT NULL,
        "CalculationVersion" character varying(75) NOT NULL,
        "CalculatedAt" timestamp with time zone NOT NULL,
        "CreatedByUserId" integer,
        CONSTRAINT "PK_RunExpectations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RunExpectations_ActualRunRevisions_ActualRunRevisionId" FOREIGN KEY ("ActualRunRevisionId") REFERENCES "ActualRunRevisions" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_RunExpectations_ActualRuns_ActualRunId" FOREIGN KEY ("ActualRunId") REFERENCES "ActualRuns" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_RunExpectations_Users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE TABLE IF NOT EXISTS "RunExpectationSources" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "RunExpectationId" bigint NOT NULL,
        "BinsRunEntryId" bigint NOT NULL,
        "WarehouseId" integer NOT NULL,
        "RoomId" integer NOT NULL,
        "FacilitySnapshot" character varying(50) NOT NULL,
        "RoomSnapshot" character varying(100) NOT NULL,
        "CropYearSnapshot" integer,
        "GrowerLotId" integer,
        "FruitProfileId" integer,
        "GrowerSnapshot" character varying(200) NOT NULL,
        "LotSnapshot" character varying(100) NOT NULL,
        "VarietySnapshot" character varying(100) NOT NULL,
        "ProductionTypeSnapshot" character varying(50) NOT NULL,
        "IsOrganicSnapshot" boolean NOT NULL,
        "BinsContributed" integer NOT NULL,
        "ContributionPercent" numeric(9,6) NOT NULL,
        "QcSampleId" bigint,
        "QcSampleTakenAtSnapshot" timestamp with time zone,
        "QcFruitCountSnapshot" integer NOT NULL,
        "QcMeasurementSnapshotJson" text NOT NULL,
        "SizeDistributionSnapshotJson" text NOT NULL,
        "GradeDistributionSnapshotJson" text NOT NULL,
        "GrossPounds" numeric(18,4) NOT NULL,
        "ExpectedPackedPounds" numeric(18,4) NOT NULL,
        "ExpectedWholeBoxes" integer NOT NULL,
        "ExpectedCullPounds" numeric(18,4) NOT NULL,
        "ConfidencePercent" numeric(8,4) NOT NULL,
        "WarningSnapshot" character varying(1000),
        CONSTRAINT "PK_RunExpectationSources" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RunExpectationSources_BinsRunEntries_BinsRunEntryId" FOREIGN KEY ("BinsRunEntryId") REFERENCES "BinsRunEntries" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_RunExpectationSources_QcSamples_QcSampleId" FOREIGN KEY ("QcSampleId") REFERENCES "QcSamples" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_RunExpectationSources_RunExpectations_RunExpectationId" FOREIGN KEY ("RunExpectationId") REFERENCES "RunExpectations" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE TABLE IF NOT EXISTS "PackoutSourceAllocations" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "PackoutRunId" bigint NOT NULL,
        "RunExpectationSourceId" bigint NOT NULL,
        "BinsContributed" integer NOT NULL,
        "ContributionPercent" numeric(9,6) NOT NULL,
        "AllocatedPackedPounds" numeric(18,6) NOT NULL,
        "AllocatedWholeBoxes" integer NOT NULL,
        "AllocatedResidualPounds" numeric(18,6) NOT NULL,
        "AllocatedJuicePounds" numeric(18,6) NOT NULL,
        "AllocatedPeelerPounds" numeric(18,6) NOT NULL,
        "AllocatedWastePounds" numeric(18,6) NOT NULL,
        "PackCodeAllocationJson" text NOT NULL,
        "SizeAllocationJson" text NOT NULL,
        "GradeAllocationJson" text NOT NULL,
        "AllocationVersion" character varying(75) NOT NULL,
        "CalculatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_PackoutSourceAllocations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PackoutSourceAllocations_PackoutRuns_PackoutRunId" FOREIGN KEY ("PackoutRunId") REFERENCES "PackoutRuns" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_PackoutSourceAllocations_RunExpectationSources_RunExpectationSourceId" FOREIGN KEY ("RunExpectationSourceId") REFERENCES "RunExpectationSources" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE INDEX IF NOT EXISTS "IX_PackoutRuns_RunExpectationId" ON "PackoutRuns" ("RunExpectationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE UNIQUE INDEX IF NOT EXISTS "UX_PackoutRuns_ActualRunId" ON "PackoutRuns" ("ActualRunId") WHERE "ActualRunId" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE UNIQUE INDEX IF NOT EXISTS "IX_PackoutSourceAllocations_PackoutRunId_RunExpectationSourceId" ON "PackoutSourceAllocations" ("PackoutRunId", "RunExpectationSourceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE INDEX IF NOT EXISTS "IX_PackoutSourceAllocations_RunExpectationSourceId" ON "PackoutSourceAllocations" ("RunExpectationSourceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE UNIQUE INDEX IF NOT EXISTS "IX_RunExpectations_ActualRunId_RevisionNumber" ON "RunExpectations" ("ActualRunId", "RevisionNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE UNIQUE INDEX IF NOT EXISTS "IX_RunExpectations_ActualRunRevisionId" ON "RunExpectations" ("ActualRunRevisionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE INDEX IF NOT EXISTS "IX_RunExpectations_CreatedByUserId" ON "RunExpectations" ("CreatedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE INDEX IF NOT EXISTS "IX_RunExpectationSources_BinsRunEntryId" ON "RunExpectationSources" ("BinsRunEntryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE INDEX IF NOT EXISTS "IX_RunExpectationSources_QcSampleId" ON "RunExpectationSources" ("QcSampleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE UNIQUE INDEX IF NOT EXISTS "IX_RunExpectationSources_RunExpectationId_BinsRunEntryId" ON "RunExpectationSources" ("RunExpectationId", "BinsRunEntryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE INDEX IF NOT EXISTS "IX_RunExpectationSources_WarehouseId_RoomId_CropYearSnapshot_LotSnapshot_VarietySnapshot" ON "RunExpectationSources" ("WarehouseId", "RoomId", "CropYearSnapshot", "LotSnapshot", "VarietySnapshot");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'FK_PackoutRuns_ActualRuns_ActualRunId'
          AND conrelid = '"PackoutRuns"'::regclass
    ) THEN
        ALTER TABLE "PackoutRuns" ADD CONSTRAINT "FK_PackoutRuns_ActualRuns_ActualRunId" FOREIGN KEY ("ActualRunId") REFERENCES "ActualRuns" ("Id") ON DELETE RESTRICT;
    END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'FK_PackoutRuns_RunExpectations_RunExpectationId'
          AND conrelid = '"PackoutRuns"'::regclass
    ) THEN
        ALTER TABLE "PackoutRuns" ADD CONSTRAINT "FK_PackoutRuns_RunExpectations_RunExpectationId" FOREIGN KEY ("RunExpectationId") REFERENCES "RunExpectations" ("Id") ON DELETE RESTRICT;
    END IF;
    END IF;
END $EF$;

DO $RELATIONSHIPS$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_PackoutRuns_ActualRuns_ActualRunId' AND conrelid = '"PackoutRuns"'::regclass) THEN
        ALTER TABLE "PackoutRuns" ADD CONSTRAINT "FK_PackoutRuns_ActualRuns_ActualRunId" FOREIGN KEY ("ActualRunId") REFERENCES "ActualRuns" ("Id") ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_PackoutRuns_RunExpectations_RunExpectationId' AND conrelid = '"PackoutRuns"'::regclass) THEN
        ALTER TABLE "PackoutRuns" ADD CONSTRAINT "FK_PackoutRuns_RunExpectations_RunExpectationId" FOREIGN KEY ("RunExpectationId") REFERENCES "RunExpectations" ("Id") ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_RunExpectations_ActualRunRevisions_ActualRunRevisionId' AND conrelid = '"RunExpectations"'::regclass) THEN
        ALTER TABLE "RunExpectations" ADD CONSTRAINT "FK_RunExpectations_ActualRunRevisions_ActualRunRevisionId" FOREIGN KEY ("ActualRunRevisionId") REFERENCES "ActualRunRevisions" ("Id") ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_RunExpectations_ActualRuns_ActualRunId' AND conrelid = '"RunExpectations"'::regclass) THEN
        ALTER TABLE "RunExpectations" ADD CONSTRAINT "FK_RunExpectations_ActualRuns_ActualRunId" FOREIGN KEY ("ActualRunId") REFERENCES "ActualRuns" ("Id") ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_RunExpectations_Users_CreatedByUserId' AND conrelid = '"RunExpectations"'::regclass) THEN
        ALTER TABLE "RunExpectations" ADD CONSTRAINT "FK_RunExpectations_Users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_RunExpectationSources_BinsRunEntries_BinsRunEntryId' AND conrelid = '"RunExpectationSources"'::regclass) THEN
        ALTER TABLE "RunExpectationSources" ADD CONSTRAINT "FK_RunExpectationSources_BinsRunEntries_BinsRunEntryId" FOREIGN KEY ("BinsRunEntryId") REFERENCES "BinsRunEntries" ("Id") ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_RunExpectationSources_QcSamples_QcSampleId' AND conrelid = '"RunExpectationSources"'::regclass) THEN
        ALTER TABLE "RunExpectationSources" ADD CONSTRAINT "FK_RunExpectationSources_QcSamples_QcSampleId" FOREIGN KEY ("QcSampleId") REFERENCES "QcSamples" ("Id") ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_RunExpectationSources_RunExpectations_RunExpectationId' AND conrelid = '"RunExpectationSources"'::regclass) THEN
        ALTER TABLE "RunExpectationSources" ADD CONSTRAINT "FK_RunExpectationSources_RunExpectations_RunExpectationId" FOREIGN KEY ("RunExpectationId") REFERENCES "RunExpectations" ("Id") ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_PackoutSourceAllocations_PackoutRuns_PackoutRunId' AND conrelid = '"PackoutSourceAllocations"'::regclass) THEN
        ALTER TABLE "PackoutSourceAllocations" ADD CONSTRAINT "FK_PackoutSourceAllocations_PackoutRuns_PackoutRunId" FOREIGN KEY ("PackoutRunId") REFERENCES "PackoutRuns" ("Id") ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = left('FK_PackoutSourceAllocations_RunExpectationSources_RunExpectationSourceId', 63) AND conrelid = '"PackoutSourceAllocations"'::regclass) THEN
        ALTER TABLE "PackoutSourceAllocations" ADD CONSTRAINT "FK_PackoutSourceAllocations_RunExpectationSources_RunExpectationSourceId" FOREIGN KEY ("RunExpectationSourceId") REFERENCES "RunExpectationSources" ("Id") ON DELETE RESTRICT;
    END IF;
END $RELATIONSHIPS$;

CREATE INDEX IF NOT EXISTS "IX_PackoutRuns_RunExpectationId" ON "PackoutRuns" ("RunExpectationId");
CREATE UNIQUE INDEX IF NOT EXISTS "UX_PackoutRuns_ActualRunId" ON "PackoutRuns" ("ActualRunId") WHERE "ActualRunId" IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "IX_PackoutSourceAllocations_PackoutRunId_RunExpectationSourceId" ON "PackoutSourceAllocations" ("PackoutRunId", "RunExpectationSourceId");
CREATE INDEX IF NOT EXISTS "IX_PackoutSourceAllocations_RunExpectationSourceId" ON "PackoutSourceAllocations" ("RunExpectationSourceId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_RunExpectations_ActualRunId_RevisionNumber" ON "RunExpectations" ("ActualRunId", "RevisionNumber");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_RunExpectations_ActualRunRevisionId" ON "RunExpectations" ("ActualRunRevisionId");
CREATE INDEX IF NOT EXISTS "IX_RunExpectations_CreatedByUserId" ON "RunExpectations" ("CreatedByUserId");
CREATE INDEX IF NOT EXISTS "IX_RunExpectationSources_BinsRunEntryId" ON "RunExpectationSources" ("BinsRunEntryId");
CREATE INDEX IF NOT EXISTS "IX_RunExpectationSources_QcSampleId" ON "RunExpectationSources" ("QcSampleId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_RunExpectationSources_RunExpectationId_BinsRunEntryId" ON "RunExpectationSources" ("RunExpectationId", "BinsRunEntryId");
CREATE INDEX IF NOT EXISTS "IX_RunExpectationSources_WarehouseId_RoomId_CropYearSnapshot_LotSnapshot_VarietySnapshot" ON "RunExpectationSources" ("WarehouseId", "RoomId", "CropYearSnapshot", "LotSnapshot", "VarietySnapshot");

DO $POSTCHECK$
DECLARE
    missing text;
BEGIN
    SELECT string_agg(expected.display_name, ', ' ORDER BY expected.display_name)
    INTO missing
    FROM (VALUES
        ('RunExpectations table', 'RunExpectations', NULL::text, false),
        ('RunExpectationSources table', 'RunExpectationSources', NULL::text, false),
        ('PackoutSourceAllocations table', 'PackoutSourceAllocations', NULL::text, false),
        ('PackoutRuns.ActualRunId', 'PackoutRuns', 'ActualRunId', false),
        ('PackoutRuns.RunExpectationId', 'PackoutRuns', 'RunExpectationId', false),
        ('PackoutRuns.RunProjectionId nullable', 'PackoutRuns', 'RunProjectionId', true)
    ) expected(display_name, table_name, column_name, require_nullable)
    WHERE (expected.column_name IS NULL
           AND to_regclass(format('%I.%I', current_schema(), expected.table_name)) IS NULL)
       OR (expected.column_name IS NOT NULL
           AND NOT EXISTS (
               SELECT 1 FROM information_schema.columns
               WHERE table_schema = current_schema()
                 AND table_name = expected.table_name
                 AND column_name = expected.column_name
                 AND (NOT expected.require_nullable OR is_nullable = 'YES')));

    IF missing IS NOT NULL THEN
        RAISE EXCEPTION 'Compatibility apply did not produce required object(s): %. Transaction rolled back.', missing;
    END IF;
END $POSTCHECK$;

DO $POSTCHECK_NAMED_OBJECTS$
DECLARE
    missing_indexes text;
    missing_constraints text;
BEGIN
    SELECT string_agg(expected.index_name, ', ' ORDER BY expected.index_name)
    INTO missing_indexes
    FROM (VALUES
        ('PackoutRuns', 'IX_PackoutRuns_RunExpectationId'),
        ('PackoutRuns', 'UX_PackoutRuns_ActualRunId'),
        ('PackoutSourceAllocations', 'IX_PackoutSourceAllocations_PackoutRunId_RunExpectationSourceId'),
        ('PackoutSourceAllocations', 'IX_PackoutSourceAllocations_RunExpectationSourceId'),
        ('RunExpectations', 'IX_RunExpectations_ActualRunId_RevisionNumber'),
        ('RunExpectations', 'IX_RunExpectations_ActualRunRevisionId'),
        ('RunExpectations', 'IX_RunExpectations_CreatedByUserId'),
        ('RunExpectationSources', 'IX_RunExpectationSources_BinsRunEntryId'),
        ('RunExpectationSources', 'IX_RunExpectationSources_QcSampleId'),
        ('RunExpectationSources', 'IX_RunExpectationSources_RunExpectationId_BinsRunEntryId'),
        ('RunExpectationSources', 'IX_RunExpectationSources_WarehouseId_RoomId_CropYearSnapshot_LotSnapshot_VarietySnapshot')
    ) expected(table_name, index_name)
    WHERE NOT EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = current_schema()
          AND tablename = expected.table_name
          AND indexname = left(expected.index_name, 63));

    SELECT string_agg(expected.constraint_name, ', ' ORDER BY expected.constraint_name)
    INTO missing_constraints
    FROM (VALUES
        ('PackoutRuns', 'FK_PackoutRuns_ActualRuns_ActualRunId'),
        ('PackoutRuns', 'FK_PackoutRuns_RunExpectations_RunExpectationId'),
        ('PackoutSourceAllocations', 'FK_PackoutSourceAllocations_PackoutRuns_PackoutRunId'),
        ('PackoutSourceAllocations', 'FK_PackoutSourceAllocations_RunExpectationSources_RunExpectationSourceId'),
        ('RunExpectations', 'FK_RunExpectations_ActualRunRevisions_ActualRunRevisionId'),
        ('RunExpectations', 'FK_RunExpectations_ActualRuns_ActualRunId'),
        ('RunExpectations', 'FK_RunExpectations_Users_CreatedByUserId'),
        ('RunExpectationSources', 'FK_RunExpectationSources_BinsRunEntries_BinsRunEntryId'),
        ('RunExpectationSources', 'FK_RunExpectationSources_QcSamples_QcSampleId'),
        ('RunExpectationSources', 'FK_RunExpectationSources_RunExpectations_RunExpectationId')
    ) expected(table_name, constraint_name)
    WHERE NOT EXISTS (
        SELECT 1
        FROM pg_constraint constraint_row
        JOIN pg_class table_row ON table_row.oid = constraint_row.conrelid
        JOIN pg_namespace namespace_row ON namespace_row.oid = table_row.relnamespace
        WHERE namespace_row.nspname = current_schema()
          AND table_row.relname = expected.table_name
          AND constraint_row.conname = left(expected.constraint_name, 63)
          AND constraint_row.contype = 'f');

    IF missing_indexes IS NOT NULL OR missing_constraints IS NOT NULL THEN
        RAISE EXCEPTION
            'Compatibility apply did not produce required indexes (%) or foreign keys (%). Transaction rolled back.',
            coalesce(missing_indexes, 'none'),
            coalesce(missing_constraints, 'none');
    END IF;
END $POSTCHECK_NAMED_OBJECTS$;

COMMIT;
