\set ON_ERROR_STOP on
\ir preflight-actual-run-sales-desk-attribution.sql

BEGIN;
SET LOCAL lock_timeout='15s';
SET LOCAL statement_timeout='10min';
SELECT pg_advisory_xact_lock(hashtextextended('CropQc:20260823040226_AddActualRunSalesDeskAttribution',0));
SELECT to_regclass(format('%I.%I',current_schema(),'SalesDesks')) IS NULL AS create_target \gset
\if :create_target
CREATE TABLE "SalesDesks" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "IsActive" boolean NOT NULL,
    "DisplayOrder" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedByUserId" integer,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedByUserId" integer,
    CONSTRAINT "PK_SalesDesks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SalesDesks_Users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users"("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_SalesDesks_Users_UpdatedByUserId" FOREIGN KEY ("UpdatedByUserId") REFERENCES "Users"("Id") ON DELETE SET NULL
);
ALTER TABLE "ActualRuns" ADD COLUMN "SalesDeskId" integer;
ALTER TABLE "ActualRuns" ADD COLUMN "SalesDeskNameSnapshot" character varying(100);
ALTER TABLE "ActualRunOverrideRequests" ADD COLUMN "SalesDeskId" integer;
ALTER TABLE "ActualRunOverrideRequests" ADD COLUMN "SalesDeskNameSnapshot" character varying(100);
CREATE TABLE "ActualRunSalesDeskCorrections" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ActualRunId" bigint NOT NULL,
    "OperationKey" character varying(64) NOT NULL,
    "ExpectedConcurrencyVersion" bigint NOT NULL,
    "PreviousSalesDeskId" integer,
    "PreviousSalesDeskNameSnapshot" character varying(100),
    "NewSalesDeskId" integer NOT NULL,
    "NewSalesDeskNameSnapshot" character varying(100) NOT NULL,
    "Reason" character varying(1000) NOT NULL,
    "CorrectedByUserId" integer NOT NULL,
    "CorrectedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ActualRunSalesDeskCorrections" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ActualRunSalesDeskCorrections_ActualRuns_ActualRunId" FOREIGN KEY ("ActualRunId") REFERENCES "ActualRuns"("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ActualRunSalesDeskCorrections_SalesDesks_NewSalesDeskId" FOREIGN KEY ("NewSalesDeskId") REFERENCES "SalesDesks"("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ActualRunSalesDeskCorrections_SalesDesks_PreviousSalesDeskId" FOREIGN KEY ("PreviousSalesDeskId") REFERENCES "SalesDesks"("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ActualRunSalesDeskCorrections_Users_CorrectedByUserId" FOREIGN KEY ("CorrectedByUserId") REFERENCES "Users"("Id") ON DELETE RESTRICT
);
INSERT INTO "SalesDesks" ("Id","Name","IsActive","DisplayOrder","CreatedAt","UpdatedAt") VALUES
    (1,'Domex',true,10,'2026-05-21T00:00:00Z','2026-05-21T00:00:00Z'),
    (2,'Honey Bear',true,20,'2026-05-21T00:00:00Z','2026-05-21T00:00:00Z'),
    (3,'Viva Tierra',true,30,'2026-05-21T00:00:00Z','2026-05-21T00:00:00Z');
SELECT setval(pg_get_serial_sequence('"SalesDesks"','Id'), GREATEST((SELECT max("Id") FROM "SalesDesks"),1), true);
CREATE INDEX "IX_ActualRuns_SalesDeskId_Status_RunAt" ON "ActualRuns"("SalesDeskId","Status","RunAt");
CREATE INDEX "IX_ActualRunOverrideRequests_SalesDeskId" ON "ActualRunOverrideRequests"("SalesDeskId");
CREATE INDEX "IX_ActualRunSalesDeskCorrections_ActualRunId_CorrectedAt" ON "ActualRunSalesDeskCorrections"("ActualRunId","CorrectedAt");
CREATE INDEX "IX_ActualRunSalesDeskCorrections_CorrectedByUserId" ON "ActualRunSalesDeskCorrections"("CorrectedByUserId");
CREATE INDEX "IX_ActualRunSalesDeskCorrections_NewSalesDeskId" ON "ActualRunSalesDeskCorrections"("NewSalesDeskId");
CREATE UNIQUE INDEX "IX_ActualRunSalesDeskCorrections_OperationKey" ON "ActualRunSalesDeskCorrections"("OperationKey");
CREATE INDEX "IX_ActualRunSalesDeskCorrections_PreviousSalesDeskId" ON "ActualRunSalesDeskCorrections"("PreviousSalesDeskId");
CREATE INDEX "IX_SalesDesks_CreatedByUserId" ON "SalesDesks"("CreatedByUserId");
CREATE INDEX "IX_SalesDesks_IsActive_DisplayOrder_Name" ON "SalesDesks"("IsActive","DisplayOrder","Name");
CREATE UNIQUE INDEX "IX_SalesDesks_Name" ON "SalesDesks"("Name");
CREATE INDEX "IX_SalesDesks_UpdatedByUserId" ON "SalesDesks"("UpdatedByUserId");
ALTER TABLE "ActualRuns" ADD CONSTRAINT "FK_ActualRuns_SalesDesks_SalesDeskId" FOREIGN KEY ("SalesDeskId") REFERENCES "SalesDesks"("Id") ON DELETE RESTRICT;
ALTER TABLE "ActualRunOverrideRequests" ADD CONSTRAINT "FK_ActualRunOverrideRequests_SalesDesks_SalesDeskId" FOREIGN KEY ("SalesDeskId") REFERENCES "SalesDesks"("Id") ON DELETE RESTRICT;
\else
\echo 'Actual Run Sales Desk schema is already complete and exact; no DDL or configuration writes will be applied.'
\endif
DO $postcheck$ BEGIN
    IF to_regclass(format('%I.%I',current_schema(),'SalesDesks')) IS NULL THEN RAISE EXCEPTION 'SalesDesks schema missing after apply'; END IF;
    IF current_setting('cropqc.test_force_sales_desk_failure',true)='on' THEN RAISE EXCEPTION 'Forced Sales Desk compatibility failure for rollback regression'; END IF;
END $postcheck$;
COMMIT;
\ir verify-actual-run-sales-desk-attribution.sql
