\set ON_ERROR_STOP on
\ir preflight-room-treatment-tracking.sql

BEGIN;
SELECT pg_advisory_xact_lock(hashtextextended('CropQc:20260818181556_AddRoomTreatmentTracking', 0));
SELECT to_regclass(format('%I.%I', current_schema(), 'TreatmentChemicals')) IS NULL AS create_target \gset
\if :create_target

ALTER TABLE "BinsRunEntries" ADD COLUMN "TreatmentSignatureSnapshot" character varying(1000) NULL;
ALTER TABLE "BinsRunEntries" ADD COLUMN "TreatmentStateSnapshot" character varying(25) NULL;
ALTER TABLE "BinsRunEntries" ADD COLUMN "TreatmentSummarySnapshot" character varying(2000) NULL;
ALTER TABLE "ActualRunOverrideRequestLines" ADD COLUMN "TreatmentSignature" character varying(1000) NULL;

CREATE TABLE "TreatmentChemicals" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProductName" character varying(200) NOT NULL,
    "CommonName" character varying(200) NULL,
    "Crop" character varying(25) NOT NULL,
    "Volume" numeric(12,2) NOT NULL,
    "Unit" character varying(25) NOT NULL,
    "UnitPrice" numeric(12,2) NOT NULL,
    "Currency" character varying(3) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedByUserId" integer NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedByUserId" integer NULL,
    CONSTRAINT "PK_TreatmentChemicals" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TreatmentChemicals_Users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_TreatmentChemicals_Users_UpdatedByUserId" FOREIGN KEY ("UpdatedByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
);

CREATE TABLE "TreatmentLineageSegments" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "WarehouseId" integer NOT NULL,
    "RoomId" integer NOT NULL,
    "CropYear" integer NULL,
    "GrowerLotId" integer NULL,
    "FruitProfileId" integer NULL,
    "IdentityKey" character varying(500) NOT NULL,
    "GrowerNumberSnapshot" character varying(50) NULL,
    "GrowerNameSnapshot" character varying(200) NOT NULL,
    "LotNumberSnapshot" character varying(100) NOT NULL,
    "VarietyCodeSnapshot" character varying(50) NOT NULL,
    "ProductionTypeSnapshot" character varying(50) NOT NULL,
    "IsOrganicSnapshot" boolean NULL,
    "InventoryStatusSnapshot" character varying(100) NULL,
    "TreatmentState" character varying(25) NOT NULL,
    "TreatmentSignature" character varying(1000) NOT NULL,
    "CurrentBins" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "ConcurrencyVersion" bigint NOT NULL,
    CONSTRAINT "PK_TreatmentLineageSegments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TreatmentLineageSegments_FruitProfiles_FruitProfileId" FOREIGN KEY ("FruitProfileId") REFERENCES "FruitProfiles" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_TreatmentLineageSegments_Rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES "Rooms" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_TreatmentLineageSegments_Warehouses_WarehouseId" FOREIGN KEY ("WarehouseId") REFERENCES "Warehouses" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "RoomTreatmentApplications" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "OperationKey" character varying(100) NOT NULL,
    "TreatmentChemicalId" integer NOT NULL,
    "WarehouseId" integer NOT NULL,
    "RoomId" integer NOT NULL,
    "AppliedAt" timestamp with time zone NOT NULL,
    "AppliedByUserId" integer NOT NULL,
    "Notes" character varying(1000) NULL,
    "TotalBinsSnapshot" integer NOT NULL,
    "ProductNameSnapshot" character varying(200) NOT NULL,
    "CommonNameSnapshot" character varying(200) NULL,
    "CropSnapshot" character varying(25) NOT NULL,
    "VolumeSnapshot" numeric(12,2) NOT NULL,
    "UnitSnapshot" character varying(25) NOT NULL,
    "UnitPriceSnapshot" numeric(12,2) NOT NULL,
    "CurrencySnapshot" character varying(3) NOT NULL,
    "EstimatedCostSnapshot" numeric(14,2) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedByUserId" integer NOT NULL,
    "ReversedAt" timestamp with time zone NULL,
    "ReversedByUserId" integer NULL,
    "ReversalReason" character varying(1000) NULL,
    CONSTRAINT "PK_RoomTreatmentApplications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RoomTreatmentApplications_Rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES "Rooms" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_RoomTreatmentApplications_TreatmentChemicals_TreatmentChemicalId" FOREIGN KEY ("TreatmentChemicalId") REFERENCES "TreatmentChemicals" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_RoomTreatmentApplications_Users_AppliedByUserId" FOREIGN KEY ("AppliedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_RoomTreatmentApplications_Users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_RoomTreatmentApplications_Users_ReversedByUserId" FOREIGN KEY ("ReversedByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_RoomTreatmentApplications_Warehouses_WarehouseId" FOREIGN KEY ("WarehouseId") REFERENCES "Warehouses" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "TreatmentLineageMovements" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "OperationKey" character varying(200) NOT NULL,
    "MovementType" character varying(50) NOT NULL,
    "SourceSegmentId" bigint NULL,
    "DestinationSegmentId" bigint NULL,
    "SourceRoomId" integer NULL,
    "DestinationRoomId" integer NULL,
    "IdentityKey" character varying(500) NOT NULL,
    "TreatmentStateSnapshot" character varying(25) NOT NULL,
    "TreatmentSignatureSnapshot" character varying(1000) NOT NULL,
    "BinCount" integer NOT NULL,
    "RoomTransferId" bigint NULL,
    "RoomInventoryLossId" bigint NULL,
    "BinsRunEntryId" bigint NULL,
    "ReversesTreatmentLineageMovementId" bigint NULL,
    "OccurredAt" timestamp with time zone NOT NULL,
    "CreatedByUserId" integer NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TreatmentLineageMovements" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TreatmentLineageMovements_BinsRunEntries_BinsRunEntryId" FOREIGN KEY ("BinsRunEntryId") REFERENCES "BinsRunEntries" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_TreatmentLineageMovements_RoomInventoryLosses_RoomInventoryLossId" FOREIGN KEY ("RoomInventoryLossId") REFERENCES "RoomInventoryLosses" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_TreatmentLineageMovements_RoomTransfers_RoomTransferId" FOREIGN KEY ("RoomTransferId") REFERENCES "RoomTransfers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_TreatmentLineageMovements_Rooms_DestinationRoomId" FOREIGN KEY ("DestinationRoomId") REFERENCES "Rooms" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_TreatmentLineageMovements_Rooms_SourceRoomId" FOREIGN KEY ("SourceRoomId") REFERENCES "Rooms" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_TreatmentLineageMovements_TreatmentLineageMovements_ReversesTreatmentLineageMovementId" FOREIGN KEY ("ReversesTreatmentLineageMovementId") REFERENCES "TreatmentLineageMovements" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_TreatmentLineageMovements_TreatmentLineageSegments_DestinationSegmentId" FOREIGN KEY ("DestinationSegmentId") REFERENCES "TreatmentLineageSegments" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_TreatmentLineageMovements_TreatmentLineageSegments_SourceSegmentId" FOREIGN KEY ("SourceSegmentId") REFERENCES "TreatmentLineageSegments" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_TreatmentLineageMovements_Users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
);

CREATE TABLE "RoomTreatmentApplicationSources" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "RoomTreatmentApplicationId" bigint NOT NULL,
    "CropYear" integer NULL,
    "GrowerLotId" integer NULL,
    "FruitProfileId" integer NULL,
    "IdentityKey" character varying(500) NOT NULL,
    "GrowerNumberSnapshot" character varying(50) NULL,
    "GrowerNameSnapshot" character varying(200) NOT NULL,
    "LotNumberSnapshot" character varying(100) NOT NULL,
    "VarietyCodeSnapshot" character varying(50) NOT NULL,
    "ProductionTypeSnapshot" character varying(50) NOT NULL,
    "IsOrganicSnapshot" boolean NULL,
    "InventoryStatusSnapshot" character varying(100) NULL,
    "BinsTreated" integer NOT NULL,
    "PriorTreatmentSignature" character varying(1000) NOT NULL,
    "ResultTreatmentSignature" character varying(1000) NOT NULL,
    CONSTRAINT "PK_RoomTreatmentApplicationSources" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RoomTreatmentApplicationSources_FruitProfiles_FruitProfileId" FOREIGN KEY ("FruitProfileId") REFERENCES "FruitProfiles" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_RoomTreatmentApplicationSources_RoomTreatmentApplications_RoomTreatmentApplicationId" FOREIGN KEY ("RoomTreatmentApplicationId") REFERENCES "RoomTreatmentApplications" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TreatmentLineageSegmentApplications" (
    "TreatmentLineageSegmentId" bigint NOT NULL,
    "RoomTreatmentApplicationId" bigint NOT NULL,
    "Sequence" integer NOT NULL,
    CONSTRAINT "PK_TreatmentLineageSegmentApplications" PRIMARY KEY ("TreatmentLineageSegmentId", "RoomTreatmentApplicationId"),
    CONSTRAINT "FK_TreatmentLineageSegmentApplications_RoomTreatmentApplications_RoomTreatmentApplicationId" FOREIGN KEY ("RoomTreatmentApplicationId") REFERENCES "RoomTreatmentApplications" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_TreatmentLineageSegmentApplications_TreatmentLineageSegments_TreatmentLineageSegmentId" FOREIGN KEY ("TreatmentLineageSegmentId") REFERENCES "TreatmentLineageSegments" ("Id") ON DELETE CASCADE
);

INSERT INTO "TreatmentChemicals" ("Id","CommonName","CreatedAt","CreatedByUserId","Crop","Currency","IsActive","ProductName","Unit","UnitPrice","UpdatedAt","UpdatedByUserId","Volume") VALUES
(1,NULL,'2026-05-21T00:00:00Z',NULL,'Apples','USD',TRUE,'eFOG-160 PYR FOGGING','BIN',5.25,'2026-05-21T00:00:00Z',NULL,1.00),
(2,NULL,'2026-05-21T00:00:00Z',NULL,'Apples','USD',TRUE,'FOGGING EF 170,SB TBZ 99, EF80','BIN',5.67,'2026-05-21T00:00:00Z',NULL,1.00),
(3,NULL,'2026-05-21T00:00:00Z',NULL,'Pears','USD',TRUE,'FOGGING EF 180, TBZ 99, EF 80','BIN',9.58,'2026-05-21T00:00:00Z',NULL,1.00),
(4,NULL,'2026-05-21T00:00:00Z',NULL,'Pears','USD',TRUE,'eFOG-80 FDL FOGGING','BIN',5.25,'2026-05-21T00:00:00Z',NULL,1.00),
(5,NULL,'2026-05-21T00:00:00Z',NULL,'Apples','USD',TRUE,'FOGGING EF 170, EF 160','BIN',5.67,'2026-05-21T00:00:00Z',NULL,1.00),
(6,NULL,'2026-05-21T00:00:00Z',NULL,'Pears','USD',TRUE,'eFOG-180 FOGGING','BIN',4.95,'2026-05-21T00:00:00Z',NULL,1.00),
(7,NULL,'2026-05-21T00:00:00Z',NULL,'Apples','USD',TRUE,'FOGGING EF 170, EF 80','BIN',5.67,'2026-05-21T00:00:00Z',NULL,1.00),
(8,NULL,'2026-05-21T00:00:00Z',NULL,'Pears','USD',TRUE,'FOGGING EF 180, EF 160','BIN',9.27,'2026-05-21T00:00:00Z',NULL,1.00),
(9,NULL,'2026-05-21T00:00:00Z',NULL,'Apples','USD',TRUE,'FOGGING EF 170, SB TBZ 99','BIN',5.25,'2026-05-21T00:00:00Z',NULL,1.00),
(10,NULL,'2026-05-21T00:00:00Z',NULL,'Apples','USD',TRUE,'eFOG-170 DPA FOGGING','BIN',2.80,'2026-05-21T00:00:00Z',NULL,1.00);
SELECT setval(pg_get_serial_sequence('"TreatmentChemicals"','Id'), 10, true);

CREATE INDEX "IX_RoomTreatmentApplications_AppliedByUserId" ON "RoomTreatmentApplications" ("AppliedByUserId");
CREATE INDEX "IX_RoomTreatmentApplications_CreatedByUserId" ON "RoomTreatmentApplications" ("CreatedByUserId");
CREATE UNIQUE INDEX "IX_RoomTreatmentApplications_OperationKey" ON "RoomTreatmentApplications" ("OperationKey");
CREATE INDEX "IX_RoomTreatmentApplications_ReversedByUserId" ON "RoomTreatmentApplications" ("ReversedByUserId");
CREATE INDEX "IX_RoomTreatmentApplications_RoomId_AppliedAt" ON "RoomTreatmentApplications" ("RoomId", "AppliedAt");
CREATE INDEX "IX_RoomTreatmentApplications_TreatmentChemicalId" ON "RoomTreatmentApplications" ("TreatmentChemicalId");
CREATE INDEX "IX_RoomTreatmentApplications_WarehouseId" ON "RoomTreatmentApplications" ("WarehouseId");
CREATE INDEX "IX_RoomTreatmentApplicationSources_FruitProfileId" ON "RoomTreatmentApplicationSources" ("FruitProfileId");
CREATE INDEX "IX_RoomTreatmentApplicationSources_GrowerLotId" ON "RoomTreatmentApplicationSources" ("GrowerLotId");
CREATE INDEX "IX_RoomTreatmentApplicationSources_RoomTreatmentApplicationId_IdentityKey" ON "RoomTreatmentApplicationSources" ("RoomTreatmentApplicationId", "IdentityKey");
CREATE INDEX "IX_TreatmentChemicals_CreatedByUserId" ON "TreatmentChemicals" ("CreatedByUserId");
CREATE INDEX "IX_TreatmentChemicals_Crop_IsActive_ProductName" ON "TreatmentChemicals" ("Crop", "IsActive", "ProductName");
CREATE UNIQUE INDEX "IX_TreatmentChemicals_ProductName" ON "TreatmentChemicals" ("ProductName");
CREATE INDEX "IX_TreatmentChemicals_UpdatedByUserId" ON "TreatmentChemicals" ("UpdatedByUserId");
CREATE INDEX "IX_TreatmentLineageMovements_BinsRunEntryId" ON "TreatmentLineageMovements" ("BinsRunEntryId");
CREATE INDEX "IX_TreatmentLineageMovements_CreatedByUserId" ON "TreatmentLineageMovements" ("CreatedByUserId");
CREATE INDEX "IX_TreatmentLineageMovements_DestinationRoomId_OccurredAt" ON "TreatmentLineageMovements" ("DestinationRoomId", "OccurredAt");
CREATE INDEX "IX_TreatmentLineageMovements_DestinationSegmentId" ON "TreatmentLineageMovements" ("DestinationSegmentId");
CREATE UNIQUE INDEX "IX_TreatmentLineageMovements_OperationKey" ON "TreatmentLineageMovements" ("OperationKey");
CREATE INDEX "IX_TreatmentLineageMovements_ReversesTreatmentLineageMovementId" ON "TreatmentLineageMovements" ("ReversesTreatmentLineageMovementId");
CREATE INDEX "IX_TreatmentLineageMovements_RoomInventoryLossId" ON "TreatmentLineageMovements" ("RoomInventoryLossId");
CREATE INDEX "IX_TreatmentLineageMovements_RoomTransferId" ON "TreatmentLineageMovements" ("RoomTransferId");
CREATE INDEX "IX_TreatmentLineageMovements_SourceRoomId_OccurredAt" ON "TreatmentLineageMovements" ("SourceRoomId", "OccurredAt");
CREATE INDEX "IX_TreatmentLineageMovements_SourceSegmentId" ON "TreatmentLineageMovements" ("SourceSegmentId");
CREATE INDEX "IX_TreatmentLineageSegmentApplications_RoomTreatmentApplicationId_TreatmentLineageSegmentId" ON "TreatmentLineageSegmentApplications" ("RoomTreatmentApplicationId", "TreatmentLineageSegmentId");
CREATE INDEX "IX_TreatmentLineageSegments_FruitProfileId" ON "TreatmentLineageSegments" ("FruitProfileId");
CREATE INDEX "IX_TreatmentLineageSegments_GrowerLotId" ON "TreatmentLineageSegments" ("GrowerLotId");
CREATE INDEX "IX_TreatmentLineageSegments_RoomId_CurrentBins" ON "TreatmentLineageSegments" ("RoomId", "CurrentBins");
CREATE UNIQUE INDEX "IX_TreatmentLineageSegments_RoomId_IdentityKey_TreatmentSignature" ON "TreatmentLineageSegments" ("RoomId", "IdentityKey", "TreatmentSignature");
CREATE INDEX "IX_TreatmentLineageSegments_WarehouseId" ON "TreatmentLineageSegments" ("WarehouseId");

\else
\echo 'Room treatment tracking schema is already complete and exact; no DDL or seed writes will be applied.'
\endif

DO $postcheck$
BEGIN
    IF to_regclass(format('%I.%I', current_schema(), 'TreatmentChemicals')) IS NULL
       OR to_regclass(format('%I.%I', current_schema(), 'RoomTreatmentApplications')) IS NULL
       OR to_regclass(format('%I.%I', current_schema(), 'RoomTreatmentApplicationSources')) IS NULL
       OR to_regclass(format('%I.%I', current_schema(), 'TreatmentLineageSegments')) IS NULL
       OR to_regclass(format('%I.%I', current_schema(), 'TreatmentLineageSegmentApplications')) IS NULL
       OR to_regclass(format('%I.%I', current_schema(), 'TreatmentLineageMovements')) IS NULL THEN
        RAISE EXCEPTION 'Post-apply room treatment object set is incomplete; transaction will roll back.';
    END IF;
    IF current_setting('cropqc.test_force_room_treatment_failure', true) = 'on' THEN
        RAISE EXCEPTION 'Forced room treatment compatibility-apply failure for rollback regression testing.';
    END IF;
END $postcheck$;
COMMIT;

\ir verify-room-treatment-tracking.sql
