\set ON_ERROR_STOP on
\ir preflight-actual-run-detail-corrections.sql

BEGIN;
SET LOCAL lock_timeout='15s';
SET LOCAL statement_timeout='10min';
SELECT pg_advisory_xact_lock(hashtextextended('CropQc:20260902201338_AddActualRunDetailCorrections',0));
SELECT to_regclass(format('%I.%I',current_schema(),'ActualRunDetailCorrections')) IS NULL AS create_target \gset
\if :create_target
CREATE TABLE "ActualRunDetailCorrections" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ActualRunId" bigint NOT NULL,
    "OperationKey" character varying(64) NOT NULL,
    "ExpectedConcurrencyVersion" bigint NOT NULL,
    "PreviousRunAt" timestamp with time zone NOT NULL,
    "NewRunAt" timestamp with time zone NOT NULL,
    "PreviousNotes" character varying(1000),
    "NewNotes" character varying(1000),
    "Reason" character varying(1000) NOT NULL,
    "CorrectedByUserId" integer NOT NULL,
    "CorrectedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ActualRunDetailCorrections" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ActualRunDetailCorrections_ActualRuns_ActualRunId" FOREIGN KEY ("ActualRunId") REFERENCES "ActualRuns"("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ActualRunDetailCorrections_Users_CorrectedByUserId" FOREIGN KEY ("CorrectedByUserId") REFERENCES "Users"("Id") ON DELETE RESTRICT
);
CREATE INDEX "IX_ActualRunDetailCorrections_ActualRunId_CorrectedAt" ON "ActualRunDetailCorrections"("ActualRunId","CorrectedAt");
CREATE INDEX "IX_ActualRunDetailCorrections_CorrectedByUserId" ON "ActualRunDetailCorrections"("CorrectedByUserId");
CREATE UNIQUE INDEX "IX_ActualRunDetailCorrections_OperationKey" ON "ActualRunDetailCorrections"("OperationKey");
\else
\echo 'Actual Run detail correction schema is already complete and exact; no DDL or data writes will be applied.'
\endif
DO $postcheck$ BEGIN
    IF to_regclass(format('%I.%I',current_schema(),'ActualRunDetailCorrections')) IS NULL THEN
        RAISE EXCEPTION 'Actual Run detail correction schema missing after apply';
    END IF;
    IF current_setting('cropqc.test_force_actual_run_detail_failure',true)='on' THEN
        RAISE EXCEPTION 'Forced Actual Run detail correction compatibility failure for rollback regression';
    END IF;
END $postcheck$;
COMMIT;
\ir verify-actual-run-detail-corrections.sql
