\set ON_ERROR_STOP on
\ir preflight-room-sealing.sql

BEGIN;
SET LOCAL lock_timeout='15s';
SET LOCAL statement_timeout='10min';
SELECT pg_advisory_xact_lock(hashtextextended('CropQc:20260821140736_AddRoomSealing',0));
SELECT to_regclass(format('%I.%I',current_schema(),'RoomSealEvents')) IS NULL AS create_target \gset
\if :create_target
ALTER TABLE "Rooms" ADD COLUMN "IsSealed" boolean NOT NULL DEFAULT false;
ALTER TABLE "Rooms" ADD COLUMN "SealedAt" timestamp with time zone;
ALTER TABLE "Rooms" ADD COLUMN "SealedByUserId" integer;

CREATE TABLE "RoomSealEvents" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "RoomId" integer NOT NULL,
    "Action" character varying(20) NOT NULL,
    "ChangedAt" timestamp with time zone NOT NULL,
    "ChangedByUserId" integer NOT NULL,
    "WarehouseCodeSnapshot" character varying(25) NOT NULL,
    "RoomCodeSnapshot" character varying(150) NOT NULL,
    "Note" character varying(500),
    CONSTRAINT "PK_RoomSealEvents" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_RoomSealEvents_Action" CHECK ("Action" IN ('Seal', 'Unseal')),
    CONSTRAINT "FK_RoomSealEvents_Rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES "Rooms"("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_RoomSealEvents_Users_ChangedByUserId" FOREIGN KEY ("ChangedByUserId") REFERENCES "Users"("Id") ON DELETE RESTRICT
);
CREATE INDEX "IX_Rooms_SealedByUserId" ON "Rooms"("SealedByUserId");
CREATE INDEX "IX_RoomSealEvents_ChangedByUserId" ON "RoomSealEvents"("ChangedByUserId");
CREATE INDEX "IX_RoomSealEvents_RoomId_ChangedAt" ON "RoomSealEvents"("RoomId","ChangedAt");
ALTER TABLE "Rooms" ADD CONSTRAINT "FK_Rooms_Users_SealedByUserId" FOREIGN KEY ("SealedByUserId") REFERENCES "Users"("Id") ON DELETE SET NULL;
\else
\echo 'Room Sealing schema is already complete and exact; no DDL will be applied.'
\endif
DO $postcheck$ BEGIN
    IF to_regclass(format('%I.%I',current_schema(),'RoomSealEvents')) IS NULL THEN RAISE EXCEPTION 'Room Sealing schema missing after apply'; END IF;
    IF current_setting('cropqc.test_force_room_sealing_failure',true)='on' THEN RAISE EXCEPTION 'Forced Room Sealing compatibility failure for rollback regression'; END IF;
END $postcheck$;
COMMIT;
\ir verify-room-sealing.sql
