\set ON_ERROR_STOP on
\ir preflight-grower-number-qc-recipients.sql

BEGIN;
SET LOCAL lock_timeout='15s';
SET LOCAL statement_timeout='10min';
SELECT pg_advisory_xact_lock(hashtextextended('CropQc:20260826063718_AddGrowerNumberQcRecipients', 0));
SELECT to_regclass(format('%I.%I', current_schema(), 'GrowerReportRecipients')) IS NULL AS create_target \gset

\if :create_target
CREATE TABLE "GrowerReportRecipients" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CanonicalGrowerNumberId" integer NOT NULL,
    "EmailAddress" character varying(320) NOT NULL,
    "NormalizedEmailAddress" character varying(320) NOT NULL,
    "IsActive" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedByUserId" integer,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedByUserId" integer,
    "DeletedAt" timestamp with time zone,
    "DeletedByUserId" integer,
    CONSTRAINT "PK_GrowerReportRecipients" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_GrowerReportRecipients_CanonicalGrowerNumbers_CanonicalGrowerNumberId"
        FOREIGN KEY ("CanonicalGrowerNumberId") REFERENCES "CanonicalGrowerNumbers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_GrowerReportRecipients_Users_CreatedByUserId"
        FOREIGN KEY ("CreatedByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_GrowerReportRecipients_Users_DeletedByUserId"
        FOREIGN KEY ("DeletedByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_GrowerReportRecipients_Users_UpdatedByUserId"
        FOREIGN KEY ("UpdatedByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
);
CREATE INDEX "IX_GrowerReportRecipients_CanonicalGrowerNumberId_IsActive_IsDeleted"
    ON "GrowerReportRecipients" ("CanonicalGrowerNumberId", "IsActive", "IsDeleted");
CREATE UNIQUE INDEX "IX_GrowerReportRecipients_CanonicalGrowerNumberId_NormalizedEmailAddress"
    ON "GrowerReportRecipients" ("CanonicalGrowerNumberId", "NormalizedEmailAddress") WHERE "IsDeleted" = FALSE;
CREATE INDEX "IX_GrowerReportRecipients_CreatedByUserId" ON "GrowerReportRecipients" ("CreatedByUserId");
CREATE INDEX "IX_GrowerReportRecipients_DeletedByUserId" ON "GrowerReportRecipients" ("DeletedByUserId");
CREATE INDEX "IX_GrowerReportRecipients_UpdatedByUserId" ON "GrowerReportRecipients" ("UpdatedByUserId");
\else
\echo 'Grower Number QC recipient schema is already complete and exact; no DDL will be applied.'
\endif

DO $postcheck$
BEGIN
    IF current_setting('cropqc.test_force_grower_recipient_failure', true)='on' THEN
        RAISE EXCEPTION 'Forced Grower Number QC recipient compatibility failure for rollback regression';
    END IF;
END $postcheck$;
COMMIT;
\ir verify-grower-number-qc-recipients.sql
