\set ON_ERROR_STOP on
\ir preflight-transfer-custody-workflow.sql

BEGIN;
SET LOCAL lock_timeout='15s';
SET LOCAL statement_timeout='10min';
SELECT pg_advisory_xact_lock(hashtextextended('CropQc:20260828033737_AddTransferCustodyWorkflow', 0));
SELECT to_regclass(format('%I.%I', current_schema(), 'OutsideWarehouses')) IS NULL AS create_target \gset

\if :create_target
ALTER TABLE "TreatmentLineageMovements" ADD COLUMN "InterCrewTransferId" bigint;
ALTER TABLE "TreatmentLineageMovements" ADD COLUMN "OutsideWarehouseTransferId" bigint;
ALTER TABLE "RoomInventoryAdjustments" ADD COLUMN "InterCrewTransferId" bigint;
ALTER TABLE "RoomInventoryAdjustments" ADD COLUMN "OutsideWarehouseTransferId" bigint;

CREATE TABLE "InterCrewTransfers" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "OperationKey" character varying(150) NOT NULL,
    "SourceWarehouseId" integer NOT NULL,
    "SourceRoomId" integer NOT NULL,
    "DestinationCustodyGroup" character varying(20) NOT NULL,
    "DestinationWarehouseId" integer,
    "DestinationRoomId" integer,
    "ReceiptId" bigint,
    "SourceInventoryAdjustmentId" bigint,
    "CropYear" integer,
    "GrowerLotId" integer,
    "FruitProfileId" integer,
    "GrowerNumberSnapshot" character varying(50),
    "GrowerNameSnapshot" character varying(200) NOT NULL,
    "LotNumberSnapshot" character varying(100) NOT NULL,
    "VarietyCodeSnapshot" character varying(50) NOT NULL,
    "ProductionTypeSnapshot" character varying(50) NOT NULL,
    "IsOrganicSnapshot" boolean,
    "InventoryStatusSnapshot" character varying(100),
    "TreatmentStateSnapshot" character varying(25) NOT NULL,
    "TreatmentSignatureSnapshot" character varying(1000) NOT NULL,
    "TreatmentSummarySnapshot" character varying(2000) NOT NULL,
    "BinsLoaded" integer NOT NULL,
    "LoadedAt" timestamp with time zone NOT NULL,
    "TruckLoadBolNumber" character varying(150),
    "Notes" character varying(1000),
    "LoadedByUserId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "Status" character varying(30) NOT NULL,
    "ReceiveOperationKey" character varying(150),
    "BinsReceived" integer,
    "VarianceBins" integer,
    "ReceivedAt" timestamp with time zone,
    "ReceivedByUserId" integer,
    "ReceivingNote" character varying(1000),
    "ReviewOperationKey" character varying(150),
    "ReviewNote" character varying(1000),
    "ReviewedAt" timestamp with time zone,
    "ReviewedByUserId" integer,
    "ReversalOperationKey" character varying(150),
    "ReversalReason" character varying(1000),
    "ReversedAt" timestamp with time zone,
    "ReversedByUserId" integer,
    "ConcurrencyVersion" bigint NOT NULL,
    CONSTRAINT "PK_InterCrewTransfers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InterCrewTransfers_FruitProfiles_FruitProfileId" FOREIGN KEY ("FruitProfileId") REFERENCES "FruitProfiles" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_InterCrewTransfers_Receipts_ReceiptId" FOREIGN KEY ("ReceiptId") REFERENCES "Receipts" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_InterCrewTransfers_RoomInventoryAdjustments_SourceInventoryAdjustmentId" FOREIGN KEY ("SourceInventoryAdjustmentId") REFERENCES "RoomInventoryAdjustments" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_InterCrewTransfers_Rooms_DestinationRoomId" FOREIGN KEY ("DestinationRoomId") REFERENCES "Rooms" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_InterCrewTransfers_Rooms_SourceRoomId" FOREIGN KEY ("SourceRoomId") REFERENCES "Rooms" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_InterCrewTransfers_Users_LoadedByUserId" FOREIGN KEY ("LoadedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_InterCrewTransfers_Users_ReceivedByUserId" FOREIGN KEY ("ReceivedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_InterCrewTransfers_Users_ReversedByUserId" FOREIGN KEY ("ReversedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_InterCrewTransfers_Users_ReviewedByUserId" FOREIGN KEY ("ReviewedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_InterCrewTransfers_Warehouses_DestinationWarehouseId" FOREIGN KEY ("DestinationWarehouseId") REFERENCES "Warehouses" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_InterCrewTransfers_Warehouses_SourceWarehouseId" FOREIGN KEY ("SourceWarehouseId") REFERENCES "Warehouses" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "OutsideWarehouses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Code" character varying(50) NOT NULL,
    "Address" character varying(500),
    "Notes" character varying(1000),
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedByUserId" integer,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedByUserId" integer,
    CONSTRAINT "PK_OutsideWarehouses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OutsideWarehouses_Users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_OutsideWarehouses_Users_UpdatedByUserId" FOREIGN KEY ("UpdatedByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
);

CREATE TABLE "OutsideWarehouseTransfers" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "OperationKey" character varying(150) NOT NULL,
    "OutsideWarehouseId" integer NOT NULL,
    "OutsideWarehouseCodeSnapshot" character varying(50) NOT NULL,
    "OutsideWarehouseNameSnapshot" character varying(200) NOT NULL,
    "OutsideWarehouseAddressSnapshot" character varying(500),
    "SourceWarehouseId" integer NOT NULL,
    "SourceRoomId" integer NOT NULL,
    "ReceiptId" bigint,
    "SourceInventoryAdjustmentId" bigint,
    "CropYear" integer,
    "GrowerLotId" integer,
    "FruitProfileId" integer,
    "GrowerNumberSnapshot" character varying(50),
    "GrowerNameSnapshot" character varying(200) NOT NULL,
    "LotNumberSnapshot" character varying(100) NOT NULL,
    "VarietyCodeSnapshot" character varying(50) NOT NULL,
    "ProductionTypeSnapshot" character varying(50) NOT NULL,
    "IsOrganicSnapshot" boolean,
    "InventoryStatusSnapshot" character varying(100),
    "TreatmentStateSnapshot" character varying(25) NOT NULL,
    "TreatmentSignatureSnapshot" character varying(1000) NOT NULL,
    "TreatmentSummarySnapshot" character varying(2000) NOT NULL,
    "BinCount" integer NOT NULL,
    "TransferredAt" timestamp with time zone NOT NULL,
    "TruckLoadBolNumber" character varying(150),
    "Notes" character varying(1000),
    "CreatedByUserId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsReversed" boolean NOT NULL,
    "ReversalOperationKey" character varying(150),
    "ReversedAt" timestamp with time zone,
    "ReversedByUserId" integer,
    "ReverseReason" character varying(1000),
    "ConcurrencyVersion" bigint NOT NULL,
    CONSTRAINT "PK_OutsideWarehouseTransfers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OutsideWarehouseTransfers_FruitProfiles_FruitProfileId" FOREIGN KEY ("FruitProfileId") REFERENCES "FruitProfiles" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_OutsideWarehouseTransfers_OutsideWarehouses_OutsideWarehouseId" FOREIGN KEY ("OutsideWarehouseId") REFERENCES "OutsideWarehouses" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_OutsideWarehouseTransfers_Receipts_ReceiptId" FOREIGN KEY ("ReceiptId") REFERENCES "Receipts" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_OutsideWarehouseTransfers_RoomInventoryAdjustments_SourceInventoryAdjustmentId" FOREIGN KEY ("SourceInventoryAdjustmentId") REFERENCES "RoomInventoryAdjustments" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_OutsideWarehouseTransfers_Rooms_SourceRoomId" FOREIGN KEY ("SourceRoomId") REFERENCES "Rooms" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_OutsideWarehouseTransfers_Users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_OutsideWarehouseTransfers_Users_ReversedByUserId" FOREIGN KEY ("ReversedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_OutsideWarehouseTransfers_Warehouses_SourceWarehouseId" FOREIGN KEY ("SourceWarehouseId") REFERENCES "Warehouses" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_TreatmentLineageMovements_OutsideWarehouseTransferId" ON "TreatmentLineageMovements" ("OutsideWarehouseTransferId");
CREATE INDEX "IX_TreatmentLineageMovements_InterCrewTransferId" ON "TreatmentLineageMovements" ("InterCrewTransferId");
CREATE INDEX "IX_RoomInventoryAdjustments_OutsideWarehouseTransferId" ON "RoomInventoryAdjustments" ("OutsideWarehouseTransferId");
CREATE INDEX "IX_RoomInventoryAdjustments_InterCrewTransferId" ON "RoomInventoryAdjustments" ("InterCrewTransferId");
CREATE UNIQUE INDEX "IX_RoomInventoryAdjustments_InterCrewTransferId_AdjustmentType" ON "RoomInventoryAdjustments" ("InterCrewTransferId", "AdjustmentType") WHERE "InterCrewTransferId" IS NOT NULL;
CREATE UNIQUE INDEX "IX_RoomInventoryAdjustments_OutsideWarehouseTransferId_AdjustmentType" ON "RoomInventoryAdjustments" ("OutsideWarehouseTransferId", "AdjustmentType") WHERE "OutsideWarehouseTransferId" IS NOT NULL;
CREATE UNIQUE INDEX "IX_OutsideWarehouses_Code" ON "OutsideWarehouses" ("Code");
CREATE INDEX "IX_OutsideWarehouses_CreatedByUserId" ON "OutsideWarehouses" ("CreatedByUserId");
CREATE INDEX "IX_OutsideWarehouses_IsActive_Name" ON "OutsideWarehouses" ("IsActive", "Name");
CREATE INDEX "IX_OutsideWarehouses_UpdatedByUserId" ON "OutsideWarehouses" ("UpdatedByUserId");
CREATE INDEX "IX_OutsideWarehouseTransfers_CreatedByUserId" ON "OutsideWarehouseTransfers" ("CreatedByUserId");
CREATE INDEX "IX_OutsideWarehouseTransfers_FruitProfileId" ON "OutsideWarehouseTransfers" ("FruitProfileId");
CREATE INDEX "IX_OutsideWarehouseTransfers_GrowerNumberSnapshot" ON "OutsideWarehouseTransfers" ("GrowerNumberSnapshot");
CREATE UNIQUE INDEX "IX_OutsideWarehouseTransfers_OperationKey" ON "OutsideWarehouseTransfers" ("OperationKey");
CREATE INDEX "IX_OutsideWarehouseTransfers_OutsideWarehouseId" ON "OutsideWarehouseTransfers" ("OutsideWarehouseId");
CREATE INDEX "IX_OutsideWarehouseTransfers_ReceiptId" ON "OutsideWarehouseTransfers" ("ReceiptId");
CREATE UNIQUE INDEX "IX_OutsideWarehouseTransfers_ReversalOperationKey" ON "OutsideWarehouseTransfers" ("ReversalOperationKey") WHERE "ReversalOperationKey" IS NOT NULL;
CREATE INDEX "IX_OutsideWarehouseTransfers_ReversedByUserId" ON "OutsideWarehouseTransfers" ("ReversedByUserId");
CREATE INDEX "IX_OutsideWarehouseTransfers_SourceInventoryAdjustmentId" ON "OutsideWarehouseTransfers" ("SourceInventoryAdjustmentId");
CREATE INDEX "IX_OutsideWarehouseTransfers_SourceRoomId" ON "OutsideWarehouseTransfers" ("SourceRoomId");
CREATE INDEX "IX_OutsideWarehouseTransfers_SourceWarehouseId_SourceRoomId_TransferredAt" ON "OutsideWarehouseTransfers" ("SourceWarehouseId", "SourceRoomId", "TransferredAt");
CREATE INDEX "IX_OutsideWarehouseTransfers_TransferredAt_OutsideWarehouseId" ON "OutsideWarehouseTransfers" ("TransferredAt", "OutsideWarehouseId");

CREATE INDEX "IX_InterCrewTransfers_DestinationCustodyGroup_Status_LoadedAt" ON "InterCrewTransfers" ("DestinationCustodyGroup", "Status", "LoadedAt");
CREATE INDEX "IX_InterCrewTransfers_DestinationRoomId" ON "InterCrewTransfers" ("DestinationRoomId");
CREATE INDEX "IX_InterCrewTransfers_DestinationWarehouseId" ON "InterCrewTransfers" ("DestinationWarehouseId");
CREATE INDEX "IX_InterCrewTransfers_FruitProfileId" ON "InterCrewTransfers" ("FruitProfileId");
CREATE INDEX "IX_InterCrewTransfers_LoadedByUserId" ON "InterCrewTransfers" ("LoadedByUserId");
CREATE UNIQUE INDEX "IX_InterCrewTransfers_OperationKey" ON "InterCrewTransfers" ("OperationKey");
CREATE INDEX "IX_InterCrewTransfers_ReceiptId" ON "InterCrewTransfers" ("ReceiptId");
CREATE INDEX "IX_InterCrewTransfers_ReceivedByUserId" ON "InterCrewTransfers" ("ReceivedByUserId");
CREATE UNIQUE INDEX "IX_InterCrewTransfers_ReceiveOperationKey" ON "InterCrewTransfers" ("ReceiveOperationKey") WHERE "ReceiveOperationKey" IS NOT NULL;
CREATE UNIQUE INDEX "IX_InterCrewTransfers_ReversalOperationKey" ON "InterCrewTransfers" ("ReversalOperationKey") WHERE "ReversalOperationKey" IS NOT NULL;
CREATE INDEX "IX_InterCrewTransfers_ReversedByUserId" ON "InterCrewTransfers" ("ReversedByUserId");
CREATE INDEX "IX_InterCrewTransfers_ReviewedByUserId" ON "InterCrewTransfers" ("ReviewedByUserId");
CREATE UNIQUE INDEX "IX_InterCrewTransfers_ReviewOperationKey" ON "InterCrewTransfers" ("ReviewOperationKey") WHERE "ReviewOperationKey" IS NOT NULL;
CREATE INDEX "IX_InterCrewTransfers_SourceInventoryAdjustmentId" ON "InterCrewTransfers" ("SourceInventoryAdjustmentId");
CREATE INDEX "IX_InterCrewTransfers_SourceRoomId_LoadedAt" ON "InterCrewTransfers" ("SourceRoomId", "LoadedAt");
CREATE INDEX "IX_InterCrewTransfers_SourceWarehouseId" ON "InterCrewTransfers" ("SourceWarehouseId");

ALTER TABLE "RoomInventoryAdjustments" ADD CONSTRAINT "FK_RoomInventoryAdjustments_OutsideWarehouseTransfers_OutsideWarehouseTransferId" FOREIGN KEY ("OutsideWarehouseTransferId") REFERENCES "OutsideWarehouseTransfers" ("Id") ON DELETE RESTRICT;
ALTER TABLE "TreatmentLineageMovements" ADD CONSTRAINT "FK_TreatmentLineageMovements_OutsideWarehouseTransfers_OutsideWarehouseTransferId" FOREIGN KEY ("OutsideWarehouseTransferId") REFERENCES "OutsideWarehouseTransfers" ("Id") ON DELETE RESTRICT;
ALTER TABLE "RoomInventoryAdjustments" ADD CONSTRAINT "FK_RoomInventoryAdjustments_InterCrewTransfers_InterCrewTransferId" FOREIGN KEY ("InterCrewTransferId") REFERENCES "InterCrewTransfers" ("Id") ON DELETE RESTRICT;
ALTER TABLE "TreatmentLineageMovements" ADD CONSTRAINT "FK_TreatmentLineageMovements_InterCrewTransfers_InterCrewTransferId" FOREIGN KEY ("InterCrewTransferId") REFERENCES "InterCrewTransfers" ("Id") ON DELETE RESTRICT;
\else
\echo 'Transfer Custody Workflow schema is already complete and exact; no DDL will be applied.'
\endif

DO $postcheck$
BEGIN
    IF to_regclass(format('%I.%I', current_schema(), 'OutsideWarehouses')) IS NULL
       OR to_regclass(format('%I.%I', current_schema(), 'OutsideWarehouseTransfers')) IS NULL
       OR to_regclass(format('%I.%I', current_schema(), 'InterCrewTransfers')) IS NULL THEN
        RAISE EXCEPTION 'Transfer Custody Workflow tables are missing after apply';
    END IF;
    IF current_setting('cropqc.test_force_transfer_custody_failure', true)='on' THEN
        RAISE EXCEPTION 'Forced Transfer Custody Workflow compatibility failure for rollback regression';
    END IF;
END $postcheck$;
COMMIT;
\ir verify-transfer-custody-workflow.sql
