\set ON_ERROR_STOP on
\ir verify-projection-actual-run-separation.sql

START TRANSACTION;
SET LOCAL lock_timeout = '15s';
SET LOCAL statement_timeout = '10min';
SELECT pg_advisory_xact_lock(hashtextextended('CropQc:20260804052104_AddFacilityRunReporting', 0));

DO $precheck$
DECLARE
    missing_base text;
    target_recorded boolean;
    existing_target_count integer;
BEGIN
    SELECT string_agg(expected.name, ', ' ORDER BY expected.name)
    INTO missing_base
    FROM (VALUES
        ('Users'), ('Warehouses'), ('ActualRuns'), ('ActualRunOverrideRequests'), ('BinsRunEntries')
    ) AS expected(name)
    WHERE to_regclass(format('%I.%I', current_schema(), expected.name)) IS NULL;
    IF missing_base IS NOT NULL THEN
        RAISE EXCEPTION 'Required base table(s) are missing: %. Transaction rolled back.', missing_base;
    END IF;

    SELECT EXISTS (
        SELECT 1 FROM "__EFMigrationsHistory"
        WHERE "MigrationId"='20260804052104_AddFacilityRunReporting'
    ) INTO target_recorded;

    SELECT
        (CASE WHEN to_regclass(format('%I.%I', current_schema(), 'UserEmploymentHistory')) IS NULL THEN 0 ELSE 1 END)
        + (SELECT COUNT(*) FROM information_schema.columns
           WHERE table_schema=current_schema()
             AND ((table_name='Users' AND column_name IN ('EmploymentEffectiveAt','EmploymentFacility','EmploymentUpdatedAt','EmploymentUpdatedByUserId'))
               OR (table_name='ActualRuns' AND column_name IN ('RunFacilityAssignedAt','RunFacilityAssignedByUserId','RunFacilityAssignmentSource','RunFacilityCodeSnapshot','RunFacilityWarehouseId'))
               OR (table_name='ActualRunOverrideRequests' AND column_name IN ('RunFacilityAssignmentSource','RunFacilityCodeSnapshot','RunFacilityWarehouseId'))
               OR (table_name='BinsRunEntries' AND column_name IN ('GrowerNumberSnapshot','IsOrganicSnapshot','ProductionTypeSnapshot','ReportingCropYearSnapshot','ReportingFacilityAssignedAt','ReportingFacilityAssignedByUserId','ReportingFacilityAssignmentSource','ReportingFacilityCodeSnapshot','ReportingFacilityWarehouseId','ReportingFruitProfileIdSnapshot','ReportingVarietyCodeSnapshot'))))
    INTO existing_target_count;

    IF target_recorded AND existing_target_count <> 24 THEN
        RAISE EXCEPTION 'Migration history records facility reporting but the target table/column set is incomplete. Transaction rolled back.';
    END IF;
    IF NOT target_recorded AND existing_target_count <> 0 THEN
        RAISE EXCEPTION 'Unexpected partial facility-reporting schema detected (% of 24 target table/columns). Transaction rolled back.', existing_target_count;
    END IF;
END $precheck$;

SELECT EXISTS (
    SELECT 1 FROM "__EFMigrationsHistory"
    WHERE "MigrationId"='20260804052104_AddFacilityRunReporting'
) AS migration_already_applied \gset

\if :migration_already_applied
\echo 'Facility reporting schema is already recorded; verifying exact object state without mutation.'
\else
ALTER TABLE "Users" ADD "EmploymentEffectiveAt" timestamp with time zone;
ALTER TABLE "Users" ADD "EmploymentFacility" character varying(25) NOT NULL DEFAULT 'Unassigned';
ALTER TABLE "Users" ADD "EmploymentUpdatedAt" timestamp with time zone;
ALTER TABLE "Users" ADD "EmploymentUpdatedByUserId" integer;

ALTER TABLE "BinsRunEntries" ADD "GrowerNumberSnapshot" character varying(50);
ALTER TABLE "BinsRunEntries" ADD "IsOrganicSnapshot" boolean;
ALTER TABLE "BinsRunEntries" ADD "ProductionTypeSnapshot" character varying(50);
ALTER TABLE "BinsRunEntries" ADD "ReportingCropYearSnapshot" integer;
ALTER TABLE "BinsRunEntries" ADD "ReportingFacilityAssignedAt" timestamp with time zone;
ALTER TABLE "BinsRunEntries" ADD "ReportingFacilityAssignedByUserId" integer;
ALTER TABLE "BinsRunEntries" ADD "ReportingFacilityAssignmentSource" character varying(50);
ALTER TABLE "BinsRunEntries" ADD "ReportingFacilityCodeSnapshot" character varying(25);
ALTER TABLE "BinsRunEntries" ADD "ReportingFacilityWarehouseId" integer;
ALTER TABLE "BinsRunEntries" ADD "ReportingFruitProfileIdSnapshot" integer;
ALTER TABLE "BinsRunEntries" ADD "ReportingVarietyCodeSnapshot" character varying(100);

ALTER TABLE "ActualRuns" ADD "RunFacilityAssignedAt" timestamp with time zone;
ALTER TABLE "ActualRuns" ADD "RunFacilityAssignedByUserId" integer;
ALTER TABLE "ActualRuns" ADD "RunFacilityAssignmentSource" character varying(50);
ALTER TABLE "ActualRuns" ADD "RunFacilityCodeSnapshot" character varying(25);
ALTER TABLE "ActualRuns" ADD "RunFacilityWarehouseId" integer;

ALTER TABLE "ActualRunOverrideRequests" ADD "RunFacilityAssignmentSource" character varying(50);
ALTER TABLE "ActualRunOverrideRequests" ADD "RunFacilityCodeSnapshot" character varying(25);
ALTER TABLE "ActualRunOverrideRequests" ADD "RunFacilityWarehouseId" integer;

CREATE TABLE "UserEmploymentHistory" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "PreviousEmploymentFacility" character varying(25) NOT NULL,
    "EmploymentFacility" character varying(25) NOT NULL,
    "EffectiveAt" timestamp with time zone NOT NULL,
    "ChangedByUserId" integer,
    "ChangedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_UserEmploymentHistory" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserEmploymentHistory_Users_ChangedByUserId" FOREIGN KEY ("ChangedByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_UserEmploymentHistory_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Users_EmploymentFacility" ON "Users" ("EmploymentFacility");
CREATE INDEX "IX_Users_EmploymentUpdatedByUserId" ON "Users" ("EmploymentUpdatedByUserId");
CREATE INDEX "IX_BinsRunEntries_ReportingFacilityAssignedByUserId" ON "BinsRunEntries" ("ReportingFacilityAssignedByUserId");
CREATE INDEX "IX_BinsRunEntries_ReportingFacilityWarehouseId_ReportingCropYearSnapshot_RunAt" ON "BinsRunEntries" ("ReportingFacilityWarehouseId", "ReportingCropYearSnapshot", "RunAt");
CREATE INDEX "IX_ActualRuns_RunFacilityAssignedByUserId" ON "ActualRuns" ("RunFacilityAssignedByUserId");
CREATE INDEX "IX_ActualRuns_RunFacilityWarehouseId_Status_RunAt" ON "ActualRuns" ("RunFacilityWarehouseId", "Status", "RunAt");
CREATE INDEX "IX_ActualRunOverrideRequests_RunFacilityWarehouseId" ON "ActualRunOverrideRequests" ("RunFacilityWarehouseId");
CREATE INDEX "IX_UserEmploymentHistory_ChangedByUserId" ON "UserEmploymentHistory" ("ChangedByUserId");
CREATE INDEX "IX_UserEmploymentHistory_UserId_ChangedAt" ON "UserEmploymentHistory" ("UserId", "ChangedAt");

ALTER TABLE "ActualRunOverrideRequests" ADD CONSTRAINT "FK_ActualRunOverrideRequests_Warehouses_RunFacilityWarehouseId" FOREIGN KEY ("RunFacilityWarehouseId") REFERENCES "Warehouses" ("Id") ON DELETE RESTRICT;
ALTER TABLE "ActualRuns" ADD CONSTRAINT "FK_ActualRuns_Users_RunFacilityAssignedByUserId" FOREIGN KEY ("RunFacilityAssignedByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL;
ALTER TABLE "ActualRuns" ADD CONSTRAINT "FK_ActualRuns_Warehouses_RunFacilityWarehouseId" FOREIGN KEY ("RunFacilityWarehouseId") REFERENCES "Warehouses" ("Id") ON DELETE RESTRICT;
ALTER TABLE "BinsRunEntries" ADD CONSTRAINT "FK_BinsRunEntries_Users_ReportingFacilityAssignedByUserId" FOREIGN KEY ("ReportingFacilityAssignedByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL;
ALTER TABLE "BinsRunEntries" ADD CONSTRAINT "FK_BinsRunEntries_Warehouses_ReportingFacilityWarehouseId" FOREIGN KEY ("ReportingFacilityWarehouseId") REFERENCES "Warehouses" ("Id") ON DELETE RESTRICT;
ALTER TABLE "Users" ADD CONSTRAINT "FK_Users_Users_EmploymentUpdatedByUserId" FOREIGN KEY ("EmploymentUpdatedByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260804052104_AddFacilityRunReporting', '9.0.9');
\endif

COMMIT;
\ir verify-facility-run-reporting.sql
