\set ON_ERROR_STOP on

-- Compatibility update for PostgreSQL databases originally created with EnsureCreated.
-- Requires explicit production database authorization. This script intentionally does
-- not create or modify __EFMigrationsHistory and never deletes historical data.

begin;

do $$
declare
    duplicate_parent_keys bigint := 0;
    duplicate_active_recipients bigint := 0;
begin
    if to_regclass(format('%I.%I', current_schema(), 'Receipts')) is null
       or to_regclass(format('%I.%I', current_schema(), 'CanonicalOrchardBlocks')) is null
       or to_regclass(format('%I.%I', current_schema(), 'QcSummaryEmailLogs')) is null then
        raise exception 'Required pre-PR Crop QC tables are missing; no changes were applied.';
    end if;

    if exists (
        select 1
        from "CanonicalOrchardBlocks"
        where "NormalizedOrchardKey" is null or btrim("NormalizedOrchardKey") = '') then
        raise exception 'Canonical orchard blocks contain blank normalized orchard keys; no changes were applied.';
    end if;

    if to_regclass(format('%I.%I', current_schema(), 'CanonicalOrchards')) is not null then
        execute 'select count(*) from (select "NormalizedOrchardKey" from "CanonicalOrchards" group by "NormalizedOrchardKey" having count(*) > 1) duplicates'
            into duplicate_parent_keys;
        if duplicate_parent_keys > 0 then
            raise exception 'Canonical orchards contain duplicate normalized keys; no changes were applied.';
        end if;
    end if;

    if to_regclass(format('%I.%I', current_schema(), 'OrchardReportRecipients')) is not null then
        execute 'select count(*) from (select "CanonicalOrchardId", "NormalizedEmailAddress" from "OrchardReportRecipients" where not "IsDeleted" group by "CanonicalOrchardId", "NormalizedEmailAddress" having count(*) > 1) duplicates'
            into duplicate_active_recipients;
        if duplicate_active_recipients > 0 then
            raise exception 'Active orchard recipients contain duplicate normalized values; no changes were applied.';
        end if;
    end if;
end $$;

lock table "CanonicalOrchardBlocks" in share row exclusive mode;

alter table "Receipts"
    add column if not exists "CanonicalOrchardBlockId" integer null;

alter table "CanonicalOrchardBlocks"
    add column if not exists "CanonicalOrchardId" integer null;

alter table "QcSummaryEmailLogs"
    alter column "ToAddress" type character varying(2000);

create table if not exists "CanonicalOrchards" (
    "Id" integer generated by default as identity,
    "OrchardName" character varying(200) not null,
    "NormalizedOrchardKey" character varying(200) not null,
    "IsActive" boolean not null,
    "CreatedAt" timestamp with time zone not null,
    "UpdatedAt" timestamp with time zone not null,
    constraint "PK_CanonicalOrchards" primary key ("Id")
);

create unique index if not exists "IX_CanonicalOrchards_NormalizedOrchardKey"
    on "CanonicalOrchards" ("NormalizedOrchardKey");

insert into "CanonicalOrchards" (
    "OrchardName", "NormalizedOrchardKey", "IsActive", "CreatedAt", "UpdatedAt")
select min(block."OrchardName"),
       block."NormalizedOrchardKey",
       bool_or(block."IsActive"),
       min(block."CreatedAt"),
       max(block."UpdatedAt")
from "CanonicalOrchardBlocks" as block
where not exists (
    select 1
    from "CanonicalOrchards" as orchard
    where orchard."NormalizedOrchardKey" = block."NormalizedOrchardKey")
group by block."NormalizedOrchardKey";

update "CanonicalOrchardBlocks" as block
set "CanonicalOrchardId" = orchard."Id"
from "CanonicalOrchards" as orchard
where orchard."NormalizedOrchardKey" = block."NormalizedOrchardKey"
  and block."CanonicalOrchardId" is distinct from orchard."Id";

do $$
begin
    if exists (select 1 from "CanonicalOrchardBlocks" where "CanonicalOrchardId" is null) then
        raise exception 'Canonical orchard backfill did not resolve every block; no changes were applied.';
    end if;
end $$;

alter table "CanonicalOrchardBlocks"
    alter column "CanonicalOrchardId" set not null;

create table if not exists "OrchardReportRecipients" (
    "Id" integer generated by default as identity,
    "CanonicalOrchardId" integer not null,
    "EmailAddress" character varying(320) not null,
    "NormalizedEmailAddress" character varying(320) not null,
    "IsActive" boolean not null,
    "IsDeleted" boolean not null,
    "CreatedAt" timestamp with time zone not null,
    "CreatedByUserId" integer null,
    "UpdatedAt" timestamp with time zone not null,
    "UpdatedByUserId" integer null,
    "DeletedAt" timestamp with time zone null,
    "DeletedByUserId" integer null,
    constraint "PK_OrchardReportRecipients" primary key ("Id")
);

create index if not exists "IX_Receipts_CanonicalOrchardBlockId"
    on "Receipts" ("CanonicalOrchardBlockId");
create index if not exists "IX_CanonicalOrchardBlocks_CanonicalOrchardId"
    on "CanonicalOrchardBlocks" ("CanonicalOrchardId");
create index if not exists "IX_OrchardReportRecipients_CanonicalOrchardId_IsActive_IsDeleted"
    on "OrchardReportRecipients" ("CanonicalOrchardId", "IsActive", "IsDeleted");
create unique index if not exists "IX_OrchardReportRecipients_CanonicalOrchardId_NormalizedEmailAddress"
    on "OrchardReportRecipients" ("CanonicalOrchardId", "NormalizedEmailAddress")
    where "IsDeleted" = false;
create index if not exists "IX_OrchardReportRecipients_CreatedByUserId"
    on "OrchardReportRecipients" ("CreatedByUserId");
create index if not exists "IX_OrchardReportRecipients_DeletedByUserId"
    on "OrchardReportRecipients" ("DeletedByUserId");
create index if not exists "IX_OrchardReportRecipients_UpdatedByUserId"
    on "OrchardReportRecipients" ("UpdatedByUserId");

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conrelid = '"CanonicalOrchardBlocks"'::regclass
          and conname = left('FK_CanonicalOrchardBlocks_CanonicalOrchards_CanonicalOrchardId', 63)) then
        alter table "CanonicalOrchardBlocks"
            add constraint "FK_CanonicalOrchardBlocks_CanonicalOrchards_CanonicalOrchardId"
            foreign key ("CanonicalOrchardId") references "CanonicalOrchards" ("Id") on delete restrict;
    end if;

    if not exists (
        select 1 from pg_constraint
        where conrelid = '"Receipts"'::regclass
          and conname = left('FK_Receipts_CanonicalOrchardBlocks_CanonicalOrchardBlockId', 63)) then
        alter table "Receipts"
            add constraint "FK_Receipts_CanonicalOrchardBlocks_CanonicalOrchardBlockId"
            foreign key ("CanonicalOrchardBlockId") references "CanonicalOrchardBlocks" ("Id") on delete set null;
    end if;

    if not exists (
        select 1 from pg_constraint
        where conrelid = '"OrchardReportRecipients"'::regclass
          and conname = left('FK_OrchardReportRecipients_CanonicalOrchards_CanonicalOrchardId', 63)) then
        alter table "OrchardReportRecipients"
            add constraint "FK_OrchardReportRecipients_CanonicalOrchards_CanonicalOrchardId"
            foreign key ("CanonicalOrchardId") references "CanonicalOrchards" ("Id") on delete restrict;
    end if;

    if not exists (
        select 1 from pg_constraint
        where conrelid = '"OrchardReportRecipients"'::regclass
          and conname = left('FK_OrchardReportRecipients_Users_CreatedByUserId', 63)) then
        alter table "OrchardReportRecipients"
            add constraint "FK_OrchardReportRecipients_Users_CreatedByUserId"
            foreign key ("CreatedByUserId") references "Users" ("Id") on delete set null;
    end if;

    if not exists (
        select 1 from pg_constraint
        where conrelid = '"OrchardReportRecipients"'::regclass
          and conname = left('FK_OrchardReportRecipients_Users_DeletedByUserId', 63)) then
        alter table "OrchardReportRecipients"
            add constraint "FK_OrchardReportRecipients_Users_DeletedByUserId"
            foreign key ("DeletedByUserId") references "Users" ("Id") on delete set null;
    end if;

    if not exists (
        select 1 from pg_constraint
        where conrelid = '"OrchardReportRecipients"'::regclass
          and conname = left('FK_OrchardReportRecipients_Users_UpdatedByUserId', 63)) then
        alter table "OrchardReportRecipients"
            add constraint "FK_OrchardReportRecipients_Users_UpdatedByUserId"
            foreign key ("UpdatedByUserId") references "Users" ("Id") on delete set null;
    end if;
end $$;

commit;
