START TRANSACTION;

\set ON_ERROR_STOP on
set local lock_timeout = '15s';
set local statement_timeout = '10min';
select pg_advisory_xact_lock(hashtextextended(
    'CropQc:20260731014107_SeparatePlanningProjectionsFromActualRuns', 0));

DO $PRECHECK$
DECLARE
    missing_base text;
    migration_recorded boolean;
    target_objects_complete boolean;
BEGIN
    SELECT string_agg(expected.name, ', ' ORDER BY expected.name)
    INTO missing_base
    FROM (VALUES
        ('ActualRuns'),
        ('ActualRunRevisions'),
        ('BinsRunEntries'),
        ('PackoutRuns'),
        ('QcSamples'),
        ('Users')
    ) expected(name)
    WHERE to_regclass(format('%I.%I', current_schema(), expected.name)) IS NULL;

    IF missing_base IS NOT NULL THEN
        RAISE EXCEPTION 'Required pre-existing table(s) are missing: %. Transaction rolled back.', missing_base;
    END IF;

    SELECT EXISTS (
        SELECT 1 FROM "__EFMigrationsHistory"
        WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns'
    ) INTO migration_recorded;

    SELECT to_regclass(format('%I.%I', current_schema(), 'RunExpectations')) IS NOT NULL
       AND to_regclass(format('%I.%I', current_schema(), 'RunExpectationSources')) IS NOT NULL
       AND to_regclass(format('%I.%I', current_schema(), 'PackoutSourceAllocations')) IS NOT NULL
       AND EXISTS (
           SELECT 1 FROM information_schema.columns
           WHERE table_schema = current_schema()
             AND table_name = 'PackoutRuns'
             AND column_name = 'ActualRunId')
       AND EXISTS (
           SELECT 1 FROM information_schema.columns
           WHERE table_schema = current_schema()
             AND table_name = 'PackoutRuns'
             AND column_name = 'RunExpectationId')
    INTO target_objects_complete;

    IF migration_recorded AND NOT target_objects_complete THEN
        RAISE EXCEPTION 'EF migration history records the target migration but required objects are missing. Manual review is required; transaction rolled back.';
    END IF;
END $PRECHECK$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    ALTER TABLE "PackoutRuns" ALTER COLUMN "RunProjectionId" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    ALTER TABLE "PackoutRuns" ADD COLUMN IF NOT EXISTS "ActualRunId" bigint;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    ALTER TABLE "PackoutRuns" ADD COLUMN IF NOT EXISTS "RunExpectationId" bigint;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE TABLE IF NOT EXISTS "RunExpectations" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ActualRunId" bigint NOT NULL,
        "ActualRunRevisionId" bigint NOT NULL,
        "RevisionNumber" integer NOT NULL,
        "FacilityWarehouseId" integer NOT NULL,
        "FacilitySnapshot" character varying(50) NOT NULL,
        "RunAtSnapshot" timestamp with time zone NOT NULL,
        "TotalBins" integer NOT NULL,
        "GrossPounds" numeric(18,4) NOT NULL,
        "ExpectedPackoutPercent" numeric(8,4) NOT NULL,
        "ExpectedPackedPounds" numeric(18,4) NOT NULL,
        "ExpectedPackedBoxes" numeric(18,4) NOT NULL,
        "ExpectedWholeBoxes" integer NOT NULL,
        "ExpectedCullPounds" numeric(18,4) NOT NULL,
        "ExpectedJuicePounds" numeric(18,4) NOT NULL,
        "ExpectedPeelerPounds" numeric(18,4) NOT NULL,
        "ExpectedWastePounds" numeric(18,4) NOT NULL,
        "ConfidencePercent" numeric(8,4) NOT NULL,
        "SizeDistributionSnapshotJson" text NOT NULL,
        "GradeDistributionSnapshotJson" text NOT NULL,
        "ConfigurationSnapshotJson" text NOT NULL,
        "CalculationVersion" character varying(75) NOT NULL,
        "CalculatedAt" timestamp with time zone NOT NULL,
        "CreatedByUserId" integer,
        CONSTRAINT "PK_RunExpectations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RunExpectations_ActualRunRevisions_ActualRunRevisionId" FOREIGN KEY ("ActualRunRevisionId") REFERENCES "ActualRunRevisions" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_RunExpectations_ActualRuns_ActualRunId" FOREIGN KEY ("ActualRunId") REFERENCES "ActualRuns" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_RunExpectations_Users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE TABLE IF NOT EXISTS "RunExpectationSources" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "RunExpectationId" bigint NOT NULL,
        "BinsRunEntryId" bigint NOT NULL,
        "WarehouseId" integer NOT NULL,
        "RoomId" integer NOT NULL,
        "FacilitySnapshot" character varying(50) NOT NULL,
        "RoomSnapshot" character varying(100) NOT NULL,
        "CropYearSnapshot" integer,
        "GrowerLotId" integer,
        "FruitProfileId" integer,
        "GrowerSnapshot" character varying(200) NOT NULL,
        "LotSnapshot" character varying(100) NOT NULL,
        "VarietySnapshot" character varying(100) NOT NULL,
        "ProductionTypeSnapshot" character varying(50) NOT NULL,
        "IsOrganicSnapshot" boolean NOT NULL,
        "BinsContributed" integer NOT NULL,
        "ContributionPercent" numeric(9,6) NOT NULL,
        "QcSampleId" bigint,
        "QcSampleTakenAtSnapshot" timestamp with time zone,
        "QcFruitCountSnapshot" integer NOT NULL,
        "QcMeasurementSnapshotJson" text NOT NULL,
        "SizeDistributionSnapshotJson" text NOT NULL,
        "GradeDistributionSnapshotJson" text NOT NULL,
        "GrossPounds" numeric(18,4) NOT NULL,
        "ExpectedPackedPounds" numeric(18,4) NOT NULL,
        "ExpectedWholeBoxes" integer NOT NULL,
        "ExpectedCullPounds" numeric(18,4) NOT NULL,
        "ConfidencePercent" numeric(8,4) NOT NULL,
        "WarningSnapshot" character varying(1000),
        CONSTRAINT "PK_RunExpectationSources" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RunExpectationSources_BinsRunEntries_BinsRunEntryId" FOREIGN KEY ("BinsRunEntryId") REFERENCES "BinsRunEntries" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_RunExpectationSources_QcSamples_QcSampleId" FOREIGN KEY ("QcSampleId") REFERENCES "QcSamples" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_RunExpectationSources_RunExpectations_RunExpectationId" FOREIGN KEY ("RunExpectationId") REFERENCES "RunExpectations" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE TABLE IF NOT EXISTS "PackoutSourceAllocations" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "PackoutRunId" bigint NOT NULL,
        "RunExpectationSourceId" bigint NOT NULL,
        "BinsContributed" integer NOT NULL,
        "ContributionPercent" numeric(9,6) NOT NULL,
        "AllocatedPackedPounds" numeric(18,6) NOT NULL,
        "AllocatedWholeBoxes" integer NOT NULL,
        "AllocatedResidualPounds" numeric(18,6) NOT NULL,
        "AllocatedJuicePounds" numeric(18,6) NOT NULL,
        "AllocatedPeelerPounds" numeric(18,6) NOT NULL,
        "AllocatedWastePounds" numeric(18,6) NOT NULL,
        "PackCodeAllocationJson" text NOT NULL,
        "SizeAllocationJson" text NOT NULL,
        "GradeAllocationJson" text NOT NULL,
        "AllocationVersion" character varying(75) NOT NULL,
        "CalculatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_PackoutSourceAllocations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PackoutSourceAllocations_PackoutRuns_PackoutRunId" FOREIGN KEY ("PackoutRunId") REFERENCES "PackoutRuns" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_PackoutSourceAllocations_RunExpectationSources_RunExpectationSourceId" FOREIGN KEY ("RunExpectationSourceId") REFERENCES "RunExpectationSources" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

-- Repair supported partial states. Missing required columns can be added to an
-- empty or otherwise compatible partial table; unsafe populated states fail
-- and roll back when NOT NULL or key constraints are applied.
ALTER TABLE "PackoutRuns"
    ADD COLUMN IF NOT EXISTS "ActualRunId" bigint,
    ADD COLUMN IF NOT EXISTS "RunExpectationId" bigint;

ALTER TABLE "PackoutRuns"
    ALTER COLUMN "RunProjectionId" DROP NOT NULL,
    ALTER COLUMN "ActualRunId" DROP NOT NULL,
    ALTER COLUMN "RunExpectationId" DROP NOT NULL;

ALTER TABLE "RunExpectations"
    ADD COLUMN IF NOT EXISTS "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN IF NOT EXISTS "ActualRunId" bigint,
    ADD COLUMN IF NOT EXISTS "ActualRunRevisionId" bigint,
    ADD COLUMN IF NOT EXISTS "RevisionNumber" integer,
    ADD COLUMN IF NOT EXISTS "FacilityWarehouseId" integer,
    ADD COLUMN IF NOT EXISTS "FacilitySnapshot" character varying(50),
    ADD COLUMN IF NOT EXISTS "RunAtSnapshot" timestamp with time zone,
    ADD COLUMN IF NOT EXISTS "TotalBins" integer,
    ADD COLUMN IF NOT EXISTS "GrossPounds" numeric(18,4),
    ADD COLUMN IF NOT EXISTS "ExpectedPackoutPercent" numeric(8,4),
    ADD COLUMN IF NOT EXISTS "ExpectedPackedPounds" numeric(18,4),
    ADD COLUMN IF NOT EXISTS "ExpectedPackedBoxes" numeric(18,4),
    ADD COLUMN IF NOT EXISTS "ExpectedWholeBoxes" integer,
    ADD COLUMN IF NOT EXISTS "ExpectedCullPounds" numeric(18,4),
    ADD COLUMN IF NOT EXISTS "ExpectedJuicePounds" numeric(18,4),
    ADD COLUMN IF NOT EXISTS "ExpectedPeelerPounds" numeric(18,4),
    ADD COLUMN IF NOT EXISTS "ExpectedWastePounds" numeric(18,4),
    ADD COLUMN IF NOT EXISTS "ConfidencePercent" numeric(8,4),
    ADD COLUMN IF NOT EXISTS "SizeDistributionSnapshotJson" text,
    ADD COLUMN IF NOT EXISTS "GradeDistributionSnapshotJson" text,
    ADD COLUMN IF NOT EXISTS "ConfigurationSnapshotJson" text,
    ADD COLUMN IF NOT EXISTS "CalculationVersion" character varying(75),
    ADD COLUMN IF NOT EXISTS "CalculatedAt" timestamp with time zone,
    ADD COLUMN IF NOT EXISTS "CreatedByUserId" integer;

ALTER TABLE "RunExpectations"
    ALTER COLUMN "Id" SET NOT NULL,
    ALTER COLUMN "ActualRunId" SET NOT NULL,
    ALTER COLUMN "ActualRunRevisionId" SET NOT NULL,
    ALTER COLUMN "RevisionNumber" SET NOT NULL,
    ALTER COLUMN "FacilityWarehouseId" SET NOT NULL,
    ALTER COLUMN "FacilitySnapshot" SET NOT NULL,
    ALTER COLUMN "RunAtSnapshot" SET NOT NULL,
    ALTER COLUMN "TotalBins" SET NOT NULL,
    ALTER COLUMN "GrossPounds" SET NOT NULL,
    ALTER COLUMN "ExpectedPackoutPercent" SET NOT NULL,
    ALTER COLUMN "ExpectedPackedPounds" SET NOT NULL,
    ALTER COLUMN "ExpectedPackedBoxes" SET NOT NULL,
    ALTER COLUMN "ExpectedWholeBoxes" SET NOT NULL,
    ALTER COLUMN "ExpectedCullPounds" SET NOT NULL,
    ALTER COLUMN "ExpectedJuicePounds" SET NOT NULL,
    ALTER COLUMN "ExpectedPeelerPounds" SET NOT NULL,
    ALTER COLUMN "ExpectedWastePounds" SET NOT NULL,
    ALTER COLUMN "ConfidencePercent" SET NOT NULL,
    ALTER COLUMN "SizeDistributionSnapshotJson" SET NOT NULL,
    ALTER COLUMN "GradeDistributionSnapshotJson" SET NOT NULL,
    ALTER COLUMN "ConfigurationSnapshotJson" SET NOT NULL,
    ALTER COLUMN "CalculationVersion" SET NOT NULL,
    ALTER COLUMN "CalculatedAt" SET NOT NULL,
    ALTER COLUMN "CreatedByUserId" DROP NOT NULL;

ALTER TABLE "RunExpectationSources"
    ADD COLUMN IF NOT EXISTS "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN IF NOT EXISTS "RunExpectationId" bigint,
    ADD COLUMN IF NOT EXISTS "BinsRunEntryId" bigint,
    ADD COLUMN IF NOT EXISTS "WarehouseId" integer,
    ADD COLUMN IF NOT EXISTS "RoomId" integer,
    ADD COLUMN IF NOT EXISTS "FacilitySnapshot" character varying(50),
    ADD COLUMN IF NOT EXISTS "RoomSnapshot" character varying(100),
    ADD COLUMN IF NOT EXISTS "CropYearSnapshot" integer,
    ADD COLUMN IF NOT EXISTS "GrowerLotId" integer,
    ADD COLUMN IF NOT EXISTS "FruitProfileId" integer,
    ADD COLUMN IF NOT EXISTS "GrowerSnapshot" character varying(200),
    ADD COLUMN IF NOT EXISTS "LotSnapshot" character varying(100),
    ADD COLUMN IF NOT EXISTS "VarietySnapshot" character varying(100),
    ADD COLUMN IF NOT EXISTS "ProductionTypeSnapshot" character varying(50),
    ADD COLUMN IF NOT EXISTS "IsOrganicSnapshot" boolean,
    ADD COLUMN IF NOT EXISTS "BinsContributed" integer,
    ADD COLUMN IF NOT EXISTS "ContributionPercent" numeric(9,6),
    ADD COLUMN IF NOT EXISTS "QcSampleId" bigint,
    ADD COLUMN IF NOT EXISTS "QcSampleTakenAtSnapshot" timestamp with time zone,
    ADD COLUMN IF NOT EXISTS "QcFruitCountSnapshot" integer,
    ADD COLUMN IF NOT EXISTS "QcMeasurementSnapshotJson" text,
    ADD COLUMN IF NOT EXISTS "SizeDistributionSnapshotJson" text,
    ADD COLUMN IF NOT EXISTS "GradeDistributionSnapshotJson" text,
    ADD COLUMN IF NOT EXISTS "GrossPounds" numeric(18,4),
    ADD COLUMN IF NOT EXISTS "ExpectedPackedPounds" numeric(18,4),
    ADD COLUMN IF NOT EXISTS "ExpectedWholeBoxes" integer,
    ADD COLUMN IF NOT EXISTS "ExpectedCullPounds" numeric(18,4),
    ADD COLUMN IF NOT EXISTS "ConfidencePercent" numeric(8,4),
    ADD COLUMN IF NOT EXISTS "WarningSnapshot" character varying(1000);

ALTER TABLE "RunExpectationSources"
    ALTER COLUMN "Id" SET NOT NULL,
    ALTER COLUMN "RunExpectationId" SET NOT NULL,
    ALTER COLUMN "BinsRunEntryId" SET NOT NULL,
    ALTER COLUMN "WarehouseId" SET NOT NULL,
    ALTER COLUMN "RoomId" SET NOT NULL,
    ALTER COLUMN "FacilitySnapshot" SET NOT NULL,
    ALTER COLUMN "RoomSnapshot" SET NOT NULL,
    ALTER COLUMN "CropYearSnapshot" DROP NOT NULL,
    ALTER COLUMN "GrowerLotId" DROP NOT NULL,
    ALTER COLUMN "FruitProfileId" DROP NOT NULL,
    ALTER COLUMN "GrowerSnapshot" SET NOT NULL,
    ALTER COLUMN "LotSnapshot" SET NOT NULL,
    ALTER COLUMN "VarietySnapshot" SET NOT NULL,
    ALTER COLUMN "ProductionTypeSnapshot" SET NOT NULL,
    ALTER COLUMN "IsOrganicSnapshot" SET NOT NULL,
    ALTER COLUMN "BinsContributed" SET NOT NULL,
    ALTER COLUMN "ContributionPercent" SET NOT NULL,
    ALTER COLUMN "QcSampleId" DROP NOT NULL,
    ALTER COLUMN "QcSampleTakenAtSnapshot" DROP NOT NULL,
    ALTER COLUMN "QcFruitCountSnapshot" SET NOT NULL,
    ALTER COLUMN "QcMeasurementSnapshotJson" SET NOT NULL,
    ALTER COLUMN "SizeDistributionSnapshotJson" SET NOT NULL,
    ALTER COLUMN "GradeDistributionSnapshotJson" SET NOT NULL,
    ALTER COLUMN "GrossPounds" SET NOT NULL,
    ALTER COLUMN "ExpectedPackedPounds" SET NOT NULL,
    ALTER COLUMN "ExpectedWholeBoxes" SET NOT NULL,
    ALTER COLUMN "ExpectedCullPounds" SET NOT NULL,
    ALTER COLUMN "ConfidencePercent" SET NOT NULL,
    ALTER COLUMN "WarningSnapshot" DROP NOT NULL;

ALTER TABLE "PackoutSourceAllocations"
    ADD COLUMN IF NOT EXISTS "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN IF NOT EXISTS "PackoutRunId" bigint,
    ADD COLUMN IF NOT EXISTS "RunExpectationSourceId" bigint,
    ADD COLUMN IF NOT EXISTS "BinsContributed" integer,
    ADD COLUMN IF NOT EXISTS "ContributionPercent" numeric(9,6),
    ADD COLUMN IF NOT EXISTS "AllocatedPackedPounds" numeric(18,6),
    ADD COLUMN IF NOT EXISTS "AllocatedWholeBoxes" integer,
    ADD COLUMN IF NOT EXISTS "AllocatedResidualPounds" numeric(18,6),
    ADD COLUMN IF NOT EXISTS "AllocatedJuicePounds" numeric(18,6),
    ADD COLUMN IF NOT EXISTS "AllocatedPeelerPounds" numeric(18,6),
    ADD COLUMN IF NOT EXISTS "AllocatedWastePounds" numeric(18,6),
    ADD COLUMN IF NOT EXISTS "PackCodeAllocationJson" text,
    ADD COLUMN IF NOT EXISTS "SizeAllocationJson" text,
    ADD COLUMN IF NOT EXISTS "GradeAllocationJson" text,
    ADD COLUMN IF NOT EXISTS "AllocationVersion" character varying(75),
    ADD COLUMN IF NOT EXISTS "CalculatedAt" timestamp with time zone;

ALTER TABLE "PackoutSourceAllocations"
    ALTER COLUMN "Id" SET NOT NULL,
    ALTER COLUMN "PackoutRunId" SET NOT NULL,
    ALTER COLUMN "RunExpectationSourceId" SET NOT NULL,
    ALTER COLUMN "BinsContributed" SET NOT NULL,
    ALTER COLUMN "ContributionPercent" SET NOT NULL,
    ALTER COLUMN "AllocatedPackedPounds" SET NOT NULL,
    ALTER COLUMN "AllocatedWholeBoxes" SET NOT NULL,
    ALTER COLUMN "AllocatedResidualPounds" SET NOT NULL,
    ALTER COLUMN "AllocatedJuicePounds" SET NOT NULL,
    ALTER COLUMN "AllocatedPeelerPounds" SET NOT NULL,
    ALTER COLUMN "AllocatedWastePounds" SET NOT NULL,
    ALTER COLUMN "PackCodeAllocationJson" SET NOT NULL,
    ALTER COLUMN "SizeAllocationJson" SET NOT NULL,
    ALTER COLUMN "GradeAllocationJson" SET NOT NULL,
    ALTER COLUMN "AllocationVersion" SET NOT NULL,
    ALTER COLUMN "CalculatedAt" SET NOT NULL;

DO $PRIMARY_KEYS$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'PK_RunExpectations' AND conrelid = '"RunExpectations"'::regclass AND contype = 'p') THEN
        ALTER TABLE "RunExpectations" ADD CONSTRAINT "PK_RunExpectations" PRIMARY KEY ("Id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'PK_RunExpectationSources' AND conrelid = '"RunExpectationSources"'::regclass AND contype = 'p') THEN
        ALTER TABLE "RunExpectationSources" ADD CONSTRAINT "PK_RunExpectationSources" PRIMARY KEY ("Id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'PK_PackoutSourceAllocations' AND conrelid = '"PackoutSourceAllocations"'::regclass AND contype = 'p') THEN
        ALTER TABLE "PackoutSourceAllocations" ADD CONSTRAINT "PK_PackoutSourceAllocations" PRIMARY KEY ("Id");
    END IF;
END $PRIMARY_KEYS$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE INDEX IF NOT EXISTS "IX_PackoutRuns_RunExpectationId" ON "PackoutRuns" ("RunExpectationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE UNIQUE INDEX IF NOT EXISTS "UX_PackoutRuns_ActualRunId" ON "PackoutRuns" ("ActualRunId") WHERE "ActualRunId" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE UNIQUE INDEX IF NOT EXISTS "IX_PackoutSourceAllocations_PackoutRunId_RunExpectationSourceId" ON "PackoutSourceAllocations" ("PackoutRunId", "RunExpectationSourceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE INDEX IF NOT EXISTS "IX_PackoutSourceAllocations_RunExpectationSourceId" ON "PackoutSourceAllocations" ("RunExpectationSourceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE UNIQUE INDEX IF NOT EXISTS "IX_RunExpectations_ActualRunId_RevisionNumber" ON "RunExpectations" ("ActualRunId", "RevisionNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE UNIQUE INDEX IF NOT EXISTS "IX_RunExpectations_ActualRunRevisionId" ON "RunExpectations" ("ActualRunRevisionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE INDEX IF NOT EXISTS "IX_RunExpectations_CreatedByUserId" ON "RunExpectations" ("CreatedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE INDEX IF NOT EXISTS "IX_RunExpectationSources_BinsRunEntryId" ON "RunExpectationSources" ("BinsRunEntryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE INDEX IF NOT EXISTS "IX_RunExpectationSources_QcSampleId" ON "RunExpectationSources" ("QcSampleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE UNIQUE INDEX IF NOT EXISTS "IX_RunExpectationSources_RunExpectationId_BinsRunEntryId" ON "RunExpectationSources" ("RunExpectationId", "BinsRunEntryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE INDEX IF NOT EXISTS "IX_RunExpectationSources_WarehouseId_RoomId_CropYearSnapshot_LotSnapshot_VarietySnapshot" ON "RunExpectationSources" ("WarehouseId", "RoomId", "CropYearSnapshot", "LotSnapshot", "VarietySnapshot");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'FK_PackoutRuns_ActualRuns_ActualRunId'
          AND conrelid = '"PackoutRuns"'::regclass
    ) THEN
        ALTER TABLE "PackoutRuns" ADD CONSTRAINT "FK_PackoutRuns_ActualRuns_ActualRunId" FOREIGN KEY ("ActualRunId") REFERENCES "ActualRuns" ("Id") ON DELETE RESTRICT;
    END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'FK_PackoutRuns_RunExpectations_RunExpectationId'
          AND conrelid = '"PackoutRuns"'::regclass
    ) THEN
        ALTER TABLE "PackoutRuns" ADD CONSTRAINT "FK_PackoutRuns_RunExpectations_RunExpectationId" FOREIGN KEY ("RunExpectationId") REFERENCES "RunExpectations" ("Id") ON DELETE RESTRICT;
    END IF;
    END IF;
END $EF$;

DO $RELATIONSHIPS$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_PackoutRuns_ActualRuns_ActualRunId' AND conrelid = '"PackoutRuns"'::regclass) THEN
        ALTER TABLE "PackoutRuns" ADD CONSTRAINT "FK_PackoutRuns_ActualRuns_ActualRunId" FOREIGN KEY ("ActualRunId") REFERENCES "ActualRuns" ("Id") ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_PackoutRuns_RunExpectations_RunExpectationId' AND conrelid = '"PackoutRuns"'::regclass) THEN
        ALTER TABLE "PackoutRuns" ADD CONSTRAINT "FK_PackoutRuns_RunExpectations_RunExpectationId" FOREIGN KEY ("RunExpectationId") REFERENCES "RunExpectations" ("Id") ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_RunExpectations_ActualRunRevisions_ActualRunRevisionId' AND conrelid = '"RunExpectations"'::regclass) THEN
        ALTER TABLE "RunExpectations" ADD CONSTRAINT "FK_RunExpectations_ActualRunRevisions_ActualRunRevisionId" FOREIGN KEY ("ActualRunRevisionId") REFERENCES "ActualRunRevisions" ("Id") ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_RunExpectations_ActualRuns_ActualRunId' AND conrelid = '"RunExpectations"'::regclass) THEN
        ALTER TABLE "RunExpectations" ADD CONSTRAINT "FK_RunExpectations_ActualRuns_ActualRunId" FOREIGN KEY ("ActualRunId") REFERENCES "ActualRuns" ("Id") ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_RunExpectations_Users_CreatedByUserId' AND conrelid = '"RunExpectations"'::regclass) THEN
        ALTER TABLE "RunExpectations" ADD CONSTRAINT "FK_RunExpectations_Users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_RunExpectationSources_BinsRunEntries_BinsRunEntryId' AND conrelid = '"RunExpectationSources"'::regclass) THEN
        ALTER TABLE "RunExpectationSources" ADD CONSTRAINT "FK_RunExpectationSources_BinsRunEntries_BinsRunEntryId" FOREIGN KEY ("BinsRunEntryId") REFERENCES "BinsRunEntries" ("Id") ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_RunExpectationSources_QcSamples_QcSampleId' AND conrelid = '"RunExpectationSources"'::regclass) THEN
        ALTER TABLE "RunExpectationSources" ADD CONSTRAINT "FK_RunExpectationSources_QcSamples_QcSampleId" FOREIGN KEY ("QcSampleId") REFERENCES "QcSamples" ("Id") ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_RunExpectationSources_RunExpectations_RunExpectationId' AND conrelid = '"RunExpectationSources"'::regclass) THEN
        ALTER TABLE "RunExpectationSources" ADD CONSTRAINT "FK_RunExpectationSources_RunExpectations_RunExpectationId" FOREIGN KEY ("RunExpectationId") REFERENCES "RunExpectations" ("Id") ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_PackoutSourceAllocations_PackoutRuns_PackoutRunId' AND conrelid = '"PackoutSourceAllocations"'::regclass) THEN
        ALTER TABLE "PackoutSourceAllocations" ADD CONSTRAINT "FK_PackoutSourceAllocations_PackoutRuns_PackoutRunId" FOREIGN KEY ("PackoutRunId") REFERENCES "PackoutRuns" ("Id") ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = left('FK_PackoutSourceAllocations_RunExpectationSources_RunExpectationSourceId', 63) AND conrelid = '"PackoutSourceAllocations"'::regclass) THEN
        ALTER TABLE "PackoutSourceAllocations" ADD CONSTRAINT "FK_PackoutSourceAllocations_RunExpectationSources_RunExpectationSourceId" FOREIGN KEY ("RunExpectationSourceId") REFERENCES "RunExpectationSources" ("Id") ON DELETE RESTRICT;
    END IF;
END $RELATIONSHIPS$;

CREATE INDEX IF NOT EXISTS "IX_PackoutRuns_RunExpectationId" ON "PackoutRuns" ("RunExpectationId");
CREATE UNIQUE INDEX IF NOT EXISTS "UX_PackoutRuns_ActualRunId" ON "PackoutRuns" ("ActualRunId") WHERE "ActualRunId" IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "IX_PackoutSourceAllocations_PackoutRunId_RunExpectationSourceId" ON "PackoutSourceAllocations" ("PackoutRunId", "RunExpectationSourceId");
CREATE INDEX IF NOT EXISTS "IX_PackoutSourceAllocations_RunExpectationSourceId" ON "PackoutSourceAllocations" ("RunExpectationSourceId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_RunExpectations_ActualRunId_RevisionNumber" ON "RunExpectations" ("ActualRunId", "RevisionNumber");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_RunExpectations_ActualRunRevisionId" ON "RunExpectations" ("ActualRunRevisionId");
CREATE INDEX IF NOT EXISTS "IX_RunExpectations_CreatedByUserId" ON "RunExpectations" ("CreatedByUserId");
CREATE INDEX IF NOT EXISTS "IX_RunExpectationSources_BinsRunEntryId" ON "RunExpectationSources" ("BinsRunEntryId");
CREATE INDEX IF NOT EXISTS "IX_RunExpectationSources_QcSampleId" ON "RunExpectationSources" ("QcSampleId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_RunExpectationSources_RunExpectationId_BinsRunEntryId" ON "RunExpectationSources" ("RunExpectationId", "BinsRunEntryId");
CREATE INDEX IF NOT EXISTS "IX_RunExpectationSources_WarehouseId_RoomId_CropYearSnapshot_LotSnapshot_VarietySnapshot" ON "RunExpectationSources" ("WarehouseId", "RoomId", "CropYearSnapshot", "LotSnapshot", "VarietySnapshot");

DO $POSTCHECK$
DECLARE
    missing text;
BEGIN
    SELECT string_agg(expected.display_name, ', ' ORDER BY expected.display_name)
    INTO missing
    FROM (VALUES
        ('RunExpectations table', 'RunExpectations', NULL::text, NULL::text),
        ('RunExpectationSources table', 'RunExpectationSources', NULL::text, NULL::text),
        ('PackoutSourceAllocations table', 'PackoutSourceAllocations', NULL::text, NULL::text),
        ('PackoutRuns.ActualRunId', 'PackoutRuns', 'ActualRunId', 'YES'),
        ('PackoutRuns.RunExpectationId', 'PackoutRuns', 'RunExpectationId', 'YES'),
        ('PackoutRuns.RunProjectionId', 'PackoutRuns', 'RunProjectionId', 'YES'),
        ('RunExpectations.Id', 'RunExpectations', 'Id', 'NO'),
        ('RunExpectations.ActualRunId', 'RunExpectations', 'ActualRunId', 'NO'),
        ('RunExpectations.ActualRunRevisionId', 'RunExpectations', 'ActualRunRevisionId', 'NO'),
        ('RunExpectations.RevisionNumber', 'RunExpectations', 'RevisionNumber', 'NO'),
        ('RunExpectations.FacilityWarehouseId', 'RunExpectations', 'FacilityWarehouseId', 'NO'),
        ('RunExpectations.FacilitySnapshot', 'RunExpectations', 'FacilitySnapshot', 'NO'),
        ('RunExpectations.RunAtSnapshot', 'RunExpectations', 'RunAtSnapshot', 'NO'),
        ('RunExpectations.TotalBins', 'RunExpectations', 'TotalBins', 'NO'),
        ('RunExpectations.GrossPounds', 'RunExpectations', 'GrossPounds', 'NO'),
        ('RunExpectations.ExpectedPackoutPercent', 'RunExpectations', 'ExpectedPackoutPercent', 'NO'),
        ('RunExpectations.ExpectedPackedPounds', 'RunExpectations', 'ExpectedPackedPounds', 'NO'),
        ('RunExpectations.ExpectedPackedBoxes', 'RunExpectations', 'ExpectedPackedBoxes', 'NO'),
        ('RunExpectations.ExpectedWholeBoxes', 'RunExpectations', 'ExpectedWholeBoxes', 'NO'),
        ('RunExpectations.ExpectedCullPounds', 'RunExpectations', 'ExpectedCullPounds', 'NO'),
        ('RunExpectations.ExpectedJuicePounds', 'RunExpectations', 'ExpectedJuicePounds', 'NO'),
        ('RunExpectations.ExpectedPeelerPounds', 'RunExpectations', 'ExpectedPeelerPounds', 'NO'),
        ('RunExpectations.ExpectedWastePounds', 'RunExpectations', 'ExpectedWastePounds', 'NO'),
        ('RunExpectations.ConfidencePercent', 'RunExpectations', 'ConfidencePercent', 'NO'),
        ('RunExpectations.SizeDistributionSnapshotJson', 'RunExpectations', 'SizeDistributionSnapshotJson', 'NO'),
        ('RunExpectations.GradeDistributionSnapshotJson', 'RunExpectations', 'GradeDistributionSnapshotJson', 'NO'),
        ('RunExpectations.ConfigurationSnapshotJson', 'RunExpectations', 'ConfigurationSnapshotJson', 'NO'),
        ('RunExpectations.CalculationVersion', 'RunExpectations', 'CalculationVersion', 'NO'),
        ('RunExpectations.CalculatedAt', 'RunExpectations', 'CalculatedAt', 'NO'),
        ('RunExpectations.CreatedByUserId', 'RunExpectations', 'CreatedByUserId', 'YES'),
        ('RunExpectationSources.Id', 'RunExpectationSources', 'Id', 'NO'),
        ('RunExpectationSources.RunExpectationId', 'RunExpectationSources', 'RunExpectationId', 'NO'),
        ('RunExpectationSources.BinsRunEntryId', 'RunExpectationSources', 'BinsRunEntryId', 'NO'),
        ('RunExpectationSources.WarehouseId', 'RunExpectationSources', 'WarehouseId', 'NO'),
        ('RunExpectationSources.RoomId', 'RunExpectationSources', 'RoomId', 'NO'),
        ('RunExpectationSources.FacilitySnapshot', 'RunExpectationSources', 'FacilitySnapshot', 'NO'),
        ('RunExpectationSources.RoomSnapshot', 'RunExpectationSources', 'RoomSnapshot', 'NO'),
        ('RunExpectationSources.CropYearSnapshot', 'RunExpectationSources', 'CropYearSnapshot', 'YES'),
        ('RunExpectationSources.GrowerLotId', 'RunExpectationSources', 'GrowerLotId', 'YES'),
        ('RunExpectationSources.FruitProfileId', 'RunExpectationSources', 'FruitProfileId', 'YES'),
        ('RunExpectationSources.GrowerSnapshot', 'RunExpectationSources', 'GrowerSnapshot', 'NO'),
        ('RunExpectationSources.LotSnapshot', 'RunExpectationSources', 'LotSnapshot', 'NO'),
        ('RunExpectationSources.VarietySnapshot', 'RunExpectationSources', 'VarietySnapshot', 'NO'),
        ('RunExpectationSources.ProductionTypeSnapshot', 'RunExpectationSources', 'ProductionTypeSnapshot', 'NO'),
        ('RunExpectationSources.IsOrganicSnapshot', 'RunExpectationSources', 'IsOrganicSnapshot', 'NO'),
        ('RunExpectationSources.BinsContributed', 'RunExpectationSources', 'BinsContributed', 'NO'),
        ('RunExpectationSources.ContributionPercent', 'RunExpectationSources', 'ContributionPercent', 'NO'),
        ('RunExpectationSources.QcSampleId', 'RunExpectationSources', 'QcSampleId', 'YES'),
        ('RunExpectationSources.QcSampleTakenAtSnapshot', 'RunExpectationSources', 'QcSampleTakenAtSnapshot', 'YES'),
        ('RunExpectationSources.QcFruitCountSnapshot', 'RunExpectationSources', 'QcFruitCountSnapshot', 'NO'),
        ('RunExpectationSources.QcMeasurementSnapshotJson', 'RunExpectationSources', 'QcMeasurementSnapshotJson', 'NO'),
        ('RunExpectationSources.SizeDistributionSnapshotJson', 'RunExpectationSources', 'SizeDistributionSnapshotJson', 'NO'),
        ('RunExpectationSources.GradeDistributionSnapshotJson', 'RunExpectationSources', 'GradeDistributionSnapshotJson', 'NO'),
        ('RunExpectationSources.GrossPounds', 'RunExpectationSources', 'GrossPounds', 'NO'),
        ('RunExpectationSources.ExpectedPackedPounds', 'RunExpectationSources', 'ExpectedPackedPounds', 'NO'),
        ('RunExpectationSources.ExpectedWholeBoxes', 'RunExpectationSources', 'ExpectedWholeBoxes', 'NO'),
        ('RunExpectationSources.ExpectedCullPounds', 'RunExpectationSources', 'ExpectedCullPounds', 'NO'),
        ('RunExpectationSources.ConfidencePercent', 'RunExpectationSources', 'ConfidencePercent', 'NO'),
        ('RunExpectationSources.WarningSnapshot', 'RunExpectationSources', 'WarningSnapshot', 'YES'),
        ('PackoutSourceAllocations.Id', 'PackoutSourceAllocations', 'Id', 'NO'),
        ('PackoutSourceAllocations.PackoutRunId', 'PackoutSourceAllocations', 'PackoutRunId', 'NO'),
        ('PackoutSourceAllocations.RunExpectationSourceId', 'PackoutSourceAllocations', 'RunExpectationSourceId', 'NO'),
        ('PackoutSourceAllocations.BinsContributed', 'PackoutSourceAllocations', 'BinsContributed', 'NO'),
        ('PackoutSourceAllocations.ContributionPercent', 'PackoutSourceAllocations', 'ContributionPercent', 'NO'),
        ('PackoutSourceAllocations.AllocatedPackedPounds', 'PackoutSourceAllocations', 'AllocatedPackedPounds', 'NO'),
        ('PackoutSourceAllocations.AllocatedWholeBoxes', 'PackoutSourceAllocations', 'AllocatedWholeBoxes', 'NO'),
        ('PackoutSourceAllocations.AllocatedResidualPounds', 'PackoutSourceAllocations', 'AllocatedResidualPounds', 'NO'),
        ('PackoutSourceAllocations.AllocatedJuicePounds', 'PackoutSourceAllocations', 'AllocatedJuicePounds', 'NO'),
        ('PackoutSourceAllocations.AllocatedPeelerPounds', 'PackoutSourceAllocations', 'AllocatedPeelerPounds', 'NO'),
        ('PackoutSourceAllocations.AllocatedWastePounds', 'PackoutSourceAllocations', 'AllocatedWastePounds', 'NO'),
        ('PackoutSourceAllocations.PackCodeAllocationJson', 'PackoutSourceAllocations', 'PackCodeAllocationJson', 'NO'),
        ('PackoutSourceAllocations.SizeAllocationJson', 'PackoutSourceAllocations', 'SizeAllocationJson', 'NO'),
        ('PackoutSourceAllocations.GradeAllocationJson', 'PackoutSourceAllocations', 'GradeAllocationJson', 'NO'),
        ('PackoutSourceAllocations.AllocationVersion', 'PackoutSourceAllocations', 'AllocationVersion', 'NO'),
        ('PackoutSourceAllocations.CalculatedAt', 'PackoutSourceAllocations', 'CalculatedAt', 'NO')
    ) expected(display_name, table_name, column_name, expected_nullable)
    WHERE (expected.column_name IS NULL
           AND to_regclass(format('%I.%I', current_schema(), expected.table_name)) IS NULL)
       OR (expected.column_name IS NOT NULL
           AND NOT EXISTS (
               SELECT 1 FROM information_schema.columns
               WHERE table_schema = current_schema()
                 AND table_name = expected.table_name
                 AND column_name = expected.column_name
                 AND is_nullable = expected.expected_nullable));

    IF missing IS NOT NULL THEN
        RAISE EXCEPTION 'Compatibility apply did not produce required object(s): %. Transaction rolled back.', missing;
    END IF;
END $POSTCHECK$;

DO $POSTCHECK_NAMED_OBJECTS$
DECLARE
    missing_indexes text;
    missing_constraints text;
    missing_primary_keys text;
BEGIN
    SELECT string_agg(expected.index_name, ', ' ORDER BY expected.index_name)
    INTO missing_indexes
    FROM (VALUES
        ('PackoutRuns', 'IX_PackoutRuns_RunExpectationId', false),
        ('PackoutRuns', 'UX_PackoutRuns_ActualRunId', true),
        ('PackoutSourceAllocations', 'IX_PackoutSourceAllocations_PackoutRunId_RunExpectationSourceId', true),
        ('PackoutSourceAllocations', 'IX_PackoutSourceAllocations_RunExpectationSourceId', false),
        ('RunExpectations', 'IX_RunExpectations_ActualRunId_RevisionNumber', true),
        ('RunExpectations', 'IX_RunExpectations_ActualRunRevisionId', true),
        ('RunExpectations', 'IX_RunExpectations_CreatedByUserId', false),
        ('RunExpectationSources', 'IX_RunExpectationSources_BinsRunEntryId', false),
        ('RunExpectationSources', 'IX_RunExpectationSources_QcSampleId', false),
        ('RunExpectationSources', 'IX_RunExpectationSources_RunExpectationId_BinsRunEntryId', true),
        ('RunExpectationSources', 'IX_RunExpectationSources_WarehouseId_RoomId_CropYearSnapshot_LotSnapshot_VarietySnapshot', false)
    ) expected(table_name, index_name, require_unique)
    WHERE NOT EXISTS (
        SELECT 1
        FROM pg_class table_row
        JOIN pg_index index_metadata ON index_metadata.indrelid = table_row.oid
        JOIN pg_class index_row ON index_row.oid = index_metadata.indexrelid
        WHERE table_row.relnamespace = current_schema()::regnamespace
          AND table_row.relname = expected.table_name
          AND index_row.relname = left(expected.index_name, 63)
          AND (NOT expected.require_unique OR index_metadata.indisunique));

    SELECT string_agg(expected.constraint_name, ', ' ORDER BY expected.constraint_name)
    INTO missing_constraints
    FROM (VALUES
        ('PackoutRuns', 'FK_PackoutRuns_ActualRuns_ActualRunId'),
        ('PackoutRuns', 'FK_PackoutRuns_RunExpectations_RunExpectationId'),
        ('PackoutSourceAllocations', 'FK_PackoutSourceAllocations_PackoutRuns_PackoutRunId'),
        ('PackoutSourceAllocations', 'FK_PackoutSourceAllocations_RunExpectationSources_RunExpectationSourceId'),
        ('RunExpectations', 'FK_RunExpectations_ActualRunRevisions_ActualRunRevisionId'),
        ('RunExpectations', 'FK_RunExpectations_ActualRuns_ActualRunId'),
        ('RunExpectations', 'FK_RunExpectations_Users_CreatedByUserId'),
        ('RunExpectationSources', 'FK_RunExpectationSources_BinsRunEntries_BinsRunEntryId'),
        ('RunExpectationSources', 'FK_RunExpectationSources_QcSamples_QcSampleId'),
        ('RunExpectationSources', 'FK_RunExpectationSources_RunExpectations_RunExpectationId')
    ) expected(table_name, constraint_name)
    WHERE NOT EXISTS (
        SELECT 1
        FROM pg_constraint constraint_row
        JOIN pg_class table_row ON table_row.oid = constraint_row.conrelid
        JOIN pg_namespace namespace_row ON namespace_row.oid = table_row.relnamespace
        WHERE namespace_row.nspname = current_schema()
          AND table_row.relname = expected.table_name
          AND constraint_row.conname = left(expected.constraint_name, 63)
          AND constraint_row.contype = 'f');

    SELECT string_agg(expected.constraint_name, ', ' ORDER BY expected.constraint_name)
    INTO missing_primary_keys
    FROM (VALUES
        ('RunExpectations', 'PK_RunExpectations'),
        ('RunExpectationSources', 'PK_RunExpectationSources'),
        ('PackoutSourceAllocations', 'PK_PackoutSourceAllocations')
    ) expected(table_name, constraint_name)
    WHERE NOT EXISTS (
        SELECT 1
        FROM pg_constraint constraint_row
        JOIN pg_class table_row ON table_row.oid = constraint_row.conrelid
        JOIN pg_namespace namespace_row ON namespace_row.oid = table_row.relnamespace
        WHERE namespace_row.nspname = current_schema()
          AND table_row.relname = expected.table_name
          AND constraint_row.conname = left(expected.constraint_name, 63)
          AND constraint_row.contype = 'p');

    IF missing_indexes IS NOT NULL OR missing_constraints IS NOT NULL OR missing_primary_keys IS NOT NULL THEN
        RAISE EXCEPTION
            'Compatibility apply did not produce required indexes (%), foreign keys (%), or primary keys (%). Transaction rolled back.',
            coalesce(missing_indexes, 'none'),
            coalesce(missing_constraints, 'none'),
            coalesce(missing_primary_keys, 'none');
    END IF;
END $POSTCHECK_NAMED_OBJECTS$;

COMMIT;
