\set ON_ERROR_STOP on
\ir preflight-processor-shipments.sql

BEGIN;
SET LOCAL lock_timeout='15s';
SET LOCAL statement_timeout='10min';
SELECT pg_advisory_xact_lock(hashtextextended('CropQc:20260821031442_AddProcessorShipments',0));
SELECT to_regclass(format('%I.%I',current_schema(),'Processors')) IS NULL AS create_target \gset
\if :create_target
CREATE TABLE "Processors" (
 "Id" integer GENERATED BY DEFAULT AS IDENTITY, "Name" character varying(200) NOT NULL, "Code" character varying(50), "IsActive" boolean NOT NULL, "Notes" character varying(1000),
 "CreatedAt" timestamp with time zone NOT NULL, "CreatedByUserId" integer, "UpdatedAt" timestamp with time zone NOT NULL, "UpdatedByUserId" integer,
 CONSTRAINT "PK_Processors" PRIMARY KEY ("Id"), CONSTRAINT "FK_Processors_Users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users"("Id") ON DELETE SET NULL,
 CONSTRAINT "FK_Processors_Users_UpdatedByUserId" FOREIGN KEY ("UpdatedByUserId") REFERENCES "Users"("Id") ON DELETE SET NULL);
CREATE TABLE "ProcessorShipments" (
 "Id" bigint GENERATED BY DEFAULT AS IDENTITY, "OperationKey" character varying(150) NOT NULL, "ProcessorId" integer NOT NULL, "ProcessorNameSnapshot" character varying(200) NOT NULL,
 "ShippedAt" timestamp with time zone NOT NULL, "OriginalSaleRate" numeric(18,4) NOT NULL, "OriginalPricingBasis" character varying(20) NOT NULL, "SaleRate" numeric(18,4) NOT NULL,
 "PricingBasis" character varying(20) NOT NULL, "Currency" character varying(3) NOT NULL, "ReferenceNumber" character varying(100), "Notes" character varying(1000),
 "CreatedByUserId" integer NOT NULL, "CreatedAt" timestamp with time zone NOT NULL, "ReversedAt" timestamp with time zone, "ReversedByUserId" integer, "ReversalReason" character varying(1000), "ConcurrencyVersion" bigint NOT NULL,
 CONSTRAINT "PK_ProcessorShipments" PRIMARY KEY ("Id"), CONSTRAINT "FK_ProcessorShipments_Processors_ProcessorId" FOREIGN KEY ("ProcessorId") REFERENCES "Processors"("Id") ON DELETE RESTRICT,
 CONSTRAINT "FK_ProcessorShipments_Users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users"("Id") ON DELETE RESTRICT,
 CONSTRAINT "FK_ProcessorShipments_Users_ReversedByUserId" FOREIGN KEY ("ReversedByUserId") REFERENCES "Users"("Id") ON DELETE RESTRICT);
CREATE TABLE "ProcessorShipmentLines" (
 "Id" bigint GENERATED BY DEFAULT AS IDENTITY, "ProcessorShipmentId" bigint NOT NULL, "WarehouseId" integer NOT NULL, "RoomId" integer NOT NULL, "CropYear" integer, "ReceiptId" bigint,
 "SourceInventoryAdjustmentId" bigint, "GrowerLotId" integer, "FruitProfileId" integer, "GrowerNumberSnapshot" character varying(50), "GrowerNameSnapshot" character varying(200) NOT NULL,
 "LotNumberSnapshot" character varying(100) NOT NULL, "VarietyCodeSnapshot" character varying(50) NOT NULL, "ProductionTypeSnapshot" character varying(50) NOT NULL, "IsOrganicSnapshot" boolean,
 "InventoryStatusSnapshot" character varying(100), "TreatmentStateSnapshot" character varying(25) NOT NULL, "TreatmentSignatureSnapshot" character varying(1000) NOT NULL,
 "TreatmentSummarySnapshot" character varying(2000) NOT NULL, "BinsSent" integer NOT NULL, "PoundsPerBinSnapshot" numeric(18,4),
 CONSTRAINT "PK_ProcessorShipmentLines" PRIMARY KEY ("Id"), CONSTRAINT "FK_ProcessorShipmentLines_ProcessorShipments_ProcessorShipmentId" FOREIGN KEY ("ProcessorShipmentId") REFERENCES "ProcessorShipments"("Id") ON DELETE RESTRICT,
 CONSTRAINT "FK_ProcessorShipmentLines_Receipts_ReceiptId" FOREIGN KEY ("ReceiptId") REFERENCES "Receipts"("Id") ON DELETE SET NULL,
 CONSTRAINT "FK_ProcessorShipmentLines_RoomInventoryAdjustments_SourceInventoryAdjustmentId" FOREIGN KEY ("SourceInventoryAdjustmentId") REFERENCES "RoomInventoryAdjustments"("Id") ON DELETE SET NULL,
 CONSTRAINT "FK_ProcessorShipmentLines_Rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES "Rooms"("Id") ON DELETE RESTRICT,
 CONSTRAINT "FK_ProcessorShipmentLines_Warehouses_WarehouseId" FOREIGN KEY ("WarehouseId") REFERENCES "Warehouses"("Id") ON DELETE RESTRICT);
CREATE TABLE "ProcessorShipmentPriceCorrections" (
 "Id" bigint GENERATED BY DEFAULT AS IDENTITY, "ProcessorShipmentId" bigint NOT NULL, "OperationKey" character varying(150) NOT NULL, "OriginalSaleRate" numeric(18,4) NOT NULL,
 "OriginalPricingBasis" character varying(20) NOT NULL, "CorrectedSaleRate" numeric(18,4) NOT NULL, "CorrectedPricingBasis" character varying(20) NOT NULL,
 "Reason" character varying(1000) NOT NULL, "CorrectedByUserId" integer NOT NULL, "CorrectedAt" timestamp with time zone NOT NULL,
 CONSTRAINT "PK_ProcessorShipmentPriceCorrections" PRIMARY KEY ("Id"), CONSTRAINT "FK_ProcessorShipmentPriceCorrections_ProcessorShipments_ProcessorShipmentId" FOREIGN KEY ("ProcessorShipmentId") REFERENCES "ProcessorShipments"("Id") ON DELETE RESTRICT,
 CONSTRAINT "FK_ProcessorShipmentPriceCorrections_Users_CorrectedByUserId" FOREIGN KEY ("CorrectedByUserId") REFERENCES "Users"("Id") ON DELETE RESTRICT);
ALTER TABLE "RoomInventoryAdjustments" ADD COLUMN "ProcessorShipmentLineId" bigint;
ALTER TABLE "TreatmentLineageMovements" ADD COLUMN "ProcessorShipmentLineId" bigint;
ALTER TABLE "RoomInventoryAdjustments" ADD CONSTRAINT "FK_RoomInventoryAdjustments_ProcessorShipmentLines_ProcessorShipmentLineId" FOREIGN KEY ("ProcessorShipmentLineId") REFERENCES "ProcessorShipmentLines"("Id") ON DELETE RESTRICT;
ALTER TABLE "TreatmentLineageMovements" ADD CONSTRAINT "FK_TreatmentLineageMovements_ProcessorShipmentLines_ProcessorShipmentLineId" FOREIGN KEY ("ProcessorShipmentLineId") REFERENCES "ProcessorShipmentLines"("Id") ON DELETE RESTRICT;
CREATE INDEX "IX_TreatmentLineageMovements_ProcessorShipmentLineId" ON "TreatmentLineageMovements"("ProcessorShipmentLineId");
CREATE INDEX "IX_RoomInventoryAdjustments_ProcessorShipmentLineId" ON "RoomInventoryAdjustments"("ProcessorShipmentLineId");
CREATE UNIQUE INDEX "IX_RoomInventoryAdjustments_ProcessorShipmentLineId_AdjustmentType" ON "RoomInventoryAdjustments"("ProcessorShipmentLineId","AdjustmentType") WHERE "ProcessorShipmentLineId" IS NOT NULL;
CREATE INDEX "IX_Processors_CreatedByUserId" ON "Processors"("CreatedByUserId"); CREATE INDEX "IX_Processors_IsActive_Name" ON "Processors"("IsActive","Name"); CREATE INDEX "IX_Processors_Name" ON "Processors"("Name"); CREATE INDEX "IX_Processors_UpdatedByUserId" ON "Processors"("UpdatedByUserId");
CREATE INDEX "IX_ProcessorShipmentLines_ProcessorShipmentId" ON "ProcessorShipmentLines"("ProcessorShipmentId"); CREATE INDEX "IX_ProcessorShipmentLines_ReceiptId" ON "ProcessorShipmentLines"("ReceiptId"); CREATE INDEX "IX_ProcessorShipmentLines_RoomId" ON "ProcessorShipmentLines"("RoomId"); CREATE INDEX "IX_ProcessorShipmentLines_SourceInventoryAdjustmentId" ON "ProcessorShipmentLines"("SourceInventoryAdjustmentId"); CREATE INDEX "IX_ProcessorShipmentLines_WarehouseId_RoomId" ON "ProcessorShipmentLines"("WarehouseId","RoomId");
CREATE INDEX "IX_ProcessorShipmentPriceCorrections_CorrectedByUserId" ON "ProcessorShipmentPriceCorrections"("CorrectedByUserId"); CREATE UNIQUE INDEX "IX_ProcessorShipmentPriceCorrections_OperationKey" ON "ProcessorShipmentPriceCorrections"("OperationKey"); CREATE INDEX "IX_ProcessorShipmentPriceCorrections_ProcessorShipmentId_CorrectedAt" ON "ProcessorShipmentPriceCorrections"("ProcessorShipmentId","CorrectedAt");
CREATE INDEX "IX_ProcessorShipments_CreatedByUserId" ON "ProcessorShipments"("CreatedByUserId"); CREATE UNIQUE INDEX "IX_ProcessorShipments_OperationKey" ON "ProcessorShipments"("OperationKey"); CREATE INDEX "IX_ProcessorShipments_ProcessorId" ON "ProcessorShipments"("ProcessorId"); CREATE INDEX "IX_ProcessorShipments_ReversedByUserId" ON "ProcessorShipments"("ReversedByUserId"); CREATE INDEX "IX_ProcessorShipments_ShippedAt_ProcessorId" ON "ProcessorShipments"("ShippedAt","ProcessorId");
\else
\echo 'Processor Shipment schema is already complete and exact; no DDL will be applied.'
\endif
DO $postcheck$ BEGIN
 IF to_regclass(format('%I.%I',current_schema(),'ProcessorShipments')) IS NULL THEN RAISE EXCEPTION 'Processor Shipment schema missing after apply'; END IF;
 IF current_setting('cropqc.test_force_processor_shipment_failure',true)='on' THEN RAISE EXCEPTION 'Forced Processor Shipment compatibility failure for rollback regression'; END IF;
END $postcheck$;
COMMIT;
\ir verify-processor-shipments.sql
