\set ON_ERROR_STOP on
\ir preflight-treatment-report-attachments.sql

BEGIN;
SET LOCAL lock_timeout='15s';
SET LOCAL statement_timeout='10min';
SELECT pg_advisory_xact_lock(hashtextextended('CropQc:20260819142656_AddTreatmentReportAttachments', 0));
SELECT to_regclass(format('%I.%I', current_schema(), 'RoomTreatmentApplicationAttachments')) IS NULL AS create_target \gset

\if :create_target
CREATE TABLE "RoomTreatmentApplicationAttachments" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "RoomTreatmentApplicationId" bigint NOT NULL,
    "OperationKey" character varying(100) NOT NULL,
    "FileName" character varying(255) NOT NULL,
    "ContentType" character varying(100) NOT NULL,
    "FileSizeBytes" bigint NOT NULL,
    "StorageProvider" character varying(50) NOT NULL,
    "DriveId" character varying(200),
    "FileId" character varying(200) NOT NULL,
    "FolderId" character varying(200),
    "StoragePath" character varying(1000) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedByUserId" integer NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedByUserId" integer,
    "DeleteReason" character varying(1000),
    CONSTRAINT "PK_RoomTreatmentApplicationAttachments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RoomTreatmentApplicationAttachments_RoomTreatmentApplications_RoomTreatmentApplicationId" FOREIGN KEY ("RoomTreatmentApplicationId") REFERENCES "RoomTreatmentApplications" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_RoomTreatmentApplicationAttachments_Users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_RoomTreatmentApplicationAttachments_Users_DeletedByUserId" FOREIGN KEY ("DeletedByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
);
CREATE INDEX "IX_RoomTreatmentApplicationAttachments_CreatedByUserId" ON "RoomTreatmentApplicationAttachments" ("CreatedByUserId");
CREATE INDEX "IX_RoomTreatmentApplicationAttachments_DeletedByUserId" ON "RoomTreatmentApplicationAttachments" ("DeletedByUserId");
CREATE INDEX "IX_TreatmentReportAttachments_Application_IsDeleted_CreatedAt" ON "RoomTreatmentApplicationAttachments" ("RoomTreatmentApplicationId", "IsDeleted", "CreatedAt");
CREATE UNIQUE INDEX "UX_TreatmentReportAttachments_Application_OperationKey" ON "RoomTreatmentApplicationAttachments" ("RoomTreatmentApplicationId", "OperationKey");
\else
\echo 'Treatment report attachment schema is already complete and exact; no DDL will be applied.'
\endif

DO $postcheck$
BEGIN
    IF to_regclass(format('%I.%I', current_schema(), 'RoomTreatmentApplicationAttachments')) IS NULL THEN
        RAISE EXCEPTION 'Treatment report attachment table is missing after apply';
    END IF;
    IF current_setting('cropqc.test_force_treatment_report_failure', true)='on' THEN
        RAISE EXCEPTION 'Forced treatment report compatibility failure for rollback regression';
    END IF;
END $postcheck$;
COMMIT;
\ir verify-treatment-report-attachments.sql
