\set ON_ERROR_STOP on
\ir preflight-room-inventory-losses.sql

BEGIN;
SELECT pg_advisory_xact_lock(hashtextextended('CropQc:20260812061125_AddRoomInventoryLosses', 0));
SELECT to_regclass(format('%I.%I',current_schema(),'RoomInventoryLosses')) IS NULL AS create_target \gset
\if :create_target
CREATE TABLE "RoomInventoryLosses" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "OperationKey" character varying(150) NOT NULL,
    "WarehouseId" integer NOT NULL,
    "RoomId" integer NOT NULL,
    "ReceiptId" bigint NULL,
    "CropYear" integer NULL,
    "GrowerLotId" integer NULL,
    "FruitProfileId" integer NULL,
    "GrowerName" character varying(200) NOT NULL,
    "GrowerNumber" character varying(50) NULL,
    "LotNumber" character varying(100) NOT NULL,
    "PoolStart" character varying(20) NULL,
    "VarietyCode" character varying(50) NOT NULL,
    "InventoryStatus" character varying(100) NULL,
    "LossType" character varying(50) NOT NULL,
    "BinCount" integer NOT NULL,
    "Reason" character varying(500) NOT NULL,
    "Notes" character varying(1000) NULL,
    "OccurredAt" timestamp with time zone NULL,
    "CreatedByUserId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsReversed" boolean NOT NULL,
    "ReversedAt" timestamp with time zone NULL,
    "ReversedByUserId" integer NULL,
    "ReverseReason" character varying(1000) NULL,
    CONSTRAINT "PK_RoomInventoryLosses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RoomInventoryLosses_Warehouses_WarehouseId" FOREIGN KEY ("WarehouseId") REFERENCES "Warehouses" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_RoomInventoryLosses_Rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES "Rooms" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_RoomInventoryLosses_Receipts_ReceiptId" FOREIGN KEY ("ReceiptId") REFERENCES "Receipts" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_RoomInventoryLosses_FruitProfiles_FruitProfileId" FOREIGN KEY ("FruitProfileId") REFERENCES "FruitProfiles" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_RoomInventoryLosses_Users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_RoomInventoryLosses_Users_ReversedByUserId" FOREIGN KEY ("ReversedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);
ALTER TABLE "RoomInventoryAdjustments" ADD COLUMN "RoomInventoryLossId" bigint NULL;
ALTER TABLE "RoomInventoryAdjustments" ADD CONSTRAINT "FK_RoomInventoryAdjustments_RoomInventoryLosses_RoomInventoryLossId"
    FOREIGN KEY ("RoomInventoryLossId") REFERENCES "RoomInventoryLosses" ("Id") ON DELETE RESTRICT;
CREATE INDEX "IX_RoomInventoryAdjustments_RoomInventoryLossId" ON "RoomInventoryAdjustments" ("RoomInventoryLossId");
CREATE UNIQUE INDEX "IX_RoomInventoryAdjustments_RoomInventoryLossId_AdjustmentType"
    ON "RoomInventoryAdjustments" ("RoomInventoryLossId", "AdjustmentType") WHERE "RoomInventoryLossId" IS NOT NULL;
CREATE INDEX "IX_RoomInventoryLosses_CreatedByUserId" ON "RoomInventoryLosses" ("CreatedByUserId");
CREATE INDEX "IX_RoomInventoryLosses_FruitProfileId" ON "RoomInventoryLosses" ("FruitProfileId");
CREATE UNIQUE INDEX "IX_RoomInventoryLosses_OperationKey" ON "RoomInventoryLosses" ("OperationKey");
CREATE INDEX "IX_RoomInventoryLosses_ReceiptId_CreatedAt" ON "RoomInventoryLosses" ("ReceiptId", "CreatedAt");
CREATE INDEX "IX_RoomInventoryLosses_ReversedByUserId" ON "RoomInventoryLosses" ("ReversedByUserId");
CREATE INDEX "IX_RoomInventoryLosses_RoomId_CreatedAt" ON "RoomInventoryLosses" ("RoomId", "CreatedAt");
CREATE INDEX "IX_RoomInventoryLosses_WarehouseId" ON "RoomInventoryLosses" ("WarehouseId");
\else
\echo 'Room Inventory Loss schema is already complete and exact; no DDL will be applied.'
\endif

DO $postcheck$
BEGIN
    IF to_regclass(format('%I.%I',current_schema(),'RoomInventoryLosses')) IS NULL
       OR NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=current_schema() AND table_name='RoomInventoryAdjustments' AND column_name='RoomInventoryLossId') THEN
        RAISE EXCEPTION 'Post-apply Room Inventory Loss object set is incomplete; transaction will roll back.';
    END IF;
    IF current_setting('cropqc.test_force_room_inventory_loss_failure', true) = 'on' THEN
        RAISE EXCEPTION 'Forced compatibility-apply failure for rollback regression testing.';
    END IF;
END $postcheck$;
COMMIT;

\ir verify-room-inventory-losses.sql
