START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    ALTER TABLE "PackoutRuns" ALTER COLUMN "RunProjectionId" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    ALTER TABLE "PackoutRuns" ADD "ActualRunId" bigint;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    ALTER TABLE "PackoutRuns" ADD "RunExpectationId" bigint;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE TABLE "RunExpectations" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ActualRunId" bigint NOT NULL,
        "ActualRunRevisionId" bigint NOT NULL,
        "RevisionNumber" integer NOT NULL,
        "FacilityWarehouseId" integer NOT NULL,
        "FacilitySnapshot" character varying(50) NOT NULL,
        "RunAtSnapshot" timestamp with time zone NOT NULL,
        "TotalBins" integer NOT NULL,
        "GrossPounds" numeric(18,4) NOT NULL,
        "ExpectedPackoutPercent" numeric(8,4) NOT NULL,
        "ExpectedPackedPounds" numeric(18,4) NOT NULL,
        "ExpectedPackedBoxes" numeric(18,4) NOT NULL,
        "ExpectedWholeBoxes" integer NOT NULL,
        "ExpectedCullPounds" numeric(18,4) NOT NULL,
        "ExpectedJuicePounds" numeric(18,4) NOT NULL,
        "ExpectedPeelerPounds" numeric(18,4) NOT NULL,
        "ExpectedWastePounds" numeric(18,4) NOT NULL,
        "ConfidencePercent" numeric(8,4) NOT NULL,
        "SizeDistributionSnapshotJson" text NOT NULL,
        "GradeDistributionSnapshotJson" text NOT NULL,
        "ConfigurationSnapshotJson" text NOT NULL,
        "CalculationVersion" character varying(75) NOT NULL,
        "CalculatedAt" timestamp with time zone NOT NULL,
        "CreatedByUserId" integer,
        CONSTRAINT "PK_RunExpectations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RunExpectations_ActualRunRevisions_ActualRunRevisionId" FOREIGN KEY ("ActualRunRevisionId") REFERENCES "ActualRunRevisions" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_RunExpectations_ActualRuns_ActualRunId" FOREIGN KEY ("ActualRunId") REFERENCES "ActualRuns" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_RunExpectations_Users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE TABLE "RunExpectationSources" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "RunExpectationId" bigint NOT NULL,
        "BinsRunEntryId" bigint NOT NULL,
        "WarehouseId" integer NOT NULL,
        "RoomId" integer NOT NULL,
        "FacilitySnapshot" character varying(50) NOT NULL,
        "RoomSnapshot" character varying(100) NOT NULL,
        "CropYearSnapshot" integer,
        "GrowerLotId" integer,
        "FruitProfileId" integer,
        "GrowerSnapshot" character varying(200) NOT NULL,
        "LotSnapshot" character varying(100) NOT NULL,
        "VarietySnapshot" character varying(100) NOT NULL,
        "ProductionTypeSnapshot" character varying(50) NOT NULL,
        "IsOrganicSnapshot" boolean NOT NULL,
        "BinsContributed" integer NOT NULL,
        "ContributionPercent" numeric(9,6) NOT NULL,
        "QcSampleId" bigint,
        "QcSampleTakenAtSnapshot" timestamp with time zone,
        "QcFruitCountSnapshot" integer NOT NULL,
        "QcMeasurementSnapshotJson" text NOT NULL,
        "SizeDistributionSnapshotJson" text NOT NULL,
        "GradeDistributionSnapshotJson" text NOT NULL,
        "GrossPounds" numeric(18,4) NOT NULL,
        "ExpectedPackedPounds" numeric(18,4) NOT NULL,
        "ExpectedWholeBoxes" integer NOT NULL,
        "ExpectedCullPounds" numeric(18,4) NOT NULL,
        "ConfidencePercent" numeric(8,4) NOT NULL,
        "WarningSnapshot" character varying(1000),
        CONSTRAINT "PK_RunExpectationSources" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RunExpectationSources_BinsRunEntries_BinsRunEntryId" FOREIGN KEY ("BinsRunEntryId") REFERENCES "BinsRunEntries" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_RunExpectationSources_QcSamples_QcSampleId" FOREIGN KEY ("QcSampleId") REFERENCES "QcSamples" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_RunExpectationSources_RunExpectations_RunExpectationId" FOREIGN KEY ("RunExpectationId") REFERENCES "RunExpectations" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE TABLE "PackoutSourceAllocations" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "PackoutRunId" bigint NOT NULL,
        "RunExpectationSourceId" bigint NOT NULL,
        "BinsContributed" integer NOT NULL,
        "ContributionPercent" numeric(9,6) NOT NULL,
        "AllocatedPackedPounds" numeric(18,6) NOT NULL,
        "AllocatedWholeBoxes" integer NOT NULL,
        "AllocatedResidualPounds" numeric(18,6) NOT NULL,
        "AllocatedJuicePounds" numeric(18,6) NOT NULL,
        "AllocatedPeelerPounds" numeric(18,6) NOT NULL,
        "AllocatedWastePounds" numeric(18,6) NOT NULL,
        "PackCodeAllocationJson" text NOT NULL,
        "SizeAllocationJson" text NOT NULL,
        "GradeAllocationJson" text NOT NULL,
        "AllocationVersion" character varying(75) NOT NULL,
        "CalculatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_PackoutSourceAllocations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PackoutSourceAllocations_PackoutRuns_PackoutRunId" FOREIGN KEY ("PackoutRunId") REFERENCES "PackoutRuns" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_PackoutSourceAllocations_RunExpectationSources_RunExpectationSourceId" FOREIGN KEY ("RunExpectationSourceId") REFERENCES "RunExpectationSources" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE INDEX "IX_PackoutRuns_RunExpectationId" ON "PackoutRuns" ("RunExpectationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE UNIQUE INDEX "UX_PackoutRuns_ActualRunId" ON "PackoutRuns" ("ActualRunId") WHERE "ActualRunId" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE UNIQUE INDEX "IX_PackoutSourceAllocations_PackoutRunId_RunExpectationSourceId" ON "PackoutSourceAllocations" ("PackoutRunId", "RunExpectationSourceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE INDEX "IX_PackoutSourceAllocations_RunExpectationSourceId" ON "PackoutSourceAllocations" ("RunExpectationSourceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE UNIQUE INDEX "IX_RunExpectations_ActualRunId_RevisionNumber" ON "RunExpectations" ("ActualRunId", "RevisionNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE UNIQUE INDEX "IX_RunExpectations_ActualRunRevisionId" ON "RunExpectations" ("ActualRunRevisionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE INDEX "IX_RunExpectations_CreatedByUserId" ON "RunExpectations" ("CreatedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE INDEX "IX_RunExpectationSources_BinsRunEntryId" ON "RunExpectationSources" ("BinsRunEntryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE INDEX "IX_RunExpectationSources_QcSampleId" ON "RunExpectationSources" ("QcSampleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE UNIQUE INDEX "IX_RunExpectationSources_RunExpectationId_BinsRunEntryId" ON "RunExpectationSources" ("RunExpectationId", "BinsRunEntryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    CREATE INDEX "IX_RunExpectationSources_WarehouseId_RoomId_CropYearSnapshot_LotSnapshot_VarietySnapshot" ON "RunExpectationSources" ("WarehouseId", "RoomId", "CropYearSnapshot", "LotSnapshot", "VarietySnapshot");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    ALTER TABLE "PackoutRuns" ADD CONSTRAINT "FK_PackoutRuns_ActualRuns_ActualRunId" FOREIGN KEY ("ActualRunId") REFERENCES "ActualRuns" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    ALTER TABLE "PackoutRuns" ADD CONSTRAINT "FK_PackoutRuns_RunExpectations_RunExpectationId" FOREIGN KEY ("RunExpectationId") REFERENCES "RunExpectations" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731014107_SeparatePlanningProjectionsFromActualRuns') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260731014107_SeparatePlanningProjectionsFromActualRuns', '9.0.9');
    END IF;
END $EF$;
COMMIT;
