START TRANSACTION;
DROP INDEX "IX_RoomInventoryAdjustments_InterCrewTransferId_AdjustmentType";

ALTER TABLE "Receipts" ADD "IsTransferReceipt" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Receipts" ADD "TransferCompletedAt" timestamp with time zone;

ALTER TABLE "InterCrewTransfers" ADD "ReceivingReceiptId" bigint;

ALTER TABLE "InterCrewTransfers" ADD "RequiresTruckReceipt" boolean NOT NULL DEFAULT FALSE;

CREATE TABLE "ReceiptVarietyLines" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ReceiptId" bigint NOT NULL,
    "FruitProfileId" integer NOT NULL,
    "BinCount" integer NOT NULL,
    CONSTRAINT "PK_ReceiptVarietyLines" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ReceiptVarietyLines_FruitProfiles_FruitProfileId" FOREIGN KEY ("FruitProfileId") REFERENCES "FruitProfiles" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ReceiptVarietyLines_Receipts_ReceiptId" FOREIGN KEY ("ReceiptId") REFERENCES "Receipts" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_RoomInventoryAdjustments_InterCrewTransferId_AdjustmentType" ON "RoomInventoryAdjustments" ("InterCrewTransferId", "AdjustmentType") WHERE "InterCrewTransferId" IS NOT NULL;

CREATE UNIQUE INDEX "IX_InterCrewTransfers_ReceivingReceiptId" ON "InterCrewTransfers" ("ReceivingReceiptId") WHERE "ReceivingReceiptId" IS NOT NULL;

CREATE INDEX "IX_ReceiptVarietyLines_FruitProfileId" ON "ReceiptVarietyLines" ("FruitProfileId");

CREATE UNIQUE INDEX "IX_ReceiptVarietyLines_ReceiptId_FruitProfileId" ON "ReceiptVarietyLines" ("ReceiptId", "FruitProfileId");

ALTER TABLE "InterCrewTransfers" ADD CONSTRAINT "FK_InterCrewTransfers_Receipts_ReceivingReceiptId" FOREIGN KEY ("ReceivingReceiptId") REFERENCES "Receipts" ("Id") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260923202144_AddTruckReceiptReconciliation', '9.0.9');

COMMIT;
