param([int]$HostPort = 55491, [switch]$KeepContainer)
$ErrorActionPreference='Stop'
$root=Split-Path -Parent $PSScriptRoot
$container="cropqc-actual-run-details-schema-$PID"
$password='cropqc-disposable-actual-run-details-only'
$previous='20260902140938_AddInventoryIdentityCorrections'
$expected='20260902201338_AddActualRunDetailCorrections'
$scriptRoot='/tmp/cropqc-actual-run-details'
function D { param([Parameter(ValueFromRemainingArguments=$true)][string[]]$Arguments) & docker @Arguments; if($LASTEXITCODE-ne 0){throw "docker failed: $($Arguments -join ' ')"} }
function Db([string]$name){D -Arguments @('exec',$container,'createdb','-U','postgres',$name)}
function CloneDb([string]$source,[string]$name){D -Arguments @('exec',$container,'createdb','-U','postgres','-T',$source,$name)}
function Sql([string]$db,[string]$sql){$sql|docker exec -i $container psql -X -v ON_ERROR_STOP=1 -U postgres -d $db;if($LASTEXITCODE-ne 0){throw "SQL failed: $db"}}
function Scalar([string]$db,[string]$sql){$r=$sql|docker exec -i $container psql -X -v ON_ERROR_STOP=1 -U postgres -d $db -At;if($LASTEXITCODE-ne 0){throw "SQL scalar failed: $db"};return ($r|Select-Object -Last 1).Trim()}
function Script([string]$db,[string]$name){docker exec $container psql -X -v ON_ERROR_STOP=1 -U postgres -d $db -f "$scriptRoot/$name";if($LASTEXITCODE-ne 0){throw "$name failed: $db"}}
function Ef([string]$db,[string]$target){$oldP=$env:DATABASE_PROVIDER;$oldC=$env:ConnectionStrings__CropQc;try{$env:DATABASE_PROVIDER='PostgreSql';$env:ConnectionStrings__CropQc="Host=127.0.0.1;Port=$HostPort;Database=$db;Username=postgres;Password=$password";$a=@('ef','database','update',$target,'--project','src\CropQc.Data\CropQc.Data.csproj','--startup-project','src\CropQc.Data\CropQc.Data.csproj','--no-build');dotnet @a;if($LASTEXITCODE-ne 0){throw "EF failed: $db"}}finally{$env:DATABASE_PROVIDER=$oldP;$env:ConnectionStrings__CropQc=$oldC}}
function EnsureWorkflow([string]$db){$old=$env:CROPQC_ACTUAL_RUN_DETAIL_POSTGRES;try{$env:CROPQC_ACTUAL_RUN_DETAIL_POSTGRES="Host=127.0.0.1;Port=$HostPort;Database=$db;Username=postgres;Password=$password";dotnet test tests\CropQc.Api.Tests\CropQc.Api.Tests.csproj --no-build --filter FullyQualifiedName~PostgreSql_ActualRunDetailCorrectionIsNeutralAndCanonicalReportingTranslates;if($LASTEXITCODE-ne 0){throw "PostgreSQL workflow failed: $db"}}finally{$env:CROPQC_ACTUAL_RUN_DETAIL_POSTGRES=$old}}
function GenerateMigrationScript([string]$path){$old=$env:DATABASE_PROVIDER;try{$env:DATABASE_PROVIDER='PostgreSql';dotnet ef migrations script $previous $expected --project src\CropQc.Data\CropQc.Data.csproj --startup-project src\CropQc.Data\CropQc.Data.csproj --no-build --output $path;if($LASTEXITCODE-ne 0){throw 'EF migration script generation failed'}}finally{$env:DATABASE_PROVIDER=$old}}
function Gate([string]$db){$oldE=$env:ASPNETCORE_ENVIRONMENT;$oldP=$env:DATABASE_PROVIDER;$oldC=$env:ConnectionStrings__CropQc;$oldError=$ErrorActionPreference;try{$env:ASPNETCORE_ENVIRONMENT='Production';$env:DATABASE_PROVIDER='PostgreSql';$env:ConnectionStrings__CropQc="Host=127.0.0.1;Port=$HostPort;Database=$db;Username=postgres;Password=$password";$ErrorActionPreference='Continue';$output=dotnet 'src\CropQc.Web\bin\Debug\net9.0\CropQc.Web.dll' "--verify-schema=$expected" 2>&1;$output|ForEach-Object{Write-Output $_};$gateText=$output-join "`n";if($gateText-notmatch 'Database deployment gate passed' -or $gateText-notmatch 'checked object count 901'){throw "901-object schema gate failed: $db"}}finally{$ErrorActionPreference=$oldError;$env:ASPNETCORE_ENVIRONMENT=$oldE;$env:DATABASE_PROVIDER=$oldP;$env:ConnectionStrings__CropQc=$oldC}}
function Signature([string]$db){Scalar $db @'
WITH s AS (
 SELECT 'c='||md5(string_agg(table_name||'|'||ordinal_position||'|'||column_name||'|'||data_type||'|'||is_nullable||'|'||coalesce(character_maximum_length::text,''),';' ORDER BY ordinal_position)) v FROM information_schema.columns WHERE table_schema=current_schema() AND table_name='ActualRunDetailCorrections'
 UNION ALL SELECT 'i='||md5(string_agg(pg_get_indexdef(i.indexrelid),';' ORDER BY c.relname)) FROM pg_index i JOIN pg_class c ON c.oid=i.indexrelid JOIN pg_class t ON t.oid=i.indrelid JOIN pg_namespace n ON n.oid=t.relnamespace WHERE n.nspname=current_schema() AND t.relname='ActualRunDetailCorrections'
 UNION ALL SELECT 'k='||md5(string_agg(c.conname||'|'||pg_get_constraintdef(c.oid),';' ORDER BY c.conname)) FROM pg_constraint c JOIN pg_class t ON t.oid=c.conrelid JOIN pg_namespace n ON n.oid=t.relnamespace WHERE n.nspname=current_schema() AND t.relname='ActualRunDetailCorrections') SELECT string_agg(v,';' ORDER BY v) FROM s;
'@}
function MustFail([string]$db,[string]$name){$old=$ErrorActionPreference;try{$ErrorActionPreference='Continue';docker exec $container psql -X -v ON_ERROR_STOP=1 -U postgres -d $db -f "$scriptRoot/$name" *> $null;$code=$LASTEXITCODE}finally{$ErrorActionPreference=$old};if($code-eq 0){throw "$name unexpectedly passed: $db"}}
if(-not(Get-Command docker -ErrorAction SilentlyContinue)){throw 'Docker is required.'}
Push-Location $root
try{
 D -Arguments @('run','--rm','-d','--name',$container,'-e',"POSTGRES_PASSWORD=$password",'-p',"${HostPort}:5432",'postgres:18')
 $ready=$false;for($i=0;$i-lt 30;$i++){docker exec $container pg_isready -U postgres *> $null;if($LASTEXITCODE-eq 0){$ready=$true;break};Start-Sleep -Milliseconds 500};if(-not$ready){throw 'PostgreSQL 18 not ready'}
 D -Arguments @('exec',$container,'mkdir','-p',$scriptRoot)
 foreach($file in Get-ChildItem (Join-Path $root 'scripts\postgresql\*.sql')){D -Arguments @('cp',$file.FullName,"${container}:${scriptRoot}/$($file.Name)")}
 Db cropqc_details_test_fresh;EnsureWorkflow cropqc_details_test_fresh
 Sql cropqc_details_test_fresh 'create table "__EFMigrationsHistory" ("MigrationId" character varying(150) not null primary key,"ProductVersion" character varying(32) not null); insert into "__EFMigrationsHistory" values (''ensure-created-test-baseline'',''9.0.9'');'
 Script cropqc_details_test_fresh verify-actual-run-detail-corrections.sql;$freshSig=Signature cropqc_details_test_fresh
 Db cropqc_details_test_baseline;Ef cropqc_details_test_baseline '20260828033737_AddTransferCustodyWorkflow';Sql cropqc_details_test_baseline 'create table "GrowerLots" ("Id" integer not null primary key);';Script cropqc_details_test_baseline preflight-inventory-identity-corrections.sql;Script cropqc_details_test_baseline apply-inventory-identity-corrections-schema.sql;Script cropqc_details_test_baseline verify-inventory-identity-corrections.sql
 CloneDb cropqc_details_test_baseline cropqc_details_test_ef;$migrationSql=Join-Path $env:TEMP "cropqc-actual-run-details-$PID.sql";GenerateMigrationScript $migrationSql;D -Arguments @('cp',$migrationSql,"${container}:${scriptRoot}/ef-migration.sql");Script cropqc_details_test_ef ef-migration.sql;Gate cropqc_details_test_ef;$efSig=Signature cropqc_details_test_ef;if($freshSig-ne$efSig){throw "Fresh model/EF migration catalog parity failed`n$freshSig`n$efSig"}
 CloneDb cropqc_details_test_baseline cropqc_details_test_upgrade;$before=Scalar cropqc_details_test_upgrade 'select count(*)||''|''||md5(string_agg("MigrationId"||''|''||"ProductVersion",'';'' order by "MigrationId")) from "__EFMigrationsHistory";';Script cropqc_details_test_upgrade preflight-actual-run-detail-corrections.sql;Script cropqc_details_test_upgrade apply-actual-run-detail-corrections-schema.sql;Script cropqc_details_test_upgrade apply-actual-run-detail-corrections-schema.sql;Gate cropqc_details_test_upgrade;$after=Scalar cropqc_details_test_upgrade 'select count(*)||''|''||md5(string_agg("MigrationId"||''|''||"ProductVersion",'';'' order by "MigrationId")) from "__EFMigrationsHistory";';if($before-ne$after){throw 'Migration history changed'};$compatSig=Signature cropqc_details_test_upgrade;if($freshSig-ne$compatSig){throw "Compatibility catalog parity failed`n$freshSig`n$compatSig"}
 CloneDb cropqc_details_test_baseline cropqc_details_test_partial;Sql cropqc_details_test_partial 'create table "ActualRunDetailCorrections" ("Id" bigint);';MustFail cropqc_details_test_partial preflight-actual-run-detail-corrections.sql
 CloneDb cropqc_details_test_baseline cropqc_details_test_rollback;$old=$ErrorActionPreference;try{$ErrorActionPreference='Continue';docker exec $container psql -X -v ON_ERROR_STOP=1 -U postgres -d cropqc_details_test_rollback -c "set cropqc.test_force_actual_run_detail_failure='on'" -f "$scriptRoot/apply-actual-run-detail-corrections-schema.sql" *> $null;$forced=$LASTEXITCODE}finally{$ErrorActionPreference=$old};if($forced-eq 0){throw 'Forced rollback unexpectedly passed'};if((Scalar cropqc_details_test_rollback 'select case when to_regclass(''"ActualRunDetailCorrections"'') is null then ''absent'' else ''partial'' end;')-ne'absent'){throw 'Forced rollback left Actual Run detail correction objects'}
 'Fresh PostgreSQL 18 model and authenticated workflow: PASS';'EF migration and compatibility 901-object gates: PASS';'Compatibility State A/apply/verify/repeat State B: PASS';"Model/EF/compatibility catalog parity: PASS ($freshSig)";"Migration history unchanged: PASS ($before)";'Partial State C and forced rollback: PASS'
}finally{Pop-Location;if(-not$KeepContainer){$old=$ErrorActionPreference;try{$ErrorActionPreference='Continue';docker rm -f $container *> $null}finally{$ErrorActionPreference=$old}}}
