param([int]$HostPort = 55466, [switch]$KeepContainer)
$ErrorActionPreference='Stop'
$root=Split-Path -Parent $PSScriptRoot
$container="cropqc-transfer-custody-schema-$PID"
$password='cropqc-disposable-transfer-custody-only'
$previous='20260826063718_AddGrowerNumberQcRecipients'
$expected='20260828033737_AddTransferCustodyWorkflow'
$scriptRoot='/tmp/cropqc-transfer-custody'
function D { param([Parameter(ValueFromRemainingArguments=$true)][string[]]$Arguments) & docker @Arguments; if($LASTEXITCODE-ne 0){throw "docker failed: $($Arguments -join ' ')"} }
function Db([string]$name){D -Arguments @('exec',$container,'createdb','-U','postgres',$name)}
function Sql([string]$db,[string]$sql){$sql|docker exec -i $container psql -X -v ON_ERROR_STOP=1 -U postgres -d $db;if($LASTEXITCODE-ne 0){throw "SQL failed: $db"}}
function Scalar([string]$db,[string]$sql){$r=$sql|docker exec -i $container psql -X -v ON_ERROR_STOP=1 -U postgres -d $db -At;if($LASTEXITCODE-ne 0){throw "SQL scalar failed: $db"};return ($r|Select-Object -Last 1).Trim()}
function Script([string]$db,[string]$name){docker exec $container psql -X -v ON_ERROR_STOP=1 -U postgres -d $db -f "$scriptRoot/$name";if($LASTEXITCODE-ne 0){throw "$name failed: $db"}}
function Ef([string]$db,[string]$target){$oldP=$env:DATABASE_PROVIDER;$oldC=$env:ConnectionStrings__CropQc;try{$env:DATABASE_PROVIDER='PostgreSql';$env:ConnectionStrings__CropQc="Host=127.0.0.1;Port=$HostPort;Database=$db;Username=postgres;Password=$password";$a=@('ef','database','update');if($target){$a+=$target};$a+=@('--project','src\CropQc.Data\CropQc.Data.csproj','--startup-project','src\CropQc.Data\CropQc.Data.csproj','--no-build');dotnet @a;if($LASTEXITCODE-ne 0){throw "EF failed: $db"}}finally{$env:DATABASE_PROVIDER=$oldP;$env:ConnectionStrings__CropQc=$oldC}}
function Gate([string]$db){$oldE=$env:ASPNETCORE_ENVIRONMENT;$oldP=$env:DATABASE_PROVIDER;$oldC=$env:ConnectionStrings__CropQc;try{$env:ASPNETCORE_ENVIRONMENT='Production';$env:DATABASE_PROVIDER='PostgreSql';$env:ConnectionStrings__CropQc="Host=127.0.0.1;Port=$HostPort;Database=$db;Username=postgres;Password=$password";dotnet 'src\CropQc.Web\bin\Debug\net9.0\CropQc.Web.dll' "--verify-schema=$expected";if($LASTEXITCODE-ne 0){throw "836-object gate failed: $db"}}finally{$env:ASPNETCORE_ENVIRONMENT=$oldE;$env:DATABASE_PROVIDER=$oldP;$env:ConnectionStrings__CropQc=$oldC}}
function Signature([string]$db){Scalar $db @'
WITH s AS (
 SELECT 'c='||md5(string_agg(table_name||'|'||ordinal_position||'|'||column_name||'|'||data_type||'|'||is_nullable||'|'||coalesce(character_maximum_length::text,''),';' ORDER BY table_name,ordinal_position)) v FROM information_schema.columns WHERE table_schema=current_schema() AND (table_name IN ('OutsideWarehouses','OutsideWarehouseTransfers','InterCrewTransfers') OR (table_name IN ('RoomInventoryAdjustments','TreatmentLineageMovements') AND column_name IN ('OutsideWarehouseTransferId','InterCrewTransferId')))
 UNION ALL SELECT 'i='||md5(string_agg(pg_get_indexdef(i.indexrelid),';' ORDER BY c.relname)) FROM pg_index i JOIN pg_class c ON c.oid=i.indexrelid JOIN pg_class t ON t.oid=i.indrelid JOIN pg_namespace n ON n.oid=t.relnamespace WHERE n.nspname=current_schema() AND (t.relname IN ('OutsideWarehouses','OutsideWarehouseTransfers','InterCrewTransfers') OR c.relname LIKE '%OutsideWarehouseTransferId%' OR c.relname LIKE '%InterCrewTransferId%')
 UNION ALL SELECT 'k='||md5(string_agg(c.conname||'|'||pg_get_constraintdef(c.oid),';' ORDER BY c.conname)) FROM pg_constraint c JOIN pg_class t ON t.oid=c.conrelid JOIN pg_namespace n ON n.oid=t.relnamespace WHERE n.nspname=current_schema() AND (t.relname IN ('OutsideWarehouses','OutsideWarehouseTransfers','InterCrewTransfers') OR c.conname LIKE '%OutsideWarehouseTransfer%' OR c.conname LIKE '%InterCrewTransfer%')) SELECT string_agg(v,';' ORDER BY v) FROM s;
'@}
function MustFail([string]$db,[string]$name){$old=$ErrorActionPreference;try{$ErrorActionPreference='Continue';docker exec $container psql -X -v ON_ERROR_STOP=1 -U postgres -d $db -f "$scriptRoot/$name" *> $null;$code=$LASTEXITCODE}finally{$ErrorActionPreference=$old};if($code-eq 0){throw "$name unexpectedly passed: $db"}}
if(-not(Get-Command docker -ErrorAction SilentlyContinue)){throw 'Docker is required.'}
Push-Location $root
try{
 D -Arguments @('run','--rm','-d','--name',$container,'-e',"POSTGRES_PASSWORD=$password",'-p',"${HostPort}:5432",'postgres:18')
 $ready=$false;for($i=0;$i-lt 30;$i++){docker exec $container pg_isready -U postgres *> $null;if($LASTEXITCODE-eq 0){$ready=$true;break};Start-Sleep -Milliseconds 500};if(-not$ready){throw 'PostgreSQL 18 not ready'}
 D -Arguments @('exec',$container,'mkdir','-p',$scriptRoot)
 foreach($file in Get-ChildItem (Join-Path $root 'scripts\postgresql\*.sql')){D -Arguments @('cp',$file.FullName,"${container}:${scriptRoot}/$($file.Name)")}
 Db cropqc_transfer_fresh;Ef cropqc_transfer_fresh $null;Script cropqc_transfer_fresh verify-transfer-custody-workflow.sql;Gate cropqc_transfer_fresh;$freshSig=Signature cropqc_transfer_fresh
 Db cropqc_transfer_upgrade;Ef cropqc_transfer_upgrade $previous;$before=Scalar cropqc_transfer_upgrade 'select count(*)||''|''||md5(string_agg("MigrationId"||''|''||"ProductVersion",'';'' order by "MigrationId")) from "__EFMigrationsHistory";';Script cropqc_transfer_upgrade preflight-transfer-custody-workflow.sql;Script cropqc_transfer_upgrade apply-transfer-custody-workflow-schema.sql;Script cropqc_transfer_upgrade apply-transfer-custody-workflow-schema.sql;Gate cropqc_transfer_upgrade;$after=Scalar cropqc_transfer_upgrade 'select count(*)||''|''||md5(string_agg("MigrationId"||''|''||"ProductVersion",'';'' order by "MigrationId")) from "__EFMigrationsHistory";';if($before-ne$after){throw 'Migration history changed'};$compatSig=Signature cropqc_transfer_upgrade;if($freshSig-ne$compatSig){throw "Catalog parity failed`n$freshSig`n$compatSig"}
 Db cropqc_transfer_partial;Ef cropqc_transfer_partial $previous;Sql cropqc_transfer_partial 'alter table "RoomInventoryAdjustments" add column "InterCrewTransferId" bigint;';MustFail cropqc_transfer_partial preflight-transfer-custody-workflow.sql
 Db cropqc_transfer_rollback;Ef cropqc_transfer_rollback $previous;$old=$ErrorActionPreference;try{$ErrorActionPreference='Continue';docker exec $container psql -X -v ON_ERROR_STOP=1 -U postgres -d cropqc_transfer_rollback -c "set cropqc.test_force_transfer_custody_failure='on'" -f "$scriptRoot/apply-transfer-custody-workflow-schema.sql" *> $null;$forced=$LASTEXITCODE}finally{$ErrorActionPreference=$old};if($forced-eq 0){throw 'Forced rollback unexpectedly passed'};if((Scalar cropqc_transfer_rollback 'select case when to_regclass(''"InterCrewTransfers"'') is null and to_regclass(''"OutsideWarehouses"'') is null then ''absent'' else ''partial'' end;')-ne'absent'){throw 'Forced rollback left transfer objects'}
 'Fresh PostgreSQL 18 EF migration and 836-object gate: PASS';'Compatibility State A/apply/verify/repeat State B: PASS';"Catalog parity: PASS ($freshSig)";"Migration history unchanged: PASS ($before)";'Partial State C and forced rollback: PASS'
}finally{Pop-Location;if(-not$KeepContainer){$old=$ErrorActionPreference;try{$ErrorActionPreference='Continue';docker rm -f $container *> $null}finally{$ErrorActionPreference=$old}}}
